import React from 'react'
import { storiesOf } from '@storybook/react'
import withThemeProvider from '../../ui/theme/ThemeDecorator'
import { ReportSpain } from '../../components/templates/ReportsSpain/ReportSpain'
import i18nObj from '../i18n.json'
const ReportsSpainStory: React.FC = () => {
  const formValues = {
    cif: '423423uy',
    name: 'Test Name',
    address: 'C/San Antón, 13',
    province: 'Burgos',
    postalcode: '09460',
    phone: '+42625589030',
    fax: '+420313414515@faxmaker.com',
    legalForm: '',
    constitutionDateMM: '12',
    constitutionDateAAAA: '1985',
    numberBranches: '23',
    branches: 'Branch1, Branch2',
    employess: '14',
    socialCapital: '100000000',
    disbursedCapital: '345345',
    cnae: 'A011',
    typeProducts: 'Inmobiliaria',
    estimatedSales: '34',
    banksOperates: 'Santander, ING, La Caixa',
    banksReference: '',
    customerConcentration: 'ok',
    mainCustomers: 'ok',
    mainSuppliers: 'Proveedor 1 Provedor 2',
    competitors: 'Competidor 1, Competidor 2',
    exportPercentage: '12',
    countriesExports: 'EEUU, Francia',
    shareHolders: 'Accionista 1',
    participated: 'Participada 1',
    opinionCompany: '',
    opinionSector: '',
    comments: 'Comentario 1',
    confidentiality: 'true',
    consolidated: 'true',
    generateAlert: 'true',
    // BALANCE
    originBalances: 'Origen Balances: ',
    balanceClosingDates1Day: 'Fecha Cierre Balance [1]: ',
    balanceClosingDates1Month: '3',
    balanceClosingDates1Year: '1',
    balanceClosingDates2Day: 'Fecha Cierre Balance [2]: ',
    balanceClosingDates2Month: '2',
    balanceClosingDates2Year: '5',
    balanceClosingDates3Day: '4',
    balanceClosingDates3Month: '5',
    balanceClosingDates3Year: '2',
    balanceClosingMonth1: '2',
    balanceClosingMonth2: '4',
    balanceClosingMonth3: '5',
    noncurrentassets1: '1',
    noncurrentassets2: '2',
    noncurrentassets3: '3',
    intangible1: '1',
    intangible2: '2',
    intangible3: '3',
    developing1: '1',
    developing2: '2',
    developing3: '3',
    concessions1: '1',
    concessions2: '2',
    concessions3: '3',
    patents1: '1',
    patents2: '2',
    patents3: '3',
    goodwill1: '1',
    goodwill2: '2',
    goodwill3: '3',
    computerApplications1: '1',
    computerApplications2: '2',
    computerApplications3: '3',
    investigation1: '1',
    investigation2: '2',
    investigation3: '3',
    anotherIntangible1: '1',
    anotherIntangible2: '2',
    anotherIntangible3: '3',
    inmobilizedMaterial1: '1',
    inmobilizedMaterial2: '2',
    inmobilizedMaterial3: '3',
    land1: '1',
    land2: '2',
    land3: '3',
    buildings1: '1',
    buildings2: '2',
    buildings3: '3',
    investmentsInGroup1: '1',
    investmentsInGroup2: '2',
    investmentsInGroup3: '3',
    financialInvestmentsLongTerm1: '1',
    financialInvestmentsLongTerm2: '2',
    financialInvestmentsLongTerm3: '3',
    heritageInstrument1: '1',
    heritageInstrument2: '2',
    heritageInstrument3: '3',
    thirdPartyCredits1: '1',
    thirdPartyCredits2: '2',
    thirdPartyCredits3: '3',
    representativeValuesDebt1: '1',
    representativeValuesDebt2: '2',
    representativeValuesDebt3: '3',
    derivatives1: '1',
    derivatives2: '2',
    derivatives3: '3',
    otherFinancialAssets1: '1',
    otherFinancialAssets2: '2',
    otherFinancialAssets3: '3',
    otherInvestments1: '1',
    otherInvestments2: '2',
    otherInvestments3: '3',
    taxAssetsDeferred1: '1',
    taxAssetsDeferred2: '2',
    taxAssetsDeferred3: '3',
    commercialDebtsNoCurrent1: '1',
    commercialDebtsNoCurrent2: '2',
    commercialDebtsNoCurrent3: '3',
    currentAssets1: '1',
    currentAssets2: '2',
    currentAssets3: '3',
    nonCurrentAssetsHelpForSale1: '1',
    nonCurrentAssetsHelpForSale2: '2',
    nonCurrentAssetsHelpForSale3: '3',
    stocks1: '1',
    stocks2: '2',
    stocks3: '3',
    commercial1: '1',
    commercial2: '2',
    commercial3: '3',
    rawMaterials1: '1',
    rawMaterials2: '2',
    rawMaterials3: '3',
    productsInProgress1: '1',
    productsInProgress2: '2',
    productsInProgress3: '3',
    finishedProducts1: '1',
    finishedProducts2: '2',
    finishedProducts3: '3',
    byProductsWaste1: '1',
    byProductsWaste2: '2',
    byProductsWaste3: '3',
    advancedToSupplier1: '1',
    advancedToSupplier2: '2',
    advancedToSupplier3: '3',
    commercialDebtors1: '1',
    commercialDebtors2: '2',
    commercialDebtors3: '3',
    customersBySalesServicesBenefits1: '1',
    customersBySalesServicesBenefits2: '2',
    customersBySalesServicesBenefits3: '3',
    clientsOfGroupCompanies1: '1',
    clientsOfGroupCompanies2: '2',
    clientsOfGroupCompanies3: '3',
    sundryDebtors1: '1',
    sundryDebtors2: '2',
    sundryDebtors3: '3',
    staff1: '1',
    staff2: '2',
    staff3: '3',
    taxAssetsStreams1: '1',
    taxAssetsStreams2: '2',
    taxAssetsStreams3: '3',
    otherAdministrationCredits1: '1',
    otherAdministrationCredits2: '2',
    otherAdministrationCredits3: '3',
    shareholders1: '1',
    shareholders2: '2',
    shareholders3: '3',
    investmentsInGroupCompaniesAndAssociates1: '1',
    investmentsInGroupCompaniesAndAssociates2: '2',
    investmentsInGroupCompaniesAndAssociates3: '3',
    financialInvestmentsShortTerm1: '1',
    financialInvestmentsShortTerm2: '2',
    financialInvestmentsShortTerm3: '3',
    companyCredits1: '1',
    companyCredits2: '2',
    companyCredits3: '3',
    equityInstrument1: '1',
    equityInstrument2: '2',
    equityInstrument3: '3',
    representativeValuesOfDebt1: '1',
    representativeValuesOfDebt2: '2',
    representativeValuesOfDebt3: '3',
    derivatives21: '1',
    derivatives22: '2',
    derivatives23: '3',
    otherFinancialAssets21: '1',
    otherFinancialAssets22: '2',
    otherFinancialAssets23: '3',
    otherInvestments21: '1',
    otherInvestments22: '2',
    otherInvestments23: '3',
    accrualsToShortTerm1: '1',
    accrualsToShortTerm2: '2',
    accrualsToShortTerm3: '3',
    cashOthersLiquidAssetsEquivalents1: '1',
    cashOthersLiquidAssetsEquivalents2: '2',
    cashOthersLiquidAssetsEquivalents3: '3',
    treasury1: '1',
    treasury2: '2',
    treasury3: '3',
    otherLiquidAssetsEquivalents1: '1',
    otherLiquidAssetsEquivalents2: '2',
    otherLiquidAssetsEquivalents3: '3',
    totalAssets1: '1',
    totalAssets2: '2',
    totalAssets3: '3',
    equity1: '1',
    equity2: '2',
    equity3: '3',
    ownFunds1: '1',
    ownFunds2: '2',
    ownFunds3: '3',
    capital1: '1',
    capital2: '2',
    capital3: '3',
    capitalDeed1: '1',
    capitalDeed2: '2',
    capitalDeed3: '3',
    capitalNotRequired1: '1',
    capitalNotRequired2: '2',
    capitalNotRequired3: '3',
    issuePremium1: '1',
    issuePremium2: '2',
    issuePremium3: '3',
    bookings1: '1',
    bookings2: '2',
    bookings3: '3',
    actionsAndShares1: '1',
    actionsAndShares2: '2',
    actionsAndShares3: '3',
    resultOfExercisesPrevious1: '1',
    resultOfExercisesPrevious2: '2',
    resultOfExercisesPrevious3: '3',
    otherContributionsFromPartners1: '1',
    otherContributionsFromPartners2: '2',
    otherContributionsFromPartners3: '3',
    resultExercise1: '1',
    resultExercise2: '2',
    resultExercise3: '3',
    dividendOnAccount1: '1',
    dividendOnAccount2: '2',
    dividendOnAccount3: '3',
    otherInstrumentsHeritage1: '1',
    otherInstrumentsHeritage2: '2',
    otherInstrumentsHeritage3: '3',
    adjustmentsChangesOfValue1: '1',
    adjustmentsChangesOfValue2: '2',
    adjustmentsChangesOfValue3: '3',
    financialAssetsAvailableForSale1: '1',
    financialAssetsAvailableForSale2: '2',
    financialAssetsAvailableForSale3: '3',
    operationsCoverage1: '1',
    operationsCoverage2: '2',
    operationsCoverage3: '3',
    nonCurrentAssetsRelatedLiabilities1: '1',
    nonCurrentAssetsRelatedLiabilities2: '2',
    nonCurrentAssetsRelatedLiabilities3: '3',
    differencesOfConversion1: '1',
    differencesOfConversion2: '2',
    differencesOfConversion3: '3',
    others1: '1',
    others2: '2',
    others3: '3',
    grantsDonationsBequestReceived1: '1',
    grantsDonationsBequestReceived2: '2',
    grantsDonationsBequestReceived3: '3',
    nonCurrentLiabilities1: '1',
    nonCurrentLiabilities2: '2',
    nonCurrentLiabilities3: '3',
    longTermProvisions1: '1',
    longTermProvisions2: '2',
    longTermProvisions3: '3',
    provisionsRestructuring1: '1',
    provisionsRestructuring2: '2',
    provisionsRestructuring3: '3',
    longTermDebts1: '1',
    longTermDebts2: '2',
    longTermDebts3: '3',
    obligationsOtherSecuritiesNegotiable1: '1',
    obligationsOtherSecuritiesNegotiable2: '2',
    obligationsOtherSecuritiesNegotiable3: '3',
    debtsEntitiesCredit1: '1',
    debtsEntitiesCredit2: '2',
    debtsEntitiesCredit3: '3',
    creditorsFinancialLeasing1: '1',
    creditorsFinancialLeasing2: '2',
    creditorsFinancialLeasing3: '3',
    derivatives221: '1',
    derivatives222: '2',
    derivatives223: '3',
    otherFinancialLiabilities1: '1',
    otherFinancialLiabilities2: '2',
    otherFinancialLiabilities3: '3',
    debtsCompaniesGroupAssociatedLongTerm1: '1',
    debtsCompaniesGroupAssociatedLongTerm2: '2',
    debtsCompaniesGroupAssociatedLongTerm3: '3',
    taxLiabilitiesDeferred1: '1',
    taxLiabilitiesDeferred2: '2',
    taxLiabilitiesDeferred3: '3',
    longAccrualsTerm1: '1',
    longAccrualsTerm2: '2',
    longAccrualsTerm3: '3',
    tradeCreditorsNoCurrents1: '1',
    tradeCreditorsNoCurrents2: '2',
    tradeCreditorsNoCurrents3: '3',
    debtsSpecialFeaturesLongTerm1: '1',
    debtsSpecialFeaturesLongTerm2: '2',
    debtsSpecialFeaturesLongTerm3: '3',
    currentLiabilities1: '1',
    currentLiabilities2: '2',
    currentLiabilities3: '3',
    liabilitiesRelatedNonCurrentAssetsHelpForSale1: '1',
    liabilitiesRelatedNonCurrentAssetsHelpForSale2: '2',
    liabilitiesRelatedNonCurrentAssetsHelpForSale3: '3',
    shortProvisionsTerm1: '1',
    shortProvisionsTerm2: '2',
    shortProvisionsTerm3: '3',
    shortTermDebts1: '1',
    shortTermDebts2: '2',
    shortTermDebts3: '3',
    obligationsOtherSecuritiesNegotiable21: '1',
    obligationsOtherSecuritiesNegotiable22: '2',
    obligationsOtherSecuritiesNegotiable23: '3',
    debtsEntitiesOfCredit1: '1',
    debtsEntitiesOfCredit2: '2',
    debtsEntitiesOfCredit3: '3',
    creditorsFinancialLeasing21: '1',
    creditorsFinancialLeasing22: '2',
    creditorsFinancialLeasing23: '3',
    derivatives31: '1',
    derivatives32: '2',
    derivatives33: '3',
    otherFinancialLiabilities21: '1',
    otherFinancialLiabilities22: '2',
    otherFinancialLiabilities23: '3',
    debtsCompaniesGroupAssociatedShortTerm1: '1',
    debtsCompaniesGroupAssociatedShortTerm2: '2',
    debtsCompaniesGroupAssociatedShortTerm3: '3',
    tradeCreditorsOtherAccountsPayable1: '1',
    tradeCreditorsOtherAccountsPayable2: '2',
    tradeCreditorsOtherAccountsPayable3: '3',
    suppliers1: '1',
    suppliers2: '2',
    suppliers3: '3',
    suppliersCompaniesGroupAssociates1: '1',
    suppliersCompaniesGroupAssociates2: '2',
    suppliersCompaniesGroupAssociates3: '3',
    variousCreditors1: '1',
    variousCreditors2: '2',
    variousCreditors3: '3',
    personnelSalariesStillPaid1: '1',
    personnelSalariesStillPaid2: '2',
    personnelSalariesStillPaid3: '3',
    taxLiabilitiesStream1: '1',
    taxLiabilitiesStream2: '2',
    taxLiabilitiesStream3: '3',
    otherDebtsPublicAdministrations1: '1',
    otherDebtsPublicAdministrations2: '2',
    otherDebtsPublicAdministrations3: '3',
    advancesFromClients1: '1',
    advancesFromClients2: '2',
    advancesFromClients3: '3',
    accrualsShortTerm1: '1',
    accrualsShortTerm2: '2',
    accrualsShortTerm3: '3',
    debtsSpecialFeaturesShortTerm1: '1',
    debtsSpecialFeaturesShortTerm2: '2',
    debtsSpecialFeaturesShortTerm3: '3',
    totalEquityLiabilitiesABC1: '1',
    totalEquityLiabilitiesABC2: '2',
    totalEquityLiabilitiesABC3: '3',
    netAmountFigureBusiness1: '1',
    netAmountFigureBusiness2: '2',
    netAmountFigureBusiness3: '3',
    sales1: '1',
    sales2: '2',
    sales3: '3',
    variationProductStocksCompleted1: '1',
    variationProductStocksCompleted2: '2',
    variationProductStocksCompleted3: '3',
    workCarriedOutCompanyAsset1: '1',
    workCarriedOutCompanyAsset2: '2',
    workCarriedOutCompanyAsset3: '3',
    procurement1: '1',
    procurement2: '2',
    procurement3: '3',
    otherIncomeFromExplotation1: '1',
    otherIncomeFromExplotation2: '2',
    otherIncomeFromExplotation3: '3',
    personnelExpenses1: '1',
    personnelExpenses2: '2',
    personnelExpenses3: '3',
    otherExpensesExplotation1: '1',
    otherExpensesExplotation2: '2',
    otherExpensesExplotation3: '3',
    amortizationImmobilized1: '1',
    amortizationImmobilized2: '2',
    amortizationImmobilized3: '3',
    imputationFixedAssetsGrants1: '1',
    imputationFixedAssetsGrants2: '2',
    imputationFixedAssetsGrants3: '3',
    excessProvisions1: '1',
    excessProvisions2: '2',
    excessProvisions3: '3',
    impairmentResultDisposalsImmobilized1: '1',
    impairmentResultDisposalsImmobilized2: '2',
    impairmentResultDisposalsImmobilized3: '3',
    impairmentLosses1: '1',
    impairmentLosses2: '2',
    impairmentLosses3: '3',
    resultsDisposalsOther1: '1',
    resultsDisposalsOther2: '2',
    resultsDisposalsOther3: '3',
    negativeDifferencesBusinessCombinations1: '1',
    negativeDifferencesBusinessCombinations2: '2',
    negativeDifferencesBusinessCombinations3: '3',
    otherResults1: '1',
    otherResults2: '2',
    otherResults3: '3',
    resultOperation1: '1',
    resultOperation2: '2',
    resultOperation3: '3',
    financialIncome1: '1',
    financialIncome2: '2',
    financialIncome3: '3',
    financialExpenses1: '1',
    financialExpenses2: '2',
    financialExpenses3: '3',
    variationValueReasonableInstruments1: '1',
    variationValueReasonableInstruments2: '2',
    variationValueReasonableInstruments3: '3',
    exchangeDifferences1: '1',
    exchangeDifferences2: '2',
    exchangeDifferences3: '3',
    impairmentResultDisposalsFinnacialInstruments1: '1',
    impairmentResultDisposalsFinnacialInstruments2: '2',
    impairmentResultDisposalsFinnacialInstruments3: '3',
    resultFinancial1: '1',
    resultFinancial2: '2',
    resultFinancial3: '3',
    resultBeforeTaxes1: '1',
    resultBeforeTaxes2: '2',
    resultBeforeTaxes3: '3',
    taxesOnBenefits1: '1',
    taxesOnBenefits2: '2',
    taxesOnBenefits3: '3',
    resultExerciseFromOperationsContinued1: '1',
    resultExerciseFromOperationsContinued2: '2',
    resultExerciseFromOperationsContinued3: '3',
    profitYearOperationsInterrupted1: '1',
    profitYearOperationsInterrupted2: '2',
    profitYearOperationsInterrupted3: '3',
    auditConclusion: 'xxx',
    auditComments: 'xxx'

  }

  const legalForm = [
    {
      value: '1',
      result: 'Opción 1'
    },
    {
      value: '2',
      result: 'Opción 2'
    },
    {
      value: '3',
      result: 'Opción 3'
    }
  ]
  const banksReferences = [
    {
      value: '1',
      result: 'Opción 1'
    },
    {
      value: '2',
      result: 'Opción 2'
    },
    {
      value: '3',
      result: 'Opción 3'
    }
  ]

  const opinionsCompany = [
    {
      value: '1',
      result: 'Opción 1'
    },
    {
      value: '2',
      result: 'Opción 2'
    },
    {
      value: '3',
      result: 'Opción 3'
    }
  ]

  const opinionsSector = [
    {
      value: '1',
      result: 'Opción 1'
    },
    {
      value: '2',
      result: 'Opción 2'
    },
    {
      value: '3',
      result: 'Opción 3'
    }
  ]

  const originsBalances = [
    {
      value: '1',
      result: 'Opción 1'
    },
    {
      value: '2',
      result: 'Opción 2'
    },
    {
      value: '3',
      result: 'Opción 3'
    }
  ]

  const auditConclusion = [
    {
      value: '1',
      result: 'Opción 1'
    },
    {
      value: '2',
      result: 'Opción 2'
    },
    {
      value: '3',
      result: 'Opción 3'
    }
  ]

  const formValuesBalance = {
    originBalances: 'Origen Balances: ',
    balanceClosingDates1Day: 'Fecha Cierre Balance [1]: ',
    balanceClosingDates1Month: '3',
    balanceClosingDates1Year: '1',
    balanceClosingDates2Day: 'Fecha Cierre Balance [2]: ',
    balanceClosingDates2Month: '2',
    balanceClosingDates2Year: '5',
    balanceClosingDates3Day: '4',
    balanceClosingDates3Month: '5',
    balanceClosingDates3Year: '2',
    balanceClosingMonth1: '2',
    balanceClosingMonth2: '4',
    balanceClosingMonth3: '5',
    noncurrentassets1: '1',
    noncurrentassets2: '2',
    noncurrentassets3: '3',
    intangible1: '1',
    intangible2: '2',
    intangible3: '3',
    developing1: '1',
    developing2: '2',
    developing3: '3',
    concessions1: '1',
    concessions2: '2',
    concessions3: '3',
    patents1: '1',
    patents2: '2',
    patents3: '3',
    goodwill1: '1',
    goodwill2: '2',
    goodwill3: '3',
    computerApplications1: '1',
    computerApplications2: '2',
    computerApplications3: '3',
    investigation1: '1',
    investigation2: '2',
    investigation3: '3',
    anotherIntangible1: '1',
    anotherIntangible2: '2',
    anotherIntangible3: '3',
    inmobilizedMaterial1: '1',
    inmobilizedMaterial2: '2',
    inmobilizedMaterial3: '3',
    land1: '1',
    land2: '2',
    land3: '3',
    buildings1: '1',
    buildings2: '2',
    buildings3: '3',
    investmentsInGroup1: '1',
    investmentsInGroup2: '2',
    investmentsInGroup3: '3',
    financialInvestmentsLongTerm1: '1',
    financialInvestmentsLongTerm2: '2',
    financialInvestmentsLongTerm3: '3',
    heritageInstrument1: '1',
    heritageInstrument2: '2',
    heritageInstrument3: '3',
    thirdPartyCredits1: '1',
    thirdPartyCredits2: '2',
    thirdPartyCredits3: '3',
    representativeValuesDebt1: '1',
    representativeValuesDebt2: '2',
    representativeValuesDebt3: '3',
    derivatives1: '1',
    derivatives2: '2',
    derivatives3: '3',
    otherFinancialAssets1: '1',
    otherFinancialAssets2: '2',
    otherFinancialAssets3: '3',
    otherInvestments1: '1',
    otherInvestments2: '2',
    otherInvestments3: '3',
    taxAssetsDeferred1: '1',
    taxAssetsDeferred2: '2',
    taxAssetsDeferred3: '3',
    commercialDebtsNoCurrent1: '1',
    commercialDebtsNoCurrent2: '2',
    commercialDebtsNoCurrent3: '3',
    currentAssets1: '1',
    currentAssets2: '2',
    currentAssets3: '3',
    nonCurrentAssetsHelpForSale1: '1',
    nonCurrentAssetsHelpForSale2: '2',
    nonCurrentAssetsHelpForSale3: '3',
    stocks1: '1',
    stocks2: '2',
    stocks3: '3',
    commercial1: '1',
    commercial2: '2',
    commercial3: '3',
    rawMaterials1: '1',
    rawMaterials2: '2',
    rawMaterials3: '3',
    productsInProgress1: '1',
    productsInProgress2: '2',
    productsInProgress3: '3',
    finishedProducts1: '1',
    finishedProducts2: '2',
    finishedProducts3: '3',
    byProductsWaste1: '1',
    byProductsWaste2: '2',
    byProductsWaste3: '3',
    advancedToSupplier1: '1',
    advancedToSupplier2: '2',
    advancedToSupplier3: '3',
    commercialDebtors1: '1',
    commercialDebtors2: '2',
    commercialDebtors3: '3',
    customersBySalesServicesBenefits1: '1',
    customersBySalesServicesBenefits2: '2',
    customersBySalesServicesBenefits3: '3',
    clientsOfGroupCompanies1: '1',
    clientsOfGroupCompanies2: '2',
    clientsOfGroupCompanies3: '3',
    sundryDebtors1: '1',
    sundryDebtors2: '2',
    sundryDebtors3: '3',
    staff1: '1',
    staff2: '2',
    staff3: '3',
    taxAssetsStreams1: '1',
    taxAssetsStreams2: '2',
    taxAssetsStreams3: '3',
    otherAdministrationCredits1: '1',
    otherAdministrationCredits2: '2',
    otherAdministrationCredits3: '3',
    shareholders1: '1',
    shareholders2: '2',
    shareholders3: '3',
    investmentsInGroupCompaniesAndAssociates1: '1',
    investmentsInGroupCompaniesAndAssociates2: '2',
    investmentsInGroupCompaniesAndAssociates3: '3',
    financialInvestmentsShortTerm1: '1',
    financialInvestmentsShortTerm2: '2',
    financialInvestmentsShortTerm3: '3',
    companyCredits1: '1',
    companyCredits2: '2',
    companyCredits3: '3',
    equityInstrument1: '1',
    equityInstrument2: '2',
    equityInstrument3: '3',
    representativeValuesOfDebt1: '1',
    representativeValuesOfDebt2: '2',
    representativeValuesOfDebt3: '3',
    derivatives21: '1',
    derivatives22: '2',
    derivatives23: '3',
    otherFinancialAssets21: '1',
    otherFinancialAssets22: '2',
    otherFinancialAssets23: '3',
    otherInvestments21: '1',
    otherInvestments22: '2',
    otherInvestments23: '3',
    accrualsToShortTerm1: '1',
    accrualsToShortTerm2: '2',
    accrualsToShortTerm3: '3',
    cashOthersLiquidAssetsEquivalents1: '1',
    cashOthersLiquidAssetsEquivalents2: '2',
    cashOthersLiquidAssetsEquivalents3: '3',
    treasury1: '1',
    treasury2: '2',
    treasury3: '3',
    otherLiquidAssetsEquivalents1: '1',
    otherLiquidAssetsEquivalents2: '2',
    otherLiquidAssetsEquivalents3: '3',
    totalAssets1: '1',
    totalAssets2: '2',
    totalAssets3: '3',
    equity1: '1',
    equity2: '2',
    equity3: '3',
    ownFunds1: '1',
    ownFunds2: '2',
    ownFunds3: '3',
    capital1: '1',
    capital2: '2',
    capital3: '3',
    capitalDeed1: '1',
    capitalDeed2: '2',
    capitalDeed3: '3',
    capitalNotRequired1: '1',
    capitalNotRequired2: '2',
    capitalNotRequired3: '3',
    issuePremium1: '1',
    issuePremium2: '2',
    issuePremium3: '3',
    bookings1: '1',
    bookings2: '2',
    bookings3: '3',
    actionsAndShares1: '1',
    actionsAndShares2: '2',
    actionsAndShares3: '3',
    resultOfExercisesPrevious1: '1',
    resultOfExercisesPrevious2: '2',
    resultOfExercisesPrevious3: '3',
    otherContributionsFromPartners1: '1',
    otherContributionsFromPartners2: '2',
    otherContributionsFromPartners3: '3',
    resultExercise1: '1',
    resultExercise2: '2',
    resultExercise3: '3',
    dividendOnAccount1: '1',
    dividendOnAccount2: '2',
    dividendOnAccount3: '3',
    otherInstrumentsHeritage1: '1',
    otherInstrumentsHeritage2: '2',
    otherInstrumentsHeritage3: '3',
    adjustmentsChangesOfValue1: '1',
    adjustmentsChangesOfValue2: '2',
    adjustmentsChangesOfValue3: '3',
    financialAssetsAvailableForSale1: '1',
    financialAssetsAvailableForSale2: '2',
    financialAssetsAvailableForSale3: '3',
    operationsCoverage1: '1',
    operationsCoverage2: '2',
    operationsCoverage3: '3',
    nonCurrentAssetsRelatedLiabilities1: '1',
    nonCurrentAssetsRelatedLiabilities2: '2',
    nonCurrentAssetsRelatedLiabilities3: '3',
    differencesOfConversion1: '1',
    differencesOfConversion2: '2',
    differencesOfConversion3: '3',
    others1: '1',
    others2: '2',
    others3: '3',
    grantsDonationsBequestReceived1: '1',
    grantsDonationsBequestReceived2: '2',
    grantsDonationsBequestReceived3: '3',
    nonCurrentLiabilities1: '1',
    nonCurrentLiabilities2: '2',
    nonCurrentLiabilities3: '3',
    longTermProvisions1: '1',
    longTermProvisions2: '2',
    longTermProvisions3: '3',
    provisionsRestructuring1: '1',
    provisionsRestructuring2: '2',
    provisionsRestructuring3: '3',
    longTermDebts1: '1',
    longTermDebts2: '2',
    longTermDebts3: '3',
    obligationsOtherSecuritiesNegotiable1: '1',
    obligationsOtherSecuritiesNegotiable2: '2',
    obligationsOtherSecuritiesNegotiable3: '3',
    debtsEntitiesCredit1: '1',
    debtsEntitiesCredit2: '2',
    debtsEntitiesCredit3: '3',
    creditorsFinancialLeasing1: '1',
    creditorsFinancialLeasing2: '2',
    creditorsFinancialLeasing3: '3',
    derivatives221: '1',
    derivatives222: '2',
    derivatives223: '3',
    otherFinancialLiabilities1: '1',
    otherFinancialLiabilities2: '2',
    otherFinancialLiabilities3: '3',
    debtsCompaniesGroupAssociatedLongTerm1: '1',
    debtsCompaniesGroupAssociatedLongTerm2: '2',
    debtsCompaniesGroupAssociatedLongTerm3: '3',
    taxLiabilitiesDeferred1: '1',
    taxLiabilitiesDeferred2: '2',
    taxLiabilitiesDeferred3: '3',
    longAccrualsTerm1: '1',
    longAccrualsTerm2: '2',
    longAccrualsTerm3: '3',
    tradeCreditorsNoCurrents1: '1',
    tradeCreditorsNoCurrents2: '2',
    tradeCreditorsNoCurrents3: '3',
    debtsSpecialFeaturesLongTerm1: '1',
    debtsSpecialFeaturesLongTerm2: '2',
    debtsSpecialFeaturesLongTerm3: '3',
    currentLiabilities1: '1',
    currentLiabilities2: '2',
    currentLiabilities3: '3',
    liabilitiesRelatedNonCurrentAssetsHelpForSale1: '1',
    liabilitiesRelatedNonCurrentAssetsHelpForSale2: '2',
    liabilitiesRelatedNonCurrentAssetsHelpForSale3: '3',
    shortProvisionsTerm1: '1',
    shortProvisionsTerm2: '2',
    shortProvisionsTerm3: '3',
    shortTermDebts1: '1',
    shortTermDebts2: '2',
    shortTermDebts3: '3',
    obligationsOtherSecuritiesNegotiable21: '1',
    obligationsOtherSecuritiesNegotiable22: '2',
    obligationsOtherSecuritiesNegotiable23: '3',
    debtsEntitiesOfCredit1: '1',
    debtsEntitiesOfCredit2: '2',
    debtsEntitiesOfCredit3: '3',
    creditorsFinancialLeasing21: '1',
    creditorsFinancialLeasing22: '2',
    creditorsFinancialLeasing23: '3',
    derivatives31: '1',
    derivatives32: '2',
    derivatives33: '3',
    otherFinancialLiabilities21: '1',
    otherFinancialLiabilities22: '2',
    otherFinancialLiabilities23: '3',
    debtsCompaniesGroupAssociatedShortTerm1: '1',
    debtsCompaniesGroupAssociatedShortTerm2: '2',
    debtsCompaniesGroupAssociatedShortTerm3: '3',
    tradeCreditorsOtherAccountsPayable1: '1',
    tradeCreditorsOtherAccountsPayable2: '2',
    tradeCreditorsOtherAccountsPayable3: '3',
    suppliers1: '1',
    suppliers2: '2',
    suppliers3: '3',
    suppliersCompaniesGroupAssociates1: '1',
    suppliersCompaniesGroupAssociates2: '2',
    suppliersCompaniesGroupAssociates3: '3',
    variousCreditors1: '1',
    variousCreditors2: '2',
    variousCreditors3: '3',
    personnelSalariesStillPaid1: '1',
    personnelSalariesStillPaid2: '2',
    personnelSalariesStillPaid3: '3',
    taxLiabilitiesStream1: '1',
    taxLiabilitiesStream2: '2',
    taxLiabilitiesStream3: '3',
    otherDebtsPublicAdministrations1: '1',
    otherDebtsPublicAdministrations2: '2',
    otherDebtsPublicAdministrations3: '3',
    advancesFromClients1: '1',
    advancesFromClients2: '2',
    advancesFromClients3: '3',
    accrualsShortTerm1: '1',
    accrualsShortTerm2: '2',
    accrualsShortTerm3: '3',
    debtsSpecialFeaturesShortTerm1: '1',
    debtsSpecialFeaturesShortTerm2: '2',
    debtsSpecialFeaturesShortTerm3: '3',
    totalEquityLiabilitiesABC1: '1',
    totalEquityLiabilitiesABC2: '2',
    totalEquityLiabilitiesABC3: '3',
    netAmountFigureBusiness1: '1',
    netAmountFigureBusiness2: '2',
    netAmountFigureBusiness3: '3',
    sales1: '1',
    sales2: '2',
    sales3: '3',
    variationProductStocksCompleted1: '1',
    variationProductStocksCompleted2: '2',
    variationProductStocksCompleted3: '3',
    workCarriedOutCompanyAsset1: '1',
    workCarriedOutCompanyAsset2: '2',
    workCarriedOutCompanyAsset3: '3',
    procurement1: '1',
    procurement2: '2',
    procurement3: '3',
    otherIncomeFromExplotation1: '1',
    otherIncomeFromExplotation2: '2',
    otherIncomeFromExplotation3: '3',
    personnelExpenses1: '1',
    personnelExpenses2: '2',
    personnelExpenses3: '3',
    otherExpensesExplotation1: '1',
    otherExpensesExplotation2: '2',
    otherExpensesExplotation3: '3',
    amortizationImmobilized1: '1',
    amortizationImmobilized2: '2',
    amortizationImmobilized3: '3',
    imputationFixedAssetsGrants1: '1',
    imputationFixedAssetsGrants2: '2',
    imputationFixedAssetsGrants3: '3',
    excessProvisions1: '1',
    excessProvisions2: '2',
    excessProvisions3: '3',
    impairmentResultDisposalsImmobilized1: '1',
    impairmentResultDisposalsImmobilized2: '2',
    impairmentResultDisposalsImmobilized3: '3',
    impairmentLosses1: '1',
    impairmentLosses2: '2',
    impairmentLosses3: '3',
    resultsDisposalsOther1: '1',
    resultsDisposalsOther2: '2',
    resultsDisposalsOther3: '3',
    negativeDifferencesBusinessCombinations1: '1',
    negativeDifferencesBusinessCombinations2: '2',
    negativeDifferencesBusinessCombinations3: '3',
    otherResults1: '1',
    otherResults2: '2',
    otherResults3: '3',
    resultOperation1: '1',
    resultOperation2: '2',
    resultOperation3: '3',
    financialIncome1: '1',
    financialIncome2: '2',
    financialIncome3: '3',
    financialExpenses1: '1',
    financialExpenses2: '2',
    financialExpenses3: '3',
    variationValueReasonableInstruments1: '1',
    variationValueReasonableInstruments2: '2',
    variationValueReasonableInstruments3: '3',
    exchangeDifferences1: '1',
    exchangeDifferences2: '2',
    exchangeDifferences3: '3',
    impairmentResultDisposalsFinnacialInstruments1: '1',
    impairmentResultDisposalsFinnacialInstruments2: '2',
    impairmentResultDisposalsFinnacialInstruments3: '3',
    resultFinancial1: '1',
    resultFinancial2: '2',
    resultFinancial3: '3',
    resultBeforeTaxes1: '1',
    resultBeforeTaxes2: '2',
    resultBeforeTaxes3: '3',
    taxesOnBenefits1: '1',
    taxesOnBenefits2: '2',
    taxesOnBenefits3: '3',
    resultExerciseFromOperationsContinued1: '1',
    resultExerciseFromOperationsContinued2: '2',
    resultExerciseFromOperationsContinued3: '3',
    profitYearOperationsInterrupted1: '1',
    profitYearOperationsInterrupted2: '2',
    profitYearOperationsInterrupted3: '3',
    auditConclusion: 'xxx',
    auditComments: 'xxx'
  }

  const handleSave = (params): void => console.log(params) // eslint-disable-line
  const handleCancel = (): void => alert('cancel')
  const handleAccept = (): void => alert('accept')

  const validateOriginBalances = (): void => { alert('validateOriginBalances') }
  const validateSituacion = (): void => { alert('validateSituacion') }
  const validatePatrimonio = (): void => { alert('validatePatrimonio') }
  const validatedContinuedOperations = (): void => { alert('validatedContinuedOperations') }

  const balanceProps = {
    i18n: i18nObj,
    originsBalances: originsBalances,
    auditConclusion: auditConclusion,
    formValues: formValuesBalance,
    validateOriginBalances: validateOriginBalances,
    validateSituacion: validateSituacion,
    validatePatrimonio: validatePatrimonio,
    validatedContinuedOperations: validatedContinuedOperations
  }

  return <ReportSpain
    handleSave={handleSave}
    handleAccept={handleAccept}
    handleCancel={handleCancel}
    balanceProps={balanceProps}
    i18n={i18nObj}
    legalForm={legalForm}
    formValues={formValues}
    banksReferences={banksReferences}
    opinionsCompany={opinionsCompany}
    opinionsSector={opinionsSector}
  ></ReportSpain>
}

export { ReportsSpainStory }

storiesOf('Components|Templates.ReportsSpain', module)
  .addDecorator(withThemeProvider)
  .add('ReportsSpain', () => <ReportsSpainStory />)
