interface I18n {
  'form:france:titulo': string
  'form:france:concepto:titulo': string
  'form:france:concepto:nregistro': string
  'form:france:concepto:nombre': string
  'form:france:concepto:direccion': string
  'form:france:concepto:localidad': string
  'form:france:concepto:provincia': string
  'form:france:concepto:codigopostal': string
  'form:france:concepto:telefono': string
  'form:france:concepto:fax': string
  'form:france:concepto:confidencialidad': string
  'form:france:concepto:alerta': string
  'form:france:concepto:consolidado': string
  'form:france:concepto:si': string
  'form:france:concepto:no': string
  'form:france:balance:titulo': string
  'form:france:balance:cifra': string
  'form:france:balance:origen': string
  'form:france:balance:fechascierre': string
  'form:france:balance:fechacierre1': string
  'form:france:balance:fechacierre2': string
  'form:france:balance:fechacierre3': string
  'form:france:balance:fechacierreheader1': string
  'form:france:balance:fechacierreheader2': string
  'form:france:balance:fechacierreheader3': string
  'form:france:activo:titulo': string
  'form:france:activo:subtitulo': string
  'form:france:activo:header1': string
  'form:france:activo:header2': string
  'form:france:activo:header3': string
  'form:france:activo:accion': string
  'form:france:activo:1': string
  'form:france:activo:1.1': string
  'form:france:activo:1.2': string
  'form:france:activo:1.3': string
  'form:france:activo:2': string
  'form:france:activo:2.1': string
  'form:france:activo:2.2': string
  'form:france:activo:2.3': string
  'form:france:activo:2.4': string
  'form:france:activo:3': string
  'form:france:activo:total': string

  'form:france:pasivo:titulo': string
  'form:france:pasivo:header1': string
  'form:france:pasivo:header2': string
  'form:france:pasivo:header3': string
  'form:france:pasivo:accion': string
  'form:france:pasivo:1': string
  'form:france:pasivo:1.1': string
  'form:france:pasivo:1.2': string
  'form:france:pasivo:1.3': string
  'form:france:pasivo:1.4': string
  'form:france:pasivo:1.5': string
  'form:france:pasivo:2': string
  'form:france:pasivo:3': string
  'form:france:pasivo:4': string
  'form:france:pasivo:4.1': string
  'form:france:pasivo:4.1.1': string
  'form:france:pasivo:4.1.2': string
  'form:france:pasivo:4.1.3': string
  'form:france:pasivo:4.1.4': string
  'form:france:pasivo:4.1.5': string
  'form:france:pasivo:4.2': string
  'form:france:pasivo:4.2.1': string
  'form:france:pasivo:4.2.2': string
  'form:france:pasivo:4.2.3': string
  'form:france:pasivo:4.2.4': string
  'form:france:pasivo:5': string
  'form:france:pasivo:total': string

  'form:france:cuentas:titulo': string
  'form:france:cuentas:header1': string
  'form:france:cuentas:header2': string
  'form:france:cuentas:header3': string
  'form:france:cuentas:accion': string
  'form:france:cuentas:1': string
  'form:france:cuentas:1.ventas': string
  'form:france:cuentas:1.prestaciones': string
  'form:france:cuentas:1.ingresos': string
  'form:france:cuentas:2': string
  'form:france:cuentas:2.ingresos': string
  'form:france:cuentas:2.gastos': string
  'form:france:cuentas:3': string
  'form:france:cuentas:4': string
  'form:france:cuentas:5': string
  'form:france:cuentas:6': string
  'form:france:cuentas:7': string
  'form:france:auditoria:conclusion': string
  'form:france:auditoria:comentario': string
  'form:france:guardar': string
  'form:france:aceptar': string
  'form:france:cancelar': string
}

type Tselect = Array<{
  value: string
  label: string
}>
export interface IReportFrance {
  readonly i18n: I18n
  selectOpts: {
    balanceOrigen: Tselect
    auditoriaConclusion: Tselect
  }
  readonly formValues: {
    conceptoRegistro: string
    conceptoNombre: string
    conceptoDireccion: string
    conceptoLocalidad: string
    conceptoProvincia: string
    conceptoCodigoPostal: string
    conceptoTelefono: string
    conceptoFax: string
    conceptoConfidencialidad: string
    conceptoAlerta: string
    conceptoConsolidado: string
    balanceOrigen: string
    balanceFechacierre1Dia: string
    balanceFechacierre1Mes: string
    balanceFechacierre1Ano: string
    balanceFechacierre2Dia: string
    balanceFechacierre2Mes: string
    balanceFechacierre2Ano: string
    balanceFechacierre3Dia: string
    balanceFechacierre3Mes: string
    activo_1_balance1: string
    activo_1_balance2: string
    activo_1_balance3: string
    activo_1_1_balance1: string
    activo_1_1_balance2: string
    activo_1_1_balance3: string
    activo_1_2_balance1: string
    activo_1_2_balance2: string
    activo_1_2_balance3: string
    activo_1_3_balance1: string
    activo_1_3_balance2: string
    activo_1_3_balance3: string
    activo_2_balance1: string
    activo_2_balance2: string
    activo_2_balance3: string
    activo_2_1_balance1: string
    activo_2_1_balance2: string
    activo_2_1_balance3: string
    activo_2_2_balance1: string
    activo_2_2_balance2: string
    activo_2_2_balance3: string
    activo_2_3_balance1: string
    activo_2_3_balance2: string
    activo_2_3_balance3: string
    activo_2_4_balance1: string
    activo_2_4_balance2: string
    activo_2_4_balance3: string
    activo_3_balance1: string
    activo_3_balance2: string
    activo_3_balance3: string
    activo_total_balance1: string
    activo_total_balance2: string
    activo_total_balance3: string

    pasivo_1_1_balance1: string
    pasivo_1_1_balance2: string
    pasivo_1_1_balance3: string
    pasivo_1_2_balance1: string
    pasivo_1_2_balance2: string
    pasivo_1_2_balance3: string
    pasivo_1_3_balance1: string
    pasivo_1_3_balance2: string
    pasivo_1_3_balance3: string
    pasivo_1_4_balance1: string
    pasivo_1_4_balance2: string
    pasivo_1_4_balance3: string
    pasivo_1_5_balance1: string
    pasivo_1_5_balance2: string
    pasivo_1_5_balance3: string
    pasivo_1_balance1: string
    pasivo_1_balance2: string
    pasivo_1_balance3: string
    pasivo_2_balance1: string
    pasivo_2_balance2: string
    pasivo_2_balance3: string
    pasivo_3_balance1: string
    pasivo_3_balance2: string
    pasivo_3_balance3: string
    pasivo_4_1_1_balance1: string
    pasivo_4_1_1_balance2: string
    pasivo_4_1_1_balance3: string
    pasivo_4_1_2_balance1: string
    pasivo_4_1_2_balance2: string
    pasivo_4_1_2_balance3: string
    pasivo_4_1_3_balance1: string
    pasivo_4_1_3_balance2: string
    pasivo_4_1_3_balance3: string
    pasivo_4_1_4_balance1: string
    pasivo_4_1_4_balance2: string
    pasivo_4_1_4_balance3: string
    pasivo_4_1_5_balance1: string
    pasivo_4_1_5_balance2: string
    pasivo_4_1_5_balance3: string
    pasivo_4_1_balance1: string
    pasivo_4_1_balance2: string
    pasivo_4_1_balance3: string
    pasivo_4_2_1_balance1: string
    pasivo_4_2_1_balance2: string
    pasivo_4_2_1_balance3: string
    pasivo_4_2_2_balance1: string
    pasivo_4_2_2_balance2: string
    pasivo_4_2_2_balance3: string
    pasivo_4_2_3_balance1: string
    pasivo_4_2_3_balance2: string
    pasivo_4_2_3_balance3: string
    pasivo_4_2_4_balance1: string
    pasivo_4_2_4_balance2: string
    pasivo_4_2_4_balance3: string
    pasivo_4_2_balance1: string
    pasivo_4_2_balance2: string
    pasivo_4_2_balance3: string
    pasivo_4_balance1: string
    pasivo_4_balance2: string
    pasivo_4_balance3: string
    pasivo_5_balance1: string
    pasivo_5_balance2: string
    pasivo_5_balance3: string
    pasivo_total_balance1: string
    pasivo_total_balance2: string
    pasivo_total_balance3: string

    cuentas_1_balance1: string
    cuentas_1_balance2: string
    cuentas_1_balance3: string
    cuentas_1_ingresos_balance1: string
    cuentas_1_ingresos_balance2: string
    cuentas_1_ingresos_balance3: string
    cuentas_1_prestaciones_balance1: string
    cuentas_1_prestaciones_balance2: string
    cuentas_1_prestaciones_balance3: string
    cuentas_1_ventas_balance1: string
    cuentas_1_ventas_balance2: string
    cuentas_1_ventas_balance3: string
    cuentas_2_balance1: string
    cuentas_2_balance2: string
    cuentas_2_balance3: string
    cuentas_2_gastos_balance1: string
    cuentas_2_gastos_balance2: string
    cuentas_2_gastos_balance3: string
    cuentas_2_ingresos_balance1: string
    cuentas_2_ingresos_balance2: string
    cuentas_2_ingresos_balance3: string
    cuentas_3_balance1: string
    cuentas_3_balance2: string
    cuentas_3_balance3: string
    cuentas_4_balance1: string
    cuentas_4_balance2: string
    cuentas_4_balance3: string
    cuentas_5_balance1: string
    cuentas_5_balance2: string
    cuentas_5_balance3: string
    cuentas_6_balance1: string
    cuentas_6_balance2: string
    cuentas_6_balance3: string
    cuentas_7_balance1: string
    cuentas_7_balance2: string
    cuentas_7_balance3: string
    cuentas_total_balance1: string
    cuentas_total_balance2: string
    cuentas_total_balance3: string
    auditoriaConclusion: string
    auditoriaComentario: string
  }
  readonly formLoading: boolean
  readonly formRecoverDataError: boolean
  readonly saveSuccess: boolean
  readonly saveLoading: boolean
  readonly acceptSuccess: boolean
  readonly acceptLoading: boolean
  readonly handleCancel: () => void
  readonly handleSave: (params) => void
  readonly handleAccept: (params) => void
  readonly validateActivo: (params) => void
  readonly validatePasivo: (params) => void
  readonly validateCuentas: (params) => void
}
