interface Ii18nDebtHistory {
  'DebtHistory:title': string
  'DebtHistory:calificacion': string
  'DebtHistory:nroEntidades': string
  'DebtHistory:duedaVigente': string
  'DebtHistory:deudaAtrasada': string
  'DebtHistory:duedaJudicial': string
  'DebtHistory:duedaCastigada': string
  'DebtHistory:duedaTotal': string
  'DebtHistory:diasAtraso': string
}

export interface IDebtHistoryRequestForm {
  regulatedPeriodo1: string
  regulatedPeriodo2: string
  regulatedPeriodo3: string
  regulatedPeriodo4: string
  regulatedPeriodo5: string
  regulatedPeriodo6: string
  regulatedCalificacion1: string
  regulatedCalificacion2: string
  regulatedCalificacion3: string
  regulatedCalificacion4: string
  regulatedCalificacion5: string
  regulatedCalificacion6: string
  regulatedNroEntidades1: string
  regulatedNroEntidades2: string
  regulatedNroEntidades3: string
  regulatedNroEntidades4: string
  regulatedNroEntidades5: string
  regulatedNroEntidades6: string
  regulatedDuedaTotal1: string
  regulatedDuedaTotal2: string
  regulatedDuedaTotal3: string
  regulatedDuedaTotal4: string
  regulatedDuedaTotal5: string
  regulatedDuedaTotal6: string
  regulatedDeudaAtrasada1: string
  regulatedDeudaAtrasada2: string
  regulatedDeudaAtrasada3: string
  regulatedDeudaAtrasada4: string
  regulatedDeudaAtrasada5: string
  regulatedDeudaAtrasada6: string
  regulatedDuedaJudicial1: string
  regulatedDuedaJudicial2: string
  regulatedDuedaJudicial3: string
  regulatedDuedaJudicial4: string
  regulatedDuedaJudicial5: string
  regulatedDuedaJudicial6: string
  regulatedDiasAtraso1: string
  regulatedDiasAtraso2: string
  regulatedDiasAtraso3: string
  regulatedDiasAtraso4: string
  regulatedDiasAtraso5: string
  regulatedDiasAtraso6: string
  regulatedDuedaCastigada1: string
  regulatedDuedaCastigada2: string
  regulatedDuedaCastigada3: string
  regulatedDuedaCastigada4: string
  regulatedDuedaCastigada5: string
  regulatedDuedaCastigada6: string
  regulatedDuedaVigente1: string
  regulatedDuedaVigente2: string
  regulatedDuedaVigente3: string
  regulatedDuedaVigente4: string
  regulatedDuedaVigente5: string
  regulatedDuedaVigente6: string
  nonRegulatedPeriodo1: string
  nonRegulatedPeriodo2: string
  nonRegulatedPeriodo3: string
  nonRegulatedPeriodo4: string
  nonRegulatedPeriodo5: string
  nonRegulatedPeriodo6: string
  nonRegulatedCalificacion1: string
  nonRegulatedCalificacion2: string
  nonRegulatedCalificacion3: string
  nonRegulatedCalificacion4: string
  nonRegulatedCalificacion5: string
  nonRegulatedCalificacion6: string
  nonRegulatedNroEntidades1: string
  nonRegulatedNroEntidades2: string
  nonRegulatedNroEntidades3: string
  nonRegulatedNroEntidades4: string
  nonRegulatedNroEntidades5: string
  nonRegulatedNroEntidades6: string
  nonRegulatedDuedaVigente1: string
  nonRegulatedDuedaVigente2: string
  nonRegulatedDuedaVigente3: string
  nonRegulatedDuedaVigente4: string
  nonRegulatedDuedaVigente5: string
  nonRegulatedDuedaVigente6: string
  nonRegulatedDeudaAtrasada1: string
  nonRegulatedDeudaAtrasada2: string
  nonRegulatedDeudaAtrasada3: string
  nonRegulatedDeudaAtrasada4: string
  nonRegulatedDeudaAtrasada5: string
  nonRegulatedDeudaAtrasada6: string
  nonRegulatedDuedaJudicial1: string
  nonRegulatedDuedaJudicial2: string
  nonRegulatedDuedaJudicial3: string
  nonRegulatedDuedaJudicial4: string
  nonRegulatedDuedaJudicial5: string
  nonRegulatedDuedaJudicial6: string
  nonRegulatedDiasAtraso1: string
  nonRegulatedDiasAtraso2: string
  nonRegulatedDiasAtraso3: string
  nonRegulatedDiasAtraso4: string
  nonRegulatedDiasAtraso5: string
  nonRegulatedDiasAtraso6: string
  nonRegulatedDuedaCastigada1: string
  nonRegulatedDuedaCastigada2: string
  nonRegulatedDuedaCastigada3: string
  nonRegulatedDuedaCastigada4: string
  nonRegulatedDuedaCastigada5: string
  nonRegulatedDuedaCastigada6: string
  nonRegulatedDuedaTotal1: string
  nonRegulatedDuedaTotal2: string
  nonRegulatedDuedaTotal3: string
  nonRegulatedDuedaTotal4: string
  nonRegulatedDuedaTotal5: string
  nonRegulatedDuedaTotal6: string
}

export interface IDebtHistory {
  i18n: Ii18nDebtHistory
  data: IDebtHistoryRequestForm
}
