
interface Ii18nBalance {
  'form:spain:balance:tabTitlers': string
  'form:spain:balance:label1rs': string
  'form:spain:balance:tabTitle2rs': string
  'form:spain:balance:closingDates': string
  'form:spain:balance:closingDates1': string
  'form:spain:balance:closingDates2': string
  'form:spain:balance:closingDates3': string
  'form:spain:balance:closingDatesDD': string
  'form:spain:balance:monthsBalances': string
  'form:spain:balance:month1': string
  'form:spain:balance:month2': string
  'form:spain:balance:month3': string
  'form:spain:balance:BalanceSheet': string
  'form:spain:balance:updated': string
  'form:spain:balance:balance1': string
  'form:spain:balance:balance2': string
  'form:spain:balance:balance3': string
  'form:spain:balance:non-current-assets': string
  'form:spain:balance:intangible': string
  'form:spain:balance:developing': string
  'form:spain:balance:concessions': string
  'form:spain:balance:patents': string
  'form:spain:balance:goodwill': string
  'form:spain:balance:computerApplications': string
  'form:spain:balance:investigation': string
  'form:spain:balance:anotherIntangible': string
  'form:spain:balance:inmobilizedMaterial': string
  'form:spain:balance:land': string
  'form:spain:balance:buildings': string
  'form:spain:balance:investmentsInGroup': string
  'form:spain:balance:financialInvestmentsLongTerm': string
  'form:spain:balance:heritageInstruments': string
  'form:spain:balance:thirdPartyCredits': string
  'form:spain:balance:representativeValuesDebt': string
  'form:spain:balance:derivatives': string
  'form:spain:balance:otherFinancialAssets': string
  'form:spain:balance:otherInvestments': string
  'form:spain:balance:taxAssetsDeferred': string
  'form:spain:balance:commercialDebtsNoCurrent': string
  'form:spain:balance:currentAssets': string
  'form:spain:balance:non-current-assets-help-for-sale': string
  'form:spain:balance:stocks': string
  'form:spain:balance:commercial': string
  'form:spain:balance:rawMaterials': string
  'form:spain:balance:productsInProgress': string
  'form:spain:balance:finishedProducts': string
  'form:spain:balance:byProductsWaste': string
  'form:spain:balance:advancedToSupplier': string
  'form:spain:balance:commercialDebtors': string
  'form:spain:balance:customersBySalesServicesBenefits': string
  'form:spain:balance:clientsOfGroupCompanies': string
  'form:spain:balance:sundryDebtors': string
  'form:spain:balance:staff': string
  'form:spain:balance:taxAssetsStreams': string
  'form:spain:balance:otherAdministrationCredits': string
  'form:spain:balance:shareholders': string
  'form:spain:balance:investmentsInGroupCompaniesAndAssociates': string
  'form:spain:balance:financialInvestmentsShortTerm': string
  'form:spain:balance:equityInstrument': string
  'form:spain:balance:companyCredits': string
  'form:spain:balance:representativeValuesOfDebt': string
  'form:spain:balance:derivatives2': string
  'form:spain:balance:otherFinancialAssets2': string
  'form:spain:balance:otherInvestments2': string
  'form:spain:balance:accrualsToShortTerm': string
  'form:spain:balance:cashOthersLiquidAssetsEquivalents': string
  'form:spain:balance:treasury': string
  'form:spain:balance:otherLiquidAssetsEquivalents': string
  'form:spain:balance:totalAssets': string
  'form:spain:balance:balanceSheet': string
  'form:spain:balance:equity': string
  'form:spain:balance:ownFunds': string
  'form:spain:balance:capital': string
  'form:spain:balance:capitalDeed': string
  'form:spain:balance:capitalNotRequired': string
  'form:spain:balance:issuePremium': string
  'form:spain:balance:bookings': string
  'form:spain:balance:actionsAndShares': string
  'form:spain:balance:resultOfExercisesPrevious': string
  'form:spain:balance:otherContributionsFromPartners': string
  'form:spain:balance:resultExercise': string
  'form:spain:balance:dividendOnAccount': string
  'form:spain:balance:otherInstrumentsHeritage': string
  'form:spain:balance:adjustmentsChangesOfValue': string
  'form:spain:balance:financialAssetsAvailableForSale': string
  'form:spain:balance:operationsCoverage': string
  'form:spain:balance:nonCurrentAssetsRelatedLiabilities': string
  'form:spain:balance:differencesOfConversion': string
  'form:spain:balance:others': string
  'form:spain:balance:grantsDonationsBequestReceived': string
  'form:spain:balance:nonCurrentLiabilities': string
  'form:spain:balance:longTermProvisions': string
  'form:spain:balance:provisionsRestructuring': string
  'form:spain:balance:longTermDebts': string
  'form:spain:balance:obligationsOtherSecuritiesNegotiable': string
  'form:spain:balance:debtsEntitiesCredit': string
  'form:spain:balance:creditorsFinancialLeasing': string
  'form:spain:balance:derivatives22': string
  'form:spain:balance:otherFinancialLiabilities': string
  'form:spain:balance:debtsCompaniesGroupAssociatedLongTerm': string
  'form:spain:balance:taxLiabilitiesDeferred': string
  'form:spain:balance:longAccrualsTerm': string
  'form:spain:balance:tradeCreditorsNoCurrents': string
  'form:spain:balance:debtsSpecialFeaturesLongTerm': string
  'form:spain:balance:currentLiabilities': string
  'form:spain:balance:liabilitiesRelatedNonCurrentAssetsHelpForSale': string
  'form:spain:balance:shortProvisionsTerm': string
  'form:spain:balance:shortTermDebts': string
  'form:spain:balance:obligationsOtherSecuritiesNegotiable2': string
  'form:spain:balance:debtsEntitiesOfCredit': string
  'form:spain:balance:creditorsFinancialLeasing2': string
  'form:spain:balance:derivatives3': string
  'form:spain:balance:otherFinancialLiabilities2': string
  'form:spain:balance:debtsCompaniesGroupAssociatedShortTerm': string
  'form:spain:balance:tradeCreditorsOtherAccountsPayable': string
  'form:spain:balance:suppliers': string
  'form:spain:balance:suppliersCompaniesGroupAssociates': string
  'form:spain:balance:variousCreditors': string
  'form:spain:balance:personnelSalariesStillPaid': string
  'form:spain:balance:taxLiabilitiesStream': string
  'form:spain:balance:otherDebtsPublicAdministrations': string
  'form:spain:balance:advancesFromClients': string
  'form:spain:balance:accrualsShortTerm': string
  'form:spain:balance:debtsSpecialFeaturesShortTerm': string
  'form:spain:balance:totalEquityLiabilitiesABC': string
  'form:spain:balance:incomeStatement': string
  'form:spain:balance:continuedOperations': string
  'form:spain:balance:netAmountFigureBusiness': string
  'form:spain:balance:sales': string
  'form:spain:balance:provisionOfServices': string
  'form:spain:balance:variationProductStocksCompleted': string
  'form:spain:balance:workCarriedOutCompanyAsset': string
  'form:spain:balance:procurement': string
  'form:spain:balance:otherIncomeFromExplotation': string
  'form:spain:balance:personnelExpenses': string
  'form:spain:balance:otherExpensesExplotation': string
  'form:spain:balance:amortizationImmobilized': string
  'form:spain:balance:imputationFixedAssetsGrants': string
  'form:spain:balance:excessProvisions': string
  'form:spain:balance:impairmentResultDisposalsImmobilized': string
  'form:spain:balance:impairmentLosses': string
  'form:spain:balance:resultsDisposalsOther': string
  'form:spain:balance:negativeDifferencesBusinessCombinations': string
  'form:spain:balance:otherResults': string
  'form:spain:balance:resultOperation': string
  'form:spain:balance:financialIncome': string
  'form:spain:balance:financialExpenses': string
  'form:spain:balance:variationValueReasonableInstruments': string
  'form:spain:balance:exchangeDifferences': string
  'form:spain:balance:impairmentResultDisposalsFinnacialInstruments': string
  'form:spain:balance:resultFinancial': string
  'form:spain:balance:resultBeforeTaxes': string
  'form:spain:balance:taxesOnBenefits': string
  'form:spain:balance:resultExerciseFromOperationsContinued': string
  'form:spain:balance:interruptedOperations': string
  'form:spain:balance:profitYearOperationsInterrupted': string
  'form:spain:balance:auditComments': string

}

export interface IBalance {
  readonly i18n: Ii18nBalance
  originsBalances: any
  auditConclusion: any
  readonly validateOriginBalances: (params) => void
  readonly validateSituacion: (params) => void
  readonly validatePatrimonio: (params) => void
  readonly validatedContinuedOperations: (params) => void
  readonly formValues: {
    originBalances: string
    balanceClosingDates1Day: string
    balanceClosingDates2Day: string
    balanceClosingDates3Day: string
    balanceClosingDates2Month: string
    balanceClosingDates2Year: string
    balanceClosingDates3Month: string
    balanceClosingDates3Year: string
    balanceClosingMonth1: string
    balanceClosingMonth2: string
    balanceClosingMonth3: string
    noncurrentassets1: string
    noncurrentassets2: string
    noncurrentassets3: string
    intangible1: string
    intangible2: string
    intangible3: string
    developing1: string
    developing2: string
    developing3: string
    concessions1: string
    concessions2: string
    concessions3: string
    patents1: string
    patents2: string
    patents3: string
    goodwill1: string
    goodwill2: string
    goodwill3: string
    computerApplications1: string
    computerApplications2: string
    computerApplications3: string
    investigation1: string
    investigation2: string
    investigation3: string
    anotherIntangible1: string
    anotherIntangible2: string
    anotherIntangible3: string
    inmobilizedMaterial1: string
    inmobilizedMaterial2: string
    inmobilizedMaterial3: string
    land1: string
    land2: string
    land3: string
    buildings1: string
    buildings2: string
    buildings3: string
    investmentsInGroup1: string
    investmentsInGroup2: string
    investmentsInGroup3: string
    financialInvestmentsLongTerm1: string
    financialInvestmentsLongTerm2: string
    financialInvestmentsLongTerm3: string
    heritageInstrument1: string
    heritageInstrument2: string
    heritageInstrument3: string
    thirdPartyCredits1: string
    thirdPartyCredits2: string
    thirdPartyCredits3: string
    representativeValuesDebt1: string
    representativeValuesDebt2: string
    representativeValuesDebt3: string
    derivatives1: string
    derivatives2: string
    derivatives3: string
    otherFinancialAssets1: string
    otherFinancialAssets2: string
    otherFinancialAssets3: string
    otherInvestments1: string
    otherInvestments2: string
    otherInvestments3: string
    taxAssetsDeferred1: string
    taxAssetsDeferred2: string
    taxAssetsDeferred3: string
    commercialDebtsNoCurrent1: string
    commercialDebtsNoCurrent2: string
    commercialDebtsNoCurrent3: string
    currentAssets1: string
    currentAssets2: string
    currentAssets3: string
    nonCurrentAssetsHelpForSale1: string
    nonCurrentAssetsHelpForSale2: string
    nonCurrentAssetsHelpForSale3: string
    stocks1: string
    stocks2: string
    stocks3: string
    commercial1: string
    commercial2: string
    commercial3: string
    rawMaterials1: string
    rawMaterials2: string
    rawMaterials3: string
    productsInProgress1: string
    productsInProgress2: string
    productsInProgress3: string
    finishedProducts1: string
    finishedProducts2: string
    finishedProducts3: string
    byProductsWaste1: string
    byProductsWaste2: string
    byProductsWaste3: string
    advancedToSupplier1: string
    advancedToSupplier2: string
    advancedToSupplier3: string
    commercialDebtors1: string
    commercialDebtors2: string
    commercialDebtors3: string
    customersBySalesServicesBenefits1: string
    customersBySalesServicesBenefits2: string
    customersBySalesServicesBenefits3: string
    clientsOfGroupCompanies1: string
    clientsOfGroupCompanies2: string
    clientsOfGroupCompanies3: string
    sundryDebtors1: string
    sundryDebtors2: string
    sundryDebtors3: string
    staff1: string
    staff2: string
    staff3: string
    taxAssetsStreams1: string
    taxAssetsStreams2: string
    taxAssetsStreams3: string
    otherAdministrationCredits1: string
    otherAdministrationCredits2: string
    otherAdministrationCredits3: string
    shareholders1: string
    shareholders2: string
    shareholders3: string
    investmentsInGroupCompaniesAndAssociates1: string
    investmentsInGroupCompaniesAndAssociates2: string
    investmentsInGroupCompaniesAndAssociates3: string
    financialInvestmentsShortTerm1: string
    financialInvestmentsShortTerm2: string
    financialInvestmentsShortTerm3: string
    equityInstrument1: string
    equityInstrument2: string
    equityInstrument3: string
    companyCredits1: string
    companyCredits2: string
    companyCredits3: string
    representativeValuesOfDebt1: string
    representativeValuesOfDebt2: string
    representativeValuesOfDebt3: string
    derivatives21: string
    derivatives22: string
    derivatives23: string
    otherFinancialAssets21: string
    otherFinancialAssets22: string
    otherFinancialAssets23: string
    otherInvestments21: string
    otherInvestments22: string
    otherInvestments23: string
    accrualsToShortTerm1: string
    accrualsToShortTerm2: string
    accrualsToShortTerm3: string
    cashOthersLiquidAssetsEquivalents1: string
    cashOthersLiquidAssetsEquivalents2: string
    cashOthersLiquidAssetsEquivalents3: string
    treasury1: string
    treasury2: string
    treasury3: string
    otherLiquidAssetsEquivalents1: string
    otherLiquidAssetsEquivalents2: string
    otherLiquidAssetsEquivalents3: string
    totalAssets1: string
    totalAssets2: string
    totalAssets3: string
    equity1: string
    equity2: string
    equity3: string
    ownFunds1: string
    ownFunds2: string
    ownFunds3: string
    capital1: string
    capital2: string
    capital3: string
    capitalDeed1: string
    capitalDeed2: string
    capitalDeed3: string
    capitalNotRequired1: string
    capitalNotRequired2: string
    capitalNotRequired3: string
    issuePremium1: string
    issuePremium2: string
    issuePremium3: string
    bookings1: string
    bookings2: string
    bookings3: string
    actionsAndShares1: string
    actionsAndShares2: string
    actionsAndShares3: string
    resultOfExercisesPrevious1: string
    resultOfExercisesPrevious2: string
    resultOfExercisesPrevious3: string
    otherContributionsFromPartners1: string
    otherContributionsFromPartners2: string
    otherContributionsFromPartners3: string
    resultExercise1: string
    resultExercise2: string
    resultExercise3: string
    dividendOnAccount1: string
    dividendOnAccount2: string
    dividendOnAccount3: string
    otherInstrumentsHeritage1: string
    otherInstrumentsHeritage2: string
    otherInstrumentsHeritage3: string
    adjustmentsChangesOfValue1: string
    adjustmentsChangesOfValue2: string
    adjustmentsChangesOfValue3: string
    financialAssetsAvailableForSale1: string
    financialAssetsAvailableForSale2: string
    financialAssetsAvailableForSale3: string
    operationsCoverage1: string
    operationsCoverage2: string
    operationsCoverage3: string
    nonCurrentAssetsRelatedLiabilities1: string
    nonCurrentAssetsRelatedLiabilities2: string
    nonCurrentAssetsRelatedLiabilities3: string
    differencesOfConversion1: string
    differencesOfConversion2: string
    differencesOfConversion3: string
    others1: string
    others2: string
    others3: string
    grantsDonationsBequestReceived1: string
    grantsDonationsBequestReceived2: string
    grantsDonationsBequestReceived3: string
    nonCurrentLiabilities1: string
    nonCurrentLiabilities2: string
    nonCurrentLiabilities3: string
    longTermProvisions1: string
    longTermProvisions2: string
    longTermProvisions3: string
    provisionsRestructuring1: string
    provisionsRestructuring2: string
    provisionsRestructuring3: string
    longTermDebts1: string
    longTermDebts2: string
    longTermDebts3: string
    obligationsOtherSecuritiesNegotiable1: string
    obligationsOtherSecuritiesNegotiable2: string
    obligationsOtherSecuritiesNegotiable3: string
    debtsEntitiesCredit1: string
    debtsEntitiesCredit2: string
    debtsEntitiesCredit3: string
    creditorsFinancialLeasing1: string
    creditorsFinancialLeasing2: string
    creditorsFinancialLeasing3: string
    derivatives221: string
    derivatives222: string
    derivatives223: string
    otherFinancialLiabilities1: string
    otherFinancialLiabilities2: string
    otherFinancialLiabilities3: string
    debtsCompaniesGroupAssociatedLongTerm1: string
    debtsCompaniesGroupAssociatedLongTerm2: string
    debtsCompaniesGroupAssociatedLongTerm3: string
    taxLiabilitiesDeferred1: string
    taxLiabilitiesDeferred2: string
    taxLiabilitiesDeferred3: string
    longAccrualsTerm1: string
    longAccrualsTerm2: string
    longAccrualsTerm3: string
    tradeCreditorsNoCurrents1: string
    tradeCreditorsNoCurrents2: string
    tradeCreditorsNoCurrents3: string
    debtsSpecialFeaturesLongTerm1: string
    debtsSpecialFeaturesLongTerm2: string
    debtsSpecialFeaturesLongTerm3: string
    currentLiabilities1: string
    currentLiabilities2: string
    currentLiabilities3: string
    liabilitiesRelatedNonCurrentAssetsHelpForSale1: string
    liabilitiesRelatedNonCurrentAssetsHelpForSale2: string
    liabilitiesRelatedNonCurrentAssetsHelpForSale3: string
    shortProvisionsTerm1: string
    shortProvisionsTerm2: string
    shortProvisionsTerm3: string
    shortTermDebts1: string
    shortTermDebts2: string
    shortTermDebts3: string
    obligationsOtherSecuritiesNegotiable21: string
    obligationsOtherSecuritiesNegotiable22: string
    obligationsOtherSecuritiesNegotiable23: string
    debtsEntitiesOfCredit1: string
    debtsEntitiesOfCredit2: string
    debtsEntitiesOfCredit3: string
    creditorsFinancialLeasing21: string
    creditorsFinancialLeasing22: string
    creditorsFinancialLeasing23: string
    derivatives31: string
    derivatives32: string
    derivatives33: string
    otherFinancialLiabilities21: string
    otherFinancialLiabilities22: string
    otherFinancialLiabilities23: string
    debtsCompaniesGroupAssociatedShortTerm1: string
    debtsCompaniesGroupAssociatedShortTerm2: string
    debtsCompaniesGroupAssociatedShortTerm3: string
    tradeCreditorsOtherAccountsPayable1: string
    tradeCreditorsOtherAccountsPayable2: string
    tradeCreditorsOtherAccountsPayable3: string
    suppliers1: string
    suppliers2: string
    suppliers3: string
    suppliersCompaniesGroupAssociates1: string
    suppliersCompaniesGroupAssociates2: string
    suppliersCompaniesGroupAssociates3: string
    variousCreditors1: string
    variousCreditors2: string
    variousCreditors3: string
    personnelSalariesStillPaid1: string
    personnelSalariesStillPaid2: string
    personnelSalariesStillPaid3: string
    taxLiabilitiesStream1: string
    taxLiabilitiesStream2: string
    taxLiabilitiesStream3: string
    otherDebtsPublicAdministrations1: string
    otherDebtsPublicAdministrations2: string
    otherDebtsPublicAdministrations3: string
    advancesFromClients1: string
    advancesFromClients2: string
    advancesFromClients3: string
    accrualsShortTerm1: string
    accrualsShortTerm2: string
    accrualsShortTerm3: string
    debtsSpecialFeaturesShortTerm1: string
    debtsSpecialFeaturesShortTerm2: string
    debtsSpecialFeaturesShortTerm3: string
    totalEquityLiabilitiesABC1: string
    totalEquityLiabilitiesABC2: string
    totalEquityLiabilitiesABC3: string
    netAmountFigureBusiness1: string
    netAmountFigureBusiness2: string
    netAmountFigureBusiness3: string
    sales1: string
    sales2: string
    sales3: string
    variationProductStocksCompleted1: string
    variationProductStocksCompleted2: string
    variationProductStocksCompleted3: string
    workCarriedOutCompanyAsset1: string
    workCarriedOutCompanyAsset2: string
    workCarriedOutCompanyAsset3: string
    procurement1: string
    procurement2: string
    procurement3: string
    otherIncomeFromExplotation1: string
    otherIncomeFromExplotation2: string
    otherIncomeFromExplotation3: string
    personnelExpenses1: string
    personnelExpenses2: string
    personnelExpenses3: string
    otherExpensesExplotation1: string
    otherExpensesExplotation2: string
    otherExpensesExplotation3: string
    amortizationImmobilized1: string
    amortizationImmobilized2: string
    amortizationImmobilized3: string
    imputationFixedAssetsGrants1: string
    imputationFixedAssetsGrants2: string
    imputationFixedAssetsGrants3: string
    excessProvisions1: string
    excessProvisions2: string
    excessProvisions3: string
    impairmentResultDisposalsImmobilized1: string
    impairmentResultDisposalsImmobilized2: string
    impairmentResultDisposalsImmobilized3: string
    impairmentLosses1: string
    impairmentLosses2: string
    impairmentLosses3: string
    resultsDisposalsOther1: string
    resultsDisposalsOther2: string
    resultsDisposalsOther3: string
    negativeDifferencesBusinessCombinations1: string
    negativeDifferencesBusinessCombinations2: string
    negativeDifferencesBusinessCombinations3: string
    otherResults1: string
    otherResults2: string
    otherResults3: string
    resultOperation1: string
    resultOperation2: string
    resultOperation3: string
    financialIncome1: string
    financialIncome2: string
    financialIncome3: string
    financialExpenses1: string
    financialExpenses2: string
    financialExpenses3: string
    variationValueReasonableInstruments1: string
    variationValueReasonableInstruments2: string
    variationValueReasonableInstruments3: string
    exchangeDifferences1: string
    exchangeDifferences2: string
    exchangeDifferences3: string
    impairmentResultDisposalsFinnacialInstruments1: string
    impairmentResultDisposalsFinnacialInstruments2: string
    impairmentResultDisposalsFinnacialInstruments3: string
    resultFinancial1: string
    resultFinancial2: string
    resultFinancial3: string
    taxesOnBenefits1: string
    taxesOnBenefits2: string
    taxesOnBenefits3: string
    resultExerciseFromOperationsContinued1: string
    resultExerciseFromOperationsContinued2: string
    resultExerciseFromOperationsContinued3: string
    profitYearOperationsInterrupted1: string
    profitYearOperationsInterrupted2: string
    profitYearOperationsInterrupted3: string
    auditConclusion: string
    auditComments: string
  }
}
interface Ii18n {
  'form:spain:h1title': string
  'form:spain:poll:h2title': string
  'form:spain:poll:label1rs': string
  'form:spain:poll:label2rs': string
  'form:spain:poll:label3rs': string
  'form:spain:poll:label4rs': string
  'form:spain:poll:label5rs': string
  'form:spain:poll:label6rs': string
  'form:spain:poll:label7rs': string
  'form:spain:poll:label8rs': string
  'form:spain:poll:label9rs': string
  'form:spain:poll:label10rs': string
  'form:spain:poll:label11rs': string
  'form:spain:poll:label12rs': string
  'form:spain:poll:label13rs': string
  'form:spain:poll:label14rs': string
  'form:spain:poll:label15rs': string
  'form:spain:poll:label16rs': string
  'form:spain:poll:label17rs': string
  'form:spain:poll:label18rs': string
  'form:spain:poll:label19rs': string
  'form:spain:poll:label20rs': string
  'form:spain:poll:label21rs': string
  'form:spain:poll:label22rs': string
  'form:spain:poll:label23rs': string
  'form:spain:poll:label24rs': string
  'form:spain:poll:label25rs': string
  'form:spain:poll:label26rs': string
  'form:spain:poll:label27rs': string
  'form:spain:poll:label28rs': string
  'form:spain:poll:label29rs': string
  'form:spain:poll:label30rs': string
  'form:spain:poll:label31rs': string
  'form:spain:poll:label32rs': string
  'form:spain:poll:label33rs': string
  'form:spain:poll:label34rs': string
  'form:spain:poll:buttonSave': string
  'form:spain:poll:buttonAccept': string
  'form:spain:poll:buttonCancel': string
}

export interface IReportsSpain {
  balanceProps: IBalance
  readonly i18n: Ii18n
  legalForm: any
  banksReferences: any
  opinionsCompany: any
  opinionsSector: any
  readonly handleSave: (params) => void
  readonly handleAccept: (params) => void
  readonly handleCancel: (params) => void
  readonly formValues: {
    cif: string
    name: string
    address: string
    province: string
    postalcode: string
    phone: string
    fax: string
    legalForm: string
    constitutionDateMM: string
    constitutionDateAAAA: string
    numberBranches: string
    branches: string
    employess: string
    socialCapital: string
    disbursedCapital: string
    cnae: string
    typeProducts: string
    estimatedSales: string
    banksOperates: string
    banksReference: string
    customerConcentration: string
    mainCustomers: string
    mainSuppliers: string
    competitors: string
    exportPercentage: string
    countriesExports: string
    shareHolders: string
    participated: string
    opinionCompany: string
    opinionSector: string
    comments: string
    confidentiality: string
    generateAlert: string
    consolidated: string
    // BALANCE
    originBalances: string
    balanceClosingDates1Day: string
    balanceClosingDates2Day: string
    balanceClosingDates3Day: string
    balanceClosingDates2Month: string
    balanceClosingDates2Year: string
    balanceClosingDates3Month: string
    balanceClosingDates3Year: string
    balanceClosingMonth1: string
    balanceClosingMonth2: string
    balanceClosingMonth3: string
    noncurrentassets1: string
    noncurrentassets2: string
    noncurrentassets3: string
    intangible1: string
    intangible2: string
    intangible3: string
    developing1: string
    developing2: string
    developing3: string
    concessions1: string
    concessions2: string
    concessions3: string
    patents1: string
    patents2: string
    patents3: string
    goodwill1: string
    goodwill2: string
    goodwill3: string
    computerApplications1: string
    computerApplications2: string
    computerApplications3: string
    investigation1: string
    investigation2: string
    investigation3: string
    anotherIntangible1: string
    anotherIntangible2: string
    anotherIntangible3: string
    inmobilizedMaterial1: string
    inmobilizedMaterial2: string
    inmobilizedMaterial3: string
    land1: string
    land2: string
    land3: string
    buildings1: string
    buildings2: string
    buildings3: string
    investmentsInGroup1: string
    investmentsInGroup2: string
    investmentsInGroup3: string
    financialInvestmentsLongTerm1: string
    financialInvestmentsLongTerm2: string
    financialInvestmentsLongTerm3: string
    heritageInstrument1: string
    heritageInstrument2: string
    heritageInstrument3: string
    thirdPartyCredits1: string
    thirdPartyCredits2: string
    thirdPartyCredits3: string
    representativeValuesDebt1: string
    representativeValuesDebt2: string
    representativeValuesDebt3: string
    derivatives1: string
    derivatives2: string
    derivatives3: string
    otherFinancialAssets1: string
    otherFinancialAssets2: string
    otherFinancialAssets3: string
    otherInvestments1: string
    otherInvestments2: string
    otherInvestments3: string
    taxAssetsDeferred1: string
    taxAssetsDeferred2: string
    taxAssetsDeferred3: string
    commercialDebtsNoCurrent1: string
    commercialDebtsNoCurrent2: string
    commercialDebtsNoCurrent3: string
    currentAssets1: string
    currentAssets2: string
    currentAssets3: string
    nonCurrentAssetsHelpForSale1: string
    nonCurrentAssetsHelpForSale2: string
    nonCurrentAssetsHelpForSale3: string
    stocks1: string
    stocks2: string
    stocks3: string
    commercial1: string
    commercial2: string
    commercial3: string
    rawMaterials1: string
    rawMaterials2: string
    rawMaterials3: string
    productsInProgress1: string
    productsInProgress2: string
    productsInProgress3: string
    finishedProducts1: string
    finishedProducts2: string
    finishedProducts3: string
    byProductsWaste1: string
    byProductsWaste2: string
    byProductsWaste3: string
    advancedToSupplier1: string
    advancedToSupplier2: string
    advancedToSupplier3: string
    commercialDebtors1: string
    commercialDebtors2: string
    commercialDebtors3: string
    customersBySalesServicesBenefits1: string
    customersBySalesServicesBenefits2: string
    customersBySalesServicesBenefits3: string
    clientsOfGroupCompanies1: string
    clientsOfGroupCompanies2: string
    clientsOfGroupCompanies3: string
    sundryDebtors1: string
    sundryDebtors2: string
    sundryDebtors3: string
    staff1: string
    staff2: string
    staff3: string
    taxAssetsStreams1: string
    taxAssetsStreams2: string
    taxAssetsStreams3: string
    otherAdministrationCredits1: string
    otherAdministrationCredits2: string
    otherAdministrationCredits3: string
    shareholders1: string
    shareholders2: string
    shareholders3: string
    investmentsInGroupCompaniesAndAssociates1: string
    investmentsInGroupCompaniesAndAssociates2: string
    investmentsInGroupCompaniesAndAssociates3: string
    financialInvestmentsShortTerm1: string
    financialInvestmentsShortTerm2: string
    financialInvestmentsShortTerm3: string
    equityInstrument1: string
    equityInstrument2: string
    equityInstrument3: string
    companyCredits1: string
    companyCredits2: string
    companyCredits3: string
    representativeValuesOfDebt1: string
    representativeValuesOfDebt2: string
    representativeValuesOfDebt3: string
    derivatives21: string
    derivatives22: string
    derivatives23: string
    otherFinancialAssets21: string
    otherFinancialAssets22: string
    otherFinancialAssets23: string
    otherInvestments21: string
    otherInvestments22: string
    otherInvestments23: string
    accrualsToShortTerm1: string
    accrualsToShortTerm2: string
    accrualsToShortTerm3: string
    cashOthersLiquidAssetsEquivalents1: string
    cashOthersLiquidAssetsEquivalents2: string
    cashOthersLiquidAssetsEquivalents3: string
    treasury1: string
    treasury2: string
    treasury3: string
    otherLiquidAssetsEquivalents1: string
    otherLiquidAssetsEquivalents2: string
    otherLiquidAssetsEquivalents3: string
    totalAssets1: string
    totalAssets2: string
    totalAssets3: string
    equity1: string
    equity2: string
    equity3: string
    ownFunds1: string
    ownFunds2: string
    ownFunds3: string
    capital1: string
    capital2: string
    capital3: string
    capitalDeed1: string
    capitalDeed2: string
    capitalDeed3: string
    capitalNotRequired1: string
    capitalNotRequired2: string
    capitalNotRequired3: string
    issuePremium1: string
    issuePremium2: string
    issuePremium3: string
    bookings1: string
    bookings2: string
    bookings3: string
    actionsAndShares1: string
    actionsAndShares2: string
    actionsAndShares3: string
    resultOfExercisesPrevious1: string
    resultOfExercisesPrevious2: string
    resultOfExercisesPrevious3: string
    otherContributionsFromPartners1: string
    otherContributionsFromPartners2: string
    otherContributionsFromPartners3: string
    resultExercise1: string
    resultExercise2: string
    resultExercise3: string
    dividendOnAccount1: string
    dividendOnAccount2: string
    dividendOnAccount3: string
    otherInstrumentsHeritage1: string
    otherInstrumentsHeritage2: string
    otherInstrumentsHeritage3: string
    adjustmentsChangesOfValue1: string
    adjustmentsChangesOfValue2: string
    adjustmentsChangesOfValue3: string
    financialAssetsAvailableForSale1: string
    financialAssetsAvailableForSale2: string
    financialAssetsAvailableForSale3: string
    operationsCoverage1: string
    operationsCoverage2: string
    operationsCoverage3: string
    nonCurrentAssetsRelatedLiabilities1: string
    nonCurrentAssetsRelatedLiabilities2: string
    nonCurrentAssetsRelatedLiabilities3: string
    differencesOfConversion1: string
    differencesOfConversion2: string
    differencesOfConversion3: string
    others1: string
    others2: string
    others3: string
    grantsDonationsBequestReceived1: string
    grantsDonationsBequestReceived2: string
    grantsDonationsBequestReceived3: string
    nonCurrentLiabilities1: string
    nonCurrentLiabilities2: string
    nonCurrentLiabilities3: string
    longTermProvisions1: string
    longTermProvisions2: string
    longTermProvisions3: string
    provisionsRestructuring1: string
    provisionsRestructuring2: string
    provisionsRestructuring3: string
    longTermDebts1: string
    longTermDebts2: string
    longTermDebts3: string
    obligationsOtherSecuritiesNegotiable1: string
    obligationsOtherSecuritiesNegotiable2: string
    obligationsOtherSecuritiesNegotiable3: string
    debtsEntitiesCredit1: string
    debtsEntitiesCredit2: string
    debtsEntitiesCredit3: string
    creditorsFinancialLeasing1: string
    creditorsFinancialLeasing2: string
    creditorsFinancialLeasing3: string
    derivatives221: string
    derivatives222: string
    derivatives223: string
    otherFinancialLiabilities1: string
    otherFinancialLiabilities2: string
    otherFinancialLiabilities3: string
    debtsCompaniesGroupAssociatedLongTerm1: string
    debtsCompaniesGroupAssociatedLongTerm2: string
    debtsCompaniesGroupAssociatedLongTerm3: string
    taxLiabilitiesDeferred1: string
    taxLiabilitiesDeferred2: string
    taxLiabilitiesDeferred3: string
    longAccrualsTerm1: string
    longAccrualsTerm2: string
    longAccrualsTerm3: string
    tradeCreditorsNoCurrents1: string
    tradeCreditorsNoCurrents2: string
    tradeCreditorsNoCurrents3: string
    debtsSpecialFeaturesLongTerm1: string
    debtsSpecialFeaturesLongTerm2: string
    debtsSpecialFeaturesLongTerm3: string
    currentLiabilities1: string
    currentLiabilities2: string
    currentLiabilities3: string
    liabilitiesRelatedNonCurrentAssetsHelpForSale1: string
    liabilitiesRelatedNonCurrentAssetsHelpForSale2: string
    liabilitiesRelatedNonCurrentAssetsHelpForSale3: string
    shortProvisionsTerm1: string
    shortProvisionsTerm2: string
    shortProvisionsTerm3: string
    shortTermDebts1: string
    shortTermDebts2: string
    shortTermDebts3: string
    obligationsOtherSecuritiesNegotiable21: string
    obligationsOtherSecuritiesNegotiable22: string
    obligationsOtherSecuritiesNegotiable23: string
    debtsEntitiesOfCredit1: string
    debtsEntitiesOfCredit2: string
    debtsEntitiesOfCredit3: string
    creditorsFinancialLeasing21: string
    creditorsFinancialLeasing22: string
    creditorsFinancialLeasing23: string
    derivatives31: string
    derivatives32: string
    derivatives33: string
    otherFinancialLiabilities21: string
    otherFinancialLiabilities22: string
    otherFinancialLiabilities23: string
    debtsCompaniesGroupAssociatedShortTerm1: string
    debtsCompaniesGroupAssociatedShortTerm2: string
    debtsCompaniesGroupAssociatedShortTerm3: string
    tradeCreditorsOtherAccountsPayable1: string
    tradeCreditorsOtherAccountsPayable2: string
    tradeCreditorsOtherAccountsPayable3: string
    suppliers1: string
    suppliers2: string
    suppliers3: string
    suppliersCompaniesGroupAssociates1: string
    suppliersCompaniesGroupAssociates2: string
    suppliersCompaniesGroupAssociates3: string
    variousCreditors1: string
    variousCreditors2: string
    variousCreditors3: string
    personnelSalariesStillPaid1: string
    personnelSalariesStillPaid2: string
    personnelSalariesStillPaid3: string
    taxLiabilitiesStream1: string
    taxLiabilitiesStream2: string
    taxLiabilitiesStream3: string
    otherDebtsPublicAdministrations1: string
    otherDebtsPublicAdministrations2: string
    otherDebtsPublicAdministrations3: string
    advancesFromClients1: string
    advancesFromClients2: string
    advancesFromClients3: string
    accrualsShortTerm1: string
    accrualsShortTerm2: string
    accrualsShortTerm3: string
    debtsSpecialFeaturesShortTerm1: string
    debtsSpecialFeaturesShortTerm2: string
    debtsSpecialFeaturesShortTerm3: string
    totalEquityLiabilitiesABC1: string
    totalEquityLiabilitiesABC2: string
    totalEquityLiabilitiesABC3: string
    netAmountFigureBusiness1: string
    netAmountFigureBusiness2: string
    netAmountFigureBusiness3: string
    sales1: string
    sales2: string
    sales3: string
    variationProductStocksCompleted1: string
    variationProductStocksCompleted2: string
    variationProductStocksCompleted3: string
    workCarriedOutCompanyAsset1: string
    workCarriedOutCompanyAsset2: string
    workCarriedOutCompanyAsset3: string
    procurement1: string
    procurement2: string
    procurement3: string
    otherIncomeFromExplotation1: string
    otherIncomeFromExplotation2: string
    otherIncomeFromExplotation3: string
    personnelExpenses1: string
    personnelExpenses2: string
    personnelExpenses3: string
    otherExpensesExplotation1: string
    otherExpensesExplotation2: string
    otherExpensesExplotation3: string
    amortizationImmobilized1: string
    amortizationImmobilized2: string
    amortizationImmobilized3: string
    imputationFixedAssetsGrants1: string
    imputationFixedAssetsGrants2: string
    imputationFixedAssetsGrants3: string
    excessProvisions1: string
    excessProvisions2: string
    excessProvisions3: string
    impairmentResultDisposalsImmobilized1: string
    impairmentResultDisposalsImmobilized2: string
    impairmentResultDisposalsImmobilized3: string
    impairmentLosses1: string
    impairmentLosses2: string
    impairmentLosses3: string
    resultsDisposalsOther1: string
    resultsDisposalsOther2: string
    resultsDisposalsOther3: string
    negativeDifferencesBusinessCombinations1: string
    negativeDifferencesBusinessCombinations2: string
    negativeDifferencesBusinessCombinations3: string
    otherResults1: string
    otherResults2: string
    otherResults3: string
    resultOperation1: string
    resultOperation2: string
    resultOperation3: string
    financialIncome1: string
    financialIncome2: string
    financialIncome3: string
    financialExpenses1: string
    financialExpenses2: string
    financialExpenses3: string
    variationValueReasonableInstruments1: string
    variationValueReasonableInstruments2: string
    variationValueReasonableInstruments3: string
    exchangeDifferences1: string
    exchangeDifferences2: string
    exchangeDifferences3: string
    impairmentResultDisposalsFinnacialInstruments1: string
    impairmentResultDisposalsFinnacialInstruments2: string
    impairmentResultDisposalsFinnacialInstruments3: string
    resultFinancial1: string
    resultFinancial2: string
    resultFinancial3: string
    taxesOnBenefits1: string
    taxesOnBenefits2: string
    taxesOnBenefits3: string
    resultExerciseFromOperationsContinued1: string
    resultExerciseFromOperationsContinued2: string
    resultExerciseFromOperationsContinued3: string
    profitYearOperationsInterrupted1: string
    profitYearOperationsInterrupted2: string
    profitYearOperationsInterrupted3: string
    auditConclusion: string
    auditComments: string

  }
}
