interface Ii18nRatiosInformation {
  'RatiosInformation:title': string
  'RatiosInformation:labelTbEjercicio1': string
  'RatiosInformation:labelTbEjercicio2': string
  'RatiosInformation:labelTbEjercicio3': string
  'RatiosInformation:detailTbAccNoExx': string
  'RatiosInformation:detailTbInmoNeto': string
  'RatiosInformation:detailTbGastoEstabl': string
  'RatiosInformation:detailTbInvDesarrollo': string
  'RatiosInformation:detailTbPatentes': string
  'RatiosInformation:detailTbFondoComertio': string
  'RatiosInformation:detailTbOtroInmoInma': string
  'RatiosInformation:detailTbBienesArren': string
  'RatiosInformation:detailTbAmorInmoMat': string
  'RatiosInformation:detailTbTotInmoInmat': string
  'RatiosInformation:detailTbTerrenos': string
  'RatiosInformation:detailTbConstrucciones': string
  'RatiosInformation:detailTbTerrConstrucciones': string
  'RatiosInformation:detailTbMaqHerra': string
  'RatiosInformation:detailTbInstTecnicas': string
  'RatiosInformation:detailTbMoviliario': string
  'RatiosInformation:detailTbInmoEnCurso': string
  'RatiosInformation:detailTbOtroInmoMaterial': string
  'RatiosInformation:detailTbInmoNoOpe': string
  'RatiosInformation:detailTbTotInmoMat': string
  'RatiosInformation:detailTbEmpGrupo': string
  'RatiosInformation:detailTbEmpAsociada': string
  'RatiosInformation:detailTbAcciones': string
  'RatiosInformation:detailTbDepositos': string
  'RatiosInformation:detailTbOtrosDepositos': string
  'RatiosInformation:detailTbCreditoLargoPlazo': string
  'RatiosInformation:detailTbCreditoAsociados': string
  'RatiosInformation:detailTbCreditosGrupo': string
  'RatiosInformation:detailTbOtroInmoFinanciero': string
  'RatiosInformation:detailTbInmoOtros': string
  'RatiosInformation:detailTbTotInmoFinanciero': string
  'RatiosInformation:detailTbAmortizacion': string
  'RatiosInformation:detailTbOtroInmoLargoPlazo': string
  'RatiosInformation:detailTbGastosDistribuir': string
  'RatiosInformation:detailTbActivoCirculante': string
  'RatiosInformation:detailTbExistenciasNetas': string
  'RatiosInformation:detailTbMateriasPrimas': string
  'RatiosInformation:detailTbProductoCurso': string
  'RatiosInformation:detailTbProductoTerminado': string
  'RatiosInformation:detailTbMercaderias': string
  'RatiosInformation:detailTbExistencias': string
  'RatiosInformation:detailTbContratos': string
  'RatiosInformation:detailTbInmiuebles': string
  'RatiosInformation:detailTbAnticipos': string
  'RatiosInformation:detailTbProvExistencias': string
  'RatiosInformation:detailTbRealizable': string
  'RatiosInformation:detailTbClientes': string
  'RatiosInformation:detailTbOtrosDeudores': string
  'RatiosInformation:detailTbDeudoresEspeciales': string
  'RatiosInformation:detailTbProvTrafico': string
  'RatiosInformation:detailTbDeudasGrupo': string
  'RatiosInformation:detailTbDeudasAsociados': string
  'RatiosInformation:detailTbOtrosActCirculantes': string
  'RatiosInformation:detailTbAdmiPubnlicas': string
  'RatiosInformation:detailTbAcumulaciones': string
  'RatiosInformation:detailTbCapitalDesem': string
  'RatiosInformation:detailTbGastosAnticipados': string
  'RatiosInformation:detailTbInvFinancierasTemp': string
  'RatiosInformation:detailTbOtrasInvFinancierasCPlazo': string
  'RatiosInformation:detailTbOtrosCreditos': string
  'RatiosInformation:detailTbCarteraCortoPlazo': string
  'RatiosInformation:detailTbParticipaciones': string
  'RatiosInformation:detailTbAccionesPropias': string
  'RatiosInformation:detailTbTesoreria': string
  'RatiosInformation:detailTbCaja': string
  'RatiosInformation:detailTbBancos': string
  'RatiosInformation:detailTbTotActiv': string
  'RatiosInformation:detailTbFondosPropios': string
  'RatiosInformation:detailTbTotCapital': string
  'RatiosInformation:detailTbCapital': string
  'RatiosInformation:detailTbAccionesPref': string
  'RatiosInformation:detailTbCapitalEmitido': string
  'RatiosInformation:detailTbCapitalDesembolsado': string
  'RatiosInformation:detailTbPrimaEmision': string
  'RatiosInformation:detailTbTotReservas': string
  'RatiosInformation:detailTbReservas': string
  'RatiosInformation:detailTbExceCapital': string
  'RatiosInformation:detailTbReservaLegal': string
  'RatiosInformation:detailTbReservaNoDisp': string
  'RatiosInformation:detailTbReservaVolunt': string
  'RatiosInformation:detailTbReservaAccionesPropias': string
  'RatiosInformation:detailTbReservasEstatutarias': string
  'RatiosInformation:detailTbReservasDisponibles': string
  'RatiosInformation:detailTbOtrasReservas': string
  'RatiosInformation:detailTbReservasRevalorizacion': string
  'RatiosInformation:detailTbAcumulada': string
  'RatiosInformation:detailTbBeneficioEjerAnt': string
  'RatiosInformation:detailTbPerdidasEjerAnt': string
  'RatiosInformation:detailTbNoDistribuido': string
  'RatiosInformation:detailTbBeneficiosNoDistribuido': string
  'RatiosInformation:detailTbPerdidasGanancias': string
  'RatiosInformation:detailTbPerdidasEjer': string
  'RatiosInformation:detailTbBeneficiosEjer': string
  'RatiosInformation:detailTbDividendoEjer': string
  'RatiosInformation:detailTbProvReservas': string
  'RatiosInformation:detailTbInteresMinoritario': string
  'RatiosInformation:detailTbIngresosVariosEjer': string
  'RatiosInformation:detailTbSubvencionesCapital': string
  'RatiosInformation:detailTbRiesgosGastos': string
  'RatiosInformation:detailTbProvRiesgosGastos': string
  'RatiosInformation:detailTbProvPensiones': string
  'RatiosInformation:detailTbProvImpuesto': string
  'RatiosInformation:detailTbOtrasProv': string
  'RatiosInformation:detailTbProvCompras': string
  'RatiosInformation:detailTbDeprecInmo': string
  'RatiosInformation:detailTbDeprecIntangible': string
  'RatiosInformation:detailTbProvDeprecExistencias': string
  'RatiosInformation:detailTbCreditosIncobrables': string
  'RatiosInformation:detailTbDeprecInmovilizado': string
  'RatiosInformation:detailTbCuentaRegularizacion': string
  'RatiosInformation:detailTbCuentaCompensacion': string
  'RatiosInformation:detailTbAcreedLargoPlazo': string
  'RatiosInformation:detailTbDeudasComerciales': string
  'RatiosInformation:detailTbAcreedoresComerciales': string
  'RatiosInformation:detailTbOtrosAcreedores': string
  'RatiosInformation:detailTbDeudasRepresentadas': string
  'RatiosInformation:detailTbVentasPlazo': string
  'RatiosInformation:detailTbDeudasEmpGrupo': string
  'RatiosInformation:detailTbAcreedoresGrupo': string
  'RatiosInformation:detailTbAcreedoresAsociados': string
  'RatiosInformation:detailTbDeudasFinancieras': string
  'RatiosInformation:detailTbObligacionesConvertibles': string
  'RatiosInformation:detailTbObligacionesSimilares': string
  'RatiosInformation:detailTbHipotecasPrestamos': string
  'RatiosInformation:detailTbOtrasDeudasNoComerciales': string
  'RatiosInformation:detailTbImpuestosSeguridadSocial': string
  'RatiosInformation:detailTbDeudasPensiones': string
  'RatiosInformation:detailTbCobrosAnticipados': string
  'RatiosInformation:detailTbAcreedoresCortoPlazo': string
  'RatiosInformation:detailTbCuentasPagar': string
  'RatiosInformation:detailTbProveedorCP': string
  'RatiosInformation:detailTbOtrosAcreedoresCom': string
  'RatiosInformation:detailTbDeudasRepreAPagar': string
  'RatiosInformation:detailTbVentaPlazos': string
  'RatiosInformation:detailTbDeudasEmpGrupoAsoc': string
  'RatiosInformation:detailTbAcreedoresEGrupo': string
  'RatiosInformation:detailTbPrestamosAdmin': string
  'RatiosInformation:detailTbAcreedoresEAsoc': string
  'RatiosInformation:detailTbDeudasFinancierasLower': string
  'RatiosInformation:detailTbPertamosBancarios': string
  'RatiosInformation:detailTbParteCorrienteDeuda': string
  'RatiosInformation:detailTbOtrosPrestamos': string
  'RatiosInformation:detailTbDeudasValoresNegociables': string
  'RatiosInformation:detailTbOtrosPrestamosCP': string
  'RatiosInformation:detailTbCuentasGenerales': string
  'RatiosInformation:detailTbOtrasDeudas': string
  'RatiosInformation:detailTbDeudasInmovilizado': string
  'RatiosInformation:detailTbImpuestosSegSocial': string
  'RatiosInformation:detailTbImpuestos': string
  'RatiosInformation:detailTbSalariosSegSocial': string
  'RatiosInformation:detailTbDividendo': string
  'RatiosInformation:detailTbDeclaradoAnticipado': string
  'RatiosInformation:detailTbCobroAnticipado': string
  'RatiosInformation:detailTbAcreedoresEspeciales': string
  'RatiosInformation:detailTbIngresosDiferidos': string
  'RatiosInformation:detailTbTotAcreedores': string
  'RatiosInformation:detailTbTotPasivo': string
}

export interface IRatiosActivoRequestForm {
  accNoExi1: string
  accNoExi2: string
  accNoExi3: string
  inmoNeto1: string
  inmoNeto2: string
  inmoNeto3: string
  gastoEstabl1: string
  gastoEstabl2: string
  gastoEstabl3: string
  invDesarrollo1: string
  invDesarrollo2: string
  invDesarrollo3: string
  patentes1: string
  patentes2: string
  patentes3: string
  fondoComertio1: string
  fondoComertio2: string
  fondoComertio3: string
  otroInmoInma1: string
  otroInmoInma2: string
  otroInmoInma3: string
  bienesArren1: string
  bienesArren2: string
  bienesArren3: string
  amorInmoMat1: string
  amorInmoMat2: string
  amorInmoMat3: string
  totInmoInmat1: string
  totInmoInmat2: string
  totInmoInmat3: string
  terrenos1: string
  terrenos2: string
  terrenos3: string
  construcciones1: string
  construcciones2: string
  construcciones3: string
  terrConstrucciones1: string
  terrConstrucciones2: string
  terrConstrucciones3: string
  maqHerra1: string
  maqHerra2: string
  maqHerra3: string
  instTecnicas1: string
  instTecnicas2: string
  instTecnicas3: string
  moviliario1: string
  moviliario2: string
  moviliario3: string
  inmoEnCurso1: string
  inmoEnCurso2: string
  inmoEnCurso3: string
  otroInmoMaterial1: string
  otroInmoMaterial2: string
  otroInmoMaterial3: string
  inmoNoOpe1: string
  inmoNoOpe2: string
  inmoNoOpe3: string
  totInmoMat1: string
  totInmoMat2: string
  totInmoMat3: string
  empGrupo1: string
  empGrupo2: string
  empGrupo3: string
  empAsociada1: string
  empAsociada2: string
  empAsociada3: string
  acciones1: string
  acciones2: string
  acciones3: string
  depositos1: string
  depositos2: string
  depositos3: string
  otrosDepositos1: string
  otrosDepositos2: string
  otrosDepositos3: string
  creditoLargoPlazo1: string
  creditoLargoPlazo2: string
  creditoLargoPlazo3: string
  creditoAsociados1: string
  creditoAsociados2: string
  creditoAsociados3: string
  creditosGrupo1: string
  creditosGrupo2: string
  creditosGrupo3: string
  otroInmoFinanciero1: string
  otroInmoFinanciero2: string
  otroInmoFinanciero3: string
  inmoOtros1: string
  inmoOtros2: string
  inmoOtros3: string
  totInmoFinanciero1: string
  totInmoFinanciero2: string
  totInmoFinanciero3: string
  amortizacion1: string
  amortizacion2: string
  amortizacion3: string
  otroInmoLargoPlazo1: string
  otroInmoLargoPlazo2: string
  otroInmoLargoPlazo3: string
  gastosDistribuir1: string
  gastosDistribuir2: string
  gastosDistribuir3: string
  ratioActivoCirculante1: string
  ratioActivoCirculante2: string
  ratioActivoCirculante3: string
  existenciasNetas1: string
  existenciasNetas2: string
  existenciasNetas3: string
  materiasPrimas1: string
  materiasPrimas2: string
  materiasPrimas3: string
  productoCurso1: string
  productoCurso2: string
  productoCurso3: string
  productoTerminado1: string
  productoTerminado2: string
  productoTerminado3: string
  mercaderias1: string
  mercaderias2: string
  mercaderias3: string
  existencias1: string
  existencias2: string
  existencias3: string
  contratos1: string
  contratos2: string
  contratos3: string
  inmiuebles1: string
  inmiuebles2: string
  inmiuebles3: string
  anticipos1: string
  anticipos2: string
  anticipos3: string
  provExistencias1: string
  provExistencias2: string
  provExistencias3: string
  realizable1: string
  realizable2: string
  realizable3: string
  clientes1: string
  clientes2: string
  clientes3: string
  otrosDeudores1: string
  otrosDeudores2: string
  otrosDeudores3: string
  deudoresEspeciales1: string
  deudoresEspeciales2: string
  deudoresEspeciales3: string
  provTrafico1: string
  provTrafico2: string
  provTrafico3: string
  deudasGrupo1: string
  deudasGrupo2: string
  deudasGrupo3: string
  deudasAsociados1: string
  deudasAsociados2: string
  deudasAsociados3: string
  otrosActCirculantes1: string
  otrosActCirculantes2: string
  otrosActCirculantes3: string
  admiPubnlicas1: string
  admiPubnlicas2: string
  admiPubnlicas3: string
  acumulaciones1: string
  acumulaciones2: string
  acumulaciones3: string
  capitalDesem1: string
  capitalDesem2: string
  capitalDesem3: string
  gastosAnticipados1: string
  gastosAnticipados2: string
  gastosAnticipados3: string
  invFinancierasTemp1: string
  invFinancierasTemp2: string
  invFinancierasTemp3: string
  otrasInvFinancierasCPlazo1: string
  otrasInvFinancierasCPlazo2: string
  otrasInvFinancierasCPlazo3: string
  otrosCreditos1: string
  otrosCreditos2: string
  otrosCreditos3: string
  carteraCortoPlazo1: string
  carteraCortoPlazo2: string
  carteraCortoPlazo3: string
  participaciones1: string
  participaciones2: string
  participaciones3: string
  accionesPropias1: string
  accionesPropias2: string
  accionesPropias3: string
  tesoreria1: string
  tesoreria2: string
  tesoreria3: string
  caja1: string
  caja2: string
  caja3: string
  bancos1: string
  bancos2: string
  bancos3: string
  totActiv1: string
  totActiv2: string
  totActiv3: string
}

export interface IRatiosPasivoRequestForm {
  ratiosFondosPropios1: string
  ratiosFondosPropios2: string
  ratiosFondosPropios3: string
  totCapital1: string
  totCapital2: string
  totCapital3: string
  ratiosCapital1: string
  ratiosCapital2: string
  ratiosCapital3: string
  accionesPref1: string
  accionesPref2: string
  accionesPref3: string
  capitalEmitido1: string
  capitalEmitido2: string
  capitalEmitido3: string
  capitalDesembolsado1: string
  capitalDesembolsado2: string
  capitalDesembolsado3: string
  primaEmision1: string
  primaEmision2: string
  primaEmision3: string
  totReservas1: string
  totReservas2: string
  totReservas3: string
  reservas1: string
  reservas2: string
  reservas3: string
  exceCapital1: string
  exceCapital2: string
  exceCapital3: string
  reservaLegal1: string
  reservaLegal2: string
  reservaLegal3: string
  reservaNoDisp1: string
  reservaNoDisp2: string
  reservaNoDisp3: string
  reservaVolunt1: string
  reservaVolunt2: string
  reservaVolunt3: string
  reservaAccionesPropias1: string
  reservaAccionesPropias2: string
  reservaAccionesPropias3: string
  reservasEstatutarias1: string
  reservasEstatutarias2: string
  reservasEstatutarias3: string
  reservasDisponibles1: string
  reservasDisponibles2: string
  reservasDisponibles3: string
  otrasReservas1: string
  otrasReservas2: string
  otrasReservas3: string
  reservasRevalorizacion1: string
  reservasRevalorizacion2: string
  reservasRevalorizacion3: string
  acumulada1: string
  acumulada2: string
  acumulada3: string
  beneficioEjerAnt1: string
  beneficioEjerAnt2: string
  beneficioEjerAnt3: string
  perdidasEjerAnt1: string
  perdidasEjerAnt2: string
  perdidasEjerAnt3: string
  noDistribuido1: string
  noDistribuido2: string
  noDistribuido3: string
  beneficiosNoDistribuido1: string
  beneficiosNoDistribuido2: string
  beneficiosNoDistribuido3: string
  perdidasGanancias1: string
  perdidasGanancias2: string
  perdidasGanancias3: string
  perdidasEjer1: string
  perdidasEjer2: string
  perdidasEjer3: string
  beneficiosEjer1: string
  beneficiosEjer2: string
  beneficiosEjer3: string
  dividendoEjer1: string
  dividendoEjer2: string
  dividendoEjer3: string
  provReservas1: string
  provReservas2: string
  provReservas3: string
  interesMinoritario1: string
  interesMinoritario2: string
  interesMinoritario3: string
  ingresosVariosEjer1: string
  ingresosVariosEjer2: string
  ingresosVariosEjer3: string
  subvencionesCapital1: string
  subvencionesCapital2: string
  subvencionesCapital3: string
  riesgosGastos1: string
  riesgosGastos2: string
  riesgosGastos3: string
  provRiesgosGastos1: string
  provRiesgosGastos2: string
  provRiesgosGastos3: string
  provPensiones1: string
  provPensiones2: string
  provPensiones3: string
  provImpuesto1: string
  provImpuesto2: string
  provImpuesto3: string
  otrasProv1: string
  otrasProv2: string
  otrasProv3: string
  provCompras1: string
  provCompras2: string
  provCompras3: string
  deprecInmo1: string
  deprecInmo2: string
  deprecInmo3: string
  deprecIntangible1: string
  deprecIntangible2: string
  deprecIntangible3: string
  provDeprecExistencias1: string
  provDeprecExistencias2: string
  provDeprecExistencias3: string
  creditosIncobrables1: string
  creditosIncobrables2: string
  creditosIncobrables3: string
  deprecInmovilizado1: string
  deprecInmovilizado2: string
  deprecInmovilizado3: string
  cuentaRegularizacion1: string
  cuentaRegularizacion2: string
  cuentaRegularizacion3: string
  cuentaCompensacion1: string
  cuentaCompensacion2: string
  cuentaCompensacion3: string
  acreedLargoPlazo1: string
  acreedLargoPlazo2: string
  acreedLargoPlazo3: string
  deudasComerciales1: string
  deudasComerciales2: string
  deudasComerciales3: string
  acreedoresComerciales1: string
  acreedoresComerciales2: string
  acreedoresComerciales3: string
  otrosAcreedores1: string
  otrosAcreedores2: string
  otrosAcreedores3: string
  deudasRepresentadas1: string
  deudasRepresentadas2: string
  deudasRepresentadas3: string
  ventasPlazo1: string
  ventasPlazo2: string
  ventasPlazo3: string
  deudasEmpGrupo1: string
  deudasEmpGrupo2: string
  deudasEmpGrupo3: string
  acreedoresGrupo1: string
  acreedoresGrupo2: string
  acreedoresGrupo3: string
  acreedoresAsociados1: string
  acreedoresAsociados2: string
  acreedoresAsociados3: string
  deudasFinancieras1: string
  deudasFinancieras2: string
  deudasFinancieras3: string
  obligacionesConvertibles1: string
  obligacionesConvertibles2: string
  obligacionesConvertibles3: string
  obligacionesSimilares1: string
  obligacionesSimilares2: string
  obligacionesSimilares3: string
  hipotecasPrestamos1: string
  hipotecasPrestamos2: string
  hipotecasPrestamos3: string
  otrasDeudasNoComer1: string
  otrasDeudasNoComer2: string
  otrasDeudasNoComer3: string
  impuestosSeguridadSocial1: string
  impuestosSeguridadSocial2: string
  impuestosSeguridadSocial3: string
  deudasPensiones1: string
  deudasPensiones2: string
  deudasPensiones3: string
  cobrosAnticipados1: string
  cobrosAnticipados2: string
  cobrosAnticipados3: string
  acreedoresCortoPlazo1: string
  acreedoresCortoPlazo2: string
  acreedoresCortoPlazo3: string
  deudasComercialesBis1: string
  deudasComercialesBis2: string
  deudasComercialesBis3: string
  cuentasPagar1: string
  cuentasPagar2: string
  cuentasPagar3: string
  proveedorCP1: string
  proveedorCP2: string
  proveedorCP3: string
  otrosAcreedoresCom1: string
  otrosAcreedoresCom2: string
  otrosAcreedoresCom3: string
  deudasRepreAPagar1: string
  deudasRepreAPagar2: string
  deudasRepreAPagar3: string
  ventaPlazos1: string
  ventaPlazos2: string
  ventaPlazos3: string
  deudasEmpGrupoAsoc1: string
  deudasEmpGrupoAsoc2: string
  deudasEmpGrupoAsoc3: string
  acreedoresEGrupo1: string
  acreedoresEGrupo2: string
  acreedoresEGrupo3: string
  prestamosAdmin1: string
  prestamosAdmin2: string
  prestamosAdmin3: string
  acreedoresEAsoc1: string
  acreedoresEAsoc2: string
  acreedoresEAsoc3: string
  deudasFinancierasBis1: string
  deudasFinancierasBis2: string
  deudasFinancierasBis3: string
  deudasFinancierasLower1: string
  deudasFinancierasLower2: string
  deudasFinancierasLower3: string
  pertamosBancarios1: string
  pertamosBancarios2: string
  pertamosBancarios3: string
  parteCorrienteDeuda1: string
  parteCorrienteDeuda2: string
  parteCorrienteDeuda3: string
  otrosPrestamos1: string
  otrosPrestamos2: string
  otrosPrestamos3: string
  deudasValoresNegociables1: string
  deudasValoresNegociables2: string
  deudasValoresNegociables3: string
  otrosPrestamosCP1: string
  otrosPrestamosCP2: string
  otrosPrestamosCP3: string
  otrasDeudasNoComerciales1: string
  otrasDeudasNoComerciales2: string
  otrasDeudasNoComerciales3: string
  cuentasGenerales1: string
  cuentasGenerales2: string
  cuentasGenerales3: string
  otrasDeudas1: string
  otrasDeudas2: string
  otrasDeudas3: string
  deudasInmovilizado1: string
  deudasInmovilizado2: string
  deudasInmovilizado3: string
  impuestosSegSocial1: string
  impuestosSegSocial2: string
  impuestosSegSocial3: string
  impuestos1: string
  impuestos2: string
  impuestos3: string
  salariosSegSocial1: string
  salariosSegSocial2: string
  salariosSegSocial3: string
  dividendo1: string
  dividendo2: string
  dividendo3: string
  declaradoAnticipado1: string
  declaradoAnticipado2: string
  declaradoAnticipado3: string
  cobroAnticipado1: string
  cobroAnticipado2: string
  cobroAnticipado3: string
  acreedoresEspeciales1: string
  acreedoresEspeciales2: string
  acreedoresEspeciales3: string
  ingresosDiferidos1: string
  ingresosDiferidos2: string
  ingresosDiferidos3: string
  totAcreedores1: string
  totAcreedores2: string
  totAcreedores3: string
  totPasivo1: string
  totPasivo2: string
  totPasivo3: string
}

export interface IRatiosInformationRequestForm {
  activo: IRatiosActivoRequestForm
  pasivo: IRatiosPasivoRequestForm
}

export interface IRatiosInformation {
  i18n: Ii18nRatiosInformation
  data: IRatiosInformationRequestForm
}
