export interface Ii18nCuentasResultadosBis {
  'CuentaResultadosBis:title': string
  'CuentaResultadosBis:labelTbEjercicio1': string
  'CuentaResultadosBis:labelTbEjercicio2': string
  'CuentaResultadosBis:labelTbEjercicio3': string
  'CuentaResultadosBis:detailTbVentasMercancias': string
  'CuentaResultadosBis:detailTbVentasBienes': string
  'CuentaResultadosBis:detailTbPrestacionServicio': string
  'CuentaResultadosBis:detailTbPrestacionServicio_1': string
  'CuentaResultadosBis:detailTbPrestacionServicio_2': string
  'CuentaResultadosBis:detailTbPrestacionServicio_3': string
  'CuentaResultadosBis:detailTbPrestacionServicio_4': string
  'CuentaResultadosBis:detailTbPrestacionServicio_5': string
  'CuentaResultadosBis:detailTbPrestacionServicio_6': string
  'CuentaResultadosBis:detailTbTotalIngresos': string
  'CuentaResultadosBis:detailTbTotalIngresos_1': string
  'CuentaResultadosBis:detailTbTotalIngresos_2': string
  'CuentaResultadosBis:detailTbTotalIngresos_3': string
  'CuentaResultadosBis:detailTbTotalIngresos_4': string
  'CuentaResultadosBis:detailTbTotalIngresos_5': string
  'CuentaResultadosBis:detailTbTotalIngresos_6': string
  'CuentaResultadosBis:detailTbTotalIngresos_7': string
  'CuentaResultadosBis:detailTbTotalIngresos_8': string
  'CuentaResultadosBis:detailTbDotaciones': string
  'CuentaResultadosBis:detailTbTotalIngresos_9': string
  'CuentaResultadosBis:detailTbTotalIngresos_10': string
  'CuentaResultadosBis:detailTbTotalIngresos_11': string
  'CuentaResultadosBis:detailTbTotalIngresos_12': string
  'CuentaResultadosBis:detailTbTotalIngresos_13': string
  'CuentaResultadosBis:detailTbTotalExplotacion': string
  'CuentaResultadosBis:detailTbTotalExplotacion_1': string
  'CuentaResultadosBis:detailTbBeneficio': string
  'CuentaResultadosBis:detailTbResultado': string
  'CuentaResultadosBis:detailTbResultado_1': string
  'CuentaResultadosBis:detailTbResultado_2': string
  'CuentaResultadosBis:detailTbResultado_3': string
  'CuentaResultadosBis:detailTbResultado_4': string
  'CuentaResultadosBis:detailTbResultado_5': string
  'CuentaResultadosBis:detailTbResultado_6': string
  'CuentaResultadosBis:detailTbTotalIngresoFinanciero': string
  'CuentaResultadosBis:detailTbTotalIngreso_1': string
  'CuentaResultadosBis:detailTbTotalIngreso_2': string
  'CuentaResultadosBis:detailTbTotalIngreso_3': string
  'CuentaResultadosBis:detailTbTotalIngreso_4': string
  'CuentaResultadosBis:detailTbTotalGastoFinanciero': string
  'CuentaResultadosBis:detailTbResultadoFinanciero': string
  'CuentaResultadosBis:detailTbResultadoOrdinario': string
  'CuentaResultadosBis:detailTbIngresoExcep_1': string
  'CuentaResultadosBis:detailTbIngresoExcep_2': string
  'CuentaResultadosBis:detailTbIngresoExcep_3': string
  'CuentaResultadosBis:detailTbTotalIngresoExtra': string
  'CuentaResultadosBis:detailTbTotalIngresoExtra_1': string
  'CuentaResultadosBis:detailTbTotalIngresoExtra_2': string
  'CuentaResultadosBis:detailTbTotalIngresoExtra_3': string
  'CuentaResultadosBis:detailTbTotalGastoExtra_h': string
  'CuentaResultadosBis:detailTbTotalGastoExtra_4': string
  'CuentaResultadosBis:detailTbTotalGastoExtra_41': string
  'CuentaResultadosBis:detailTbTotalGastoExtra_42': string
  'CuentaResultadosBis:detailTbTotalIngreso': string
  'CuentaResultadosBis:detailTbTotalGasto': string
  'CuentaResultadosBis:detailTbResultadoEjercicio': string
  'CuentaResultadosBis:detailTbOtrasCuentas': string
  'CuentaResultadosBis:detailTbEbitda': string
  'CuentaResultadosBis:detailTbGastoPersonal': string
  'CuentaResultadosBis:detailTbCompras': string
  'CuentaResultadosBis:detailTbCashFlow': string
}

export interface ICuentasResultadosBisRequestForm {
  ventasMercancias1: string
  ventasMercancias2: string
  ventasMercancias3: string
  ventasBienes1: string
  ventasBienes2: string
  ventasBienes3: string
  prestacionServicio1: string
  prestacionServicio2: string
  prestacionServicio3: string
  prestacionServicio_11: string
  prestacionServicio_12: string
  prestacionServicio_13: string
  prestacionServicio_21: string
  prestacionServicio_22: string
  prestacionServicio_23: string
  prestacionServicio_31: string
  prestacionServicio_32: string
  prestacionServicio_33: string
  prestacionServicio_41: string
  prestacionServicio_42: string
  prestacionServicio_43: string
  prestacionServicio_51: string
  prestacionServicio_52: string
  prestacionServicio_53: string
  prestacionServicio_61: string
  prestacionServicio_62: string
  prestacionServicio_63: string
  totalIngresos1: string
  totalIngresos2: string
  totalIngresos3: string
  totalIngresos_11: string
  totalIngresos_12: string
  totalIngresos_13: string
  totalIngresos_21: string
  totalIngresos_22: string
  totalIngresos_23: string
  totalIngresos_31: string
  totalIngresos_32: string
  totalIngresos_33: string
  totalIngresos_41: string
  totalIngresos_42: string
  totalIngresos_43: string
  totalIngresos_51: string
  totalIngresos_52: string
  totalIngresos_53: string
  totalIngresos_61: string
  totalIngresos_62: string
  totalIngresos_63: string
  totalIngresos_71: string
  totalIngresos_72: string
  totalIngresos_73: string
  totalIngresos_81: string
  totalIngresos_82: string
  totalIngresos_83: string
  dotaciones1: string
  dotaciones2: string
  dotaciones3: string
  totalIngresos_91: string
  totalIngresos_92: string
  totalIngresos_93: string
  totalIngresos_101: string
  totalIngresos_102: string
  totalIngresos_103: string
  totalIngresos_111: string
  totalIngresos_112: string
  totalIngresos_113: string
  totalIngresos_121: string
  totalIngresos_122: string
  totalIngresos_123: string
  totalIngresos_131: string
  totalIngresos_132: string
  totalIngresos_133: string
  totalExplotacion1: string
  totalExplotacion2: string
  totalExplotacion3: string
  totalExplotacion_11: string
  totalExplotacion_12: string
  totalExplotacion_13: string
  beneficio1: string
  beneficio2: string
  beneficio3: string
  resultado1: string
  resultado2: string
  resultado3: string
  resultado_11: string
  resultado_12: string
  resultado_13: string
  resultado_21: string
  resultado_22: string
  resultado_23: string
  resultado_31: string
  resultado_32: string
  resultado_33: string
  resultado_41: string
  resultado_42: string
  resultado_43: string
  resultado_51: string
  resultado_52: string
  resultado_53: string
  resultado_61: string
  resultado_62: string
  resultado_63: string
  totalIngresoFinanciero1: string
  totalIngresoFinanciero2: string
  totalIngresoFinanciero3: string
  totalIngreso_11: string
  totalIngreso_12: string
  totalIngreso_13: string
  totalIngreso_21: string
  totalIngreso_22: string
  totalIngreso_23: string
  totalIngreso_31: string
  totalIngreso_32: string
  totalIngreso_33: string
  totalIngreso_41: string
  totalIngreso_42: string
  totalIngreso_43: string
  totalGastoFinanciero1: string
  totalGastoFinanciero2: string
  totalGastoFinanciero3: string
  resultadoFinanciero1: string
  resultadoFinanciero2: string
  resultadoFinanciero3: string
  resultadoOrdinario1: string
  resultadoOrdinario2: string
  resultadoOrdinario3: string
  ingresoExcep_11: string
  ingresoExcep_12: string
  ingresoExcep_13: string
  ingresoExcep_21: string
  ingresoExcep_22: string
  ingresoExcep_23: string
  ingresoExcep_31: string
  ingresoExcep_32: string
  ingresoExcep_33: string
  totalIngresoExtra1: string
  totalIngresoExtra2: string
  totalIngresoExtra3: string
  totalIngresoExtra_11: string
  totalIngresoExtra_12: string
  totalIngresoExtra_13: string
  totalIngresoExtra_21: string
  totalIngresoExtra_22: string
  totalIngresoExtra_23: string
  totalIngresoExtra_31: string
  totalIngresoExtra_32: string
  totalIngresoExtra_33: string
  totalGastoExtra_h1: string
  totalGastoExtra_h2: string
  totalGastoExtra_h3: string
  totalGastoExtra_41: string
  totalGastoExtra_42: string
  totalGastoExtra_43: string
  totalGastoExtra_411: string
  totalGastoExtra_412: string
  totalGastoExtra_413: string
  totalGastoExtra_421: string
  totalGastoExtra_422: string
  totalGastoExtra_423: string
  totalIngreso1: string
  totalIngreso2: string
  totalIngreso3: string
  totalGasto1: string
  totalGasto2: string
  totalGasto3: string
  resultadoEjercicio1: string
  resultadoEjercicio2: string
  resultadoEjercicio3: string
  otrasCuentas1: string
  otrasCuentas2: string
  otrasCuentas3: string
  ebitda1: string
  ebitda2: string
  ebitda3: string
  gastoPersonal1: string
  gastoPersonal2: string
  gastoPersonal3: string
  compras1: string
  compras2: string
  compras3: string
  cashFlow1: string
  cashFlow2: string
  cashFlow3: string
}

export interface ICuentasResultadosBis {
  i18n: Ii18nCuentasResultadosBis
  data: ICuentasResultadosBisRequestForm
}
