import ThemeCatalogueProvider from './ui/theme/ThemeProvider'
import { BoeForm, IBoeForm } from './components/templates/BoeForm/BoeForm'
import { ConsultReports, IConsultsReports } from './components/templates/ConsultReports/ConsultReports'
import { CopyFileProcess, ICopyFileProcess } from './components/templates/CopyFileProcess/CopyFileProcess'
import { SimulationReport, ISimulationReport } from './components/templates/SimulationReport/SimulationReport'
import { FilesTableFTP, IFilesTableFTP } from './components/templates/FilesTableFTP/FilesTable'
import { ReportDetail, IReportDetail } from './components/templates/ReportDetail/ReportDetail'
import { ReportReferences, IReportReferences } from './components/templates/ReportReferences/ReportReferences'
import { ReportPortugal, IReportPortugal } from './components/templates/ReportPortugal/ReportPortugal'
import { ReportLatin, IReportLatin } from './components/templates/ReportLatin/ReportLatin'
import { ReportSpain } from './components/templates/ReportsSpain/ReportSpain'
import { IReportsSpain } from './components/templates/ReportsSpain/types'
import { ReportFrance, IReportFrance } from './components/templates/ReportFrance/ReportFrance'
import { RequestList, IRequestList } from './components/templates/RequestList/RequestList'
import { ShowReport, IShowReport } from './components/templates/ShowReport/ShowReport'
import { CreatedReports, ICreatedReports } from './components/templates/CreatedReports/CreatedReports'
import { MasiveGestion, IMasiveGestion } from './components/templates/MasiveGestion/MasiveGestion'
import { UserMenu, IUserMenu } from './components/templates/UserMenu/UserMenu'
import { ReportTypes } from './components/templates/BaseReport/types'
import { BaseReport } from './components/templates/BaseReport/BaseReport'
import { ModalError } from './components/organisms/ModalError/ModalError'
import { IModalError } from './components/organisms/ModalError/types'
import { ModalSuccess } from './components/organisms/ModalSuccess/ModalSuccess'
import { IModalSuccess } from './components/organisms/ModalSuccess/types'
import {
  userDataFaker,
  applicationsFaker
} from './mocks'

var dataGeneralDataEmpty = {
  agencia: '',
  codigo: '',
  razonSocial: '',
  codigoFiscal: '',
  ajt1: '',
  ajt2: '',
  remitente: '',
  nombreDocumento: '',
  tipoDocumento: '',
  fechaMensaje: '',
  fecha: '',
  fechaBusqueda: '',
  numeroDocumento: '',
  numeroPeticion: '',
  moneda: '',
  nombreFichero: ''
}

var dataIdentificationEmpty = {
  razonSocial: '',
  denominacion: '',
  primaryAddress: '',
  domicilio: '',
  addressLine: '',
  localidad: '',
  provincia: '',
  codigoPostal: '',
  descripcion: '',
  pais: '',
  anteriorRazonSocial: '',
  referenciaInforme: '',
  referenciaFuente: '',
  codigoEmpresa: '',
  registrationNumber: '',
  bolsa: ''
}

var dataDenominacionesComercialesEmpty = {
  codigoFiscal: '',
  telefono: '',
  email: '',
  actividades: '',
  comentarios: '',
  nif: '',
  fax: '',
  web: ''
}

var dataSummaryEmpty = {
  formaJuridica: '',
  anteriorFormaJuríd: '',
  fechaConstrucción: '',
  fechaFormaJurídica: '',
  estadoActual: '',
  fechaEstadoActual: '',
  fechaInicioActividad: '',
  estadoActualMope: '',
  comentarios: '',
  terminosVenta: ''
}

var dataSpecificItemsEmpty = {
  cotationAlfa: '',
  descCotationalfa: '',
  motifNote: '',
  descMotifNote: '',
  cessationActivite: '',
  incidents: '',
  ventasEstimadas: ''
}

var dataInformaDataEmpty = {
  numeroPeticion: '',
  codigoProducto: '',
  codNomEmpresa: '',
  tipoCorresponsal: '',
  numeroDocumento: '',
  tipoDocumento: '',
  numeroInforme: '',
  numeroMovimiento: '',
  origen: '',
  gravedadAjt: '',
  tipoFichero: '',
  nombreFichero: ''
}

var dataNonPaymentBadexcugEmpty = {
  nombreRazonSocial: '',
  identificadorPersona: '',
  fechaAlta: '',
  fechaUltimaAct: '',
  fechaUltimaConsulta: '',
  entidadUltConsulta: '',
  numeroOperaciones: '',
  importeOperaciones: '',
  operIncidencias: '',
  cuotasImpagadas: '',
  importeImpagado: '',
  peorSituacion: '',
  fechaPeorSituacion: '',
  importeAnotacionMax: '',
  fechaAnotacionMax: ''
}

var dataOperationCodeBadexcugEmpty = [
  {
    codigoOperacion: '',
    identificadorPersona: '',
    fechaAlta: '',
    entidadCedente: '',
    producto: '',
    naturaleza: '',
    situacion: '',
    fechaInicio: '',
    fechaFinal: '',
    numeroCuotas: '',
    importeCuotas: '',
    importePendiente: '',
    importeImpagado: '',
    numCuotasImpagadas: '',
    fechaPrimerVencimiento: '',
    fechaUltimoVencimiento: '',
    informacionAdicional: ''
  },
  {
    codigoOperacion: '',
    identificadorPersona: '',
    fechaAlta: '',
    entidadCedente: '',
    producto: '',
    naturaleza: '',
    situacion: '',
    fechaInicio: '',
    fechaFinal: '',
    numeroCuotas: '',
    importeCuotas: '',
    importePendiente: '',
    importeImpagado: '',
    numCuotasImpagadas: '',
    fechaPrimerVencimiento: '',
    fechaUltimoVencimiento: '',
    informacionAdicional: ''
  }
]

var dataProtestsDemandsEmpty = {
  incidencia: '',
  tipo: '',
  fecha: '',
  incidencias: '',
  importeIncidencias: '',
  nonPayment: dataNonPaymentBadexcugEmpty,
  operationcode: dataOperationCodeBadexcugEmpty
}

var dataCommunicationsEmpty = {
  phone1: '',
  phone2: '',
  phone3: ''
}

var dataTaxCodesEmpty = {
  numDum: '',
  fechaAsignacion1: '',
  fechaAsignacion12: '',
  fechaAsignacion13: '',
  fechaCambio1: '',
  fechaCambio12: '',
  fechaCambio13: '',
  fechaAsignacion2: '',
  fechaAsignacion22: '',
  fechaAsignacion23: '',
  fechaCambio2: '',
  fechaCambio22: '',
  fechaCambio23: '',
  fechaAsignacion3: '',
  fechaAsignacion32: '',
  fechaAsignacion33: '',
  fechaCambio3: '',
  fechaCambio32: '',
  fechaCambio33: '',
  fechaAsignacion4: '',
  fechaAsignacion42: '',
  fechaAsignacion43: '',
  fechaCambio4: '',
  fechaCambio42: '',
  fechaCambio43: '',
  tipoIdentificacion: '',
  numeroIdentificacion: ''
}

var dataNaceSicEmpty = {
  codigoSIC: '',
  descripcionSIC: '',
  codigoNACE: '',
  descripcionNACE: ''
}

var dataLegalFormEmpty = {
  concursales: '',
  formajuridica1: '',
  formajuridica2: '',
  formajuridicainicial1: '',
  formajuridicainicial2: '',
  fecharegistro: '',
  fechainicial: ''
}

var dataBasicDataEmpty = {
  organizacion: '',
  fecha: '',
  constitucion: '',
  mes: '',
  tipoempresa: '',
  tipofirma: '',
  status: '',
  fechastatus: '',
  capitalNominal: '',
  capNominalAnterior: '',
  capitalDesembolsado: '',
  fechaCambioCapital: '',
  fechaUltimoBalance: '',
  resultados: '',
  moneda: '',
  cifras: '',
  facturación: '',
  empleados: '',
  comentarios: ''
}

var dataCapitalEmpty = {
  capital1: '',
  capital2: '',
  tipo: '',
  acciones: '',
  importe: '',
  empleados1: '',
  empleados2: ''
}

var dataCnaeEmpty = {
  tipo: '',
  actividad: '',
  input3: '',
  input4: '',
  input5: '',
  input6: '',
  input7: '',
  input8: ''
}

var dataDealFormEmpty = {
  clientes: '',
  comentarios: '',
  tipomercado1: '',
  tipomercado2: ''
}

var dataImportsExportsEmpty = {
  importaciones: '',
  paises: '',
  producto: '',
  exportaciones: '',
  paises2: ''
}

var dataOtherEventsEmpty = [
  {
    evento: '',
    fecha: '',
    efecto: '',
    importe: '',
    localizacion: ''
  }
]

var dataCompanyAssetsEmpty = {
  clase: '',
  tipoactivo: '',
  unidades: '',
  comentarios: ''
}

var dataRelationShipEmpty = [
  {
    input1: '',
    input2: '',
    numDum: '',
    accionista: '',
    tipo: '',
    porcentaje: '',
    importe1: '',
    importe2: ''
  }
]

var dataAdministratorEmpty = {
  input1: '',
  input2: '',
  input3: '',
  form: [
    {
      relaciones1: '',
      relaciones2: '',
      asociacion: '',
      numeroDun: '',
      estatus1: '',
      estatus2: '',
      administrador: '',
      fecha: ''
    }
  ]
}

var dataSubsidiaryAffiliatesEmpty = {
  input1: '',
  input2: '',
  numDum: '',
  participada: '',
  participacion: '',
  importe: ''
}

var dataBranchOfficesEmpty = {
  input1: '',
  input2: '',
  numDum: '',
  participada: '',
  participacion: '',
  importe: ''
}

var dataBankEmpty = {
  input1: '',
  input2: ''
}

var dataPaymentFormEmpty = {
  transacciones: '',
  proveedores: '',
  paydex: ''
}

var dataPaydexHistoricEmpty = {
  mes1: '',
  mes2: '',
  mes3: '',
  mes4: '',
  mes5: '',
  mes6: '',
  mes7: '',
  mes8: '',
  paidex1: '',
  paidex2: '',
  paidex3: '',
  paidex4: '',
  paidex5: '',
  paidex6: '',
  paidex7: '',
  paidex8: ''
}

var dataPaydexSectorialEmpty = {
  cuatrilsup: '',
  mediana: '',
  cuatrilinf: ''
}

var dataSummaryPaymentsEmpty = [
  {
    fechacalculo: '',
    periodoconsiderado: '',
    numproveedores: '',
    transacciones: '',
    importetransacciones: '',
    importeretrasado: '',
    moneda: '',
    comportamiento1: '',
    comportamiento2: '',
    comportamiento3: '',
    comportamiento4: '',
    transaccionescomerciales1: '',
    transaccionescomerciales2: '',
    transaccionescomerciales3: '',
    transaccionescomerciales4: '',
    promediominimo1: '',
    promediominimo2: '',
    promediominimo3: '',
    promediominimo4: '',
    promediomaximo1: '',
    promediomaximo2: '',
    promediomaximo3: '',
    promediomaximo4: '',
    importe1: '',
    importe2: '',
    importe3: '',
    importe4: '',
    monedacol1: '',
    monedacol2: '',
    monedacol3: '',
    monedacol4: ''
  }
]

var dataLegalProceduresEmpty = [
  {
    entidad: '',
    fecha: '',
    tipoaccion: '',
    claseaccion: '',
    fechapublicacion: '',
    distrito: '',
    duracion: '',
    fechafinalizacion: '',
    importe: '',
    costes: '',
    situacion: '',
    resolucion: '',
    moneda: '',
    demandante: '',
    comentarios: ''
  }
]

var dataLegalConfirmedFaker = [
  {
    fecha: '',
    periodo: '',
    tipoaccion: '',
    claseaccion: '',
    nprocedimientos: '',
    importe: '',
    procedimientoLegal: ''
  }
]

var dataRatingFormFaker = [
  {
    fechaasignacion: '',
    formaasignacionrating: '',
    dbrating: '',
    indicador: '',
    observaciones: '',
    riesgo1: '',
    riesgo2: '',
    riesgo3: '',
    riesgo4: '',
    riesgo5: '',
    riesgo6: '',
    riesgo7: '',
    riesgo8: '',
    credito1: '',
    credito2: '',
    formaasignacioncredito: '',
    evaluacioncredito: '',
    otrosratings1: '',
    otrosratings2: '',
    valor1: '',
    valor2: ''
  }
]

var datosHostDataEmpty = {
  organizacion: '',
  numeroPeticion: '',
  nomCorresponsal: '',
  codProducto: '',
  codEmpresa: '',
  tipoCorresponsal: '',
  numeroDocumento: '',
  numeroInforme: '',
  origen: '',
  tipoFichero: '',
  tipoDocumento: '',
  numeroMovimiento: '',
  gravedad: '',
  nombreFichero: ''
}

var dataAggregateSummaryDataEmpty = {
  tipoResposabilidad: '',
  factoring1: '',
  factoring2: '',
  factoring3: '',
  factoring4: '',
  otros1: '',
  otros2: '',
  otros3: '',
  otros4: '',
  descubierto1: '',
  descubierto2: '',
  descubierto3: '',
  descubierto4: '',
  facilities1: '',
  facilities2: '',
  facilities3: '',
  facilities4: '',
  credito1: '',
  credito2: '',
  credito3: '',
  credito4: '',
  freeFloat1: '',
  freeFloat2: '',
  freeFloat3: '',
  freeFloat4: '',
  renovable1: '',
  renovable2: '',
  renovable3: '',
  renovable4: '',
  noRenobable1: '',
  noRenobable2: '',
  noRenobable3: '',
  noRenobable4: '',
  factoringBis1: '',
  factoringBis2: '',
  factoringBis3: '',
  factoringBis4: '',
  confirming1: '',
  confirming2: '',
  confirming3: '',
  confirming4: '',
  otrosValores1: '',
  otrosValores2: '',
  otrosValores3: '',
  otrosValores4: '',
  descuentos1: '',
  descuentos2: '',
  descuentos3: '',
  descuentos4: '',
  creditoPersonal1: '',
  creditoPersonal2: '',
  creditoPersonal3: '',
  creditoPersonal4: '',
  creditoAutomovil1: '',
  creditoAutomovil2: '',
  creditoAutomovil3: '',
  creditoAutomovil4: '',
  avales1: '',
  avales2: '',
  avales3: '',
  avales4: '',
  otrosAvales1: '',
  otrosAvales2: '',
  otrosAvales3: '',
  otrosAvales4: '',
  financiacion1: '',
  financiacion2: '',
  financiacion3: '',
  financiacion4: '',
  otrosBis1: '',
  otrosBis2: '',
  otrosBis3: '',
  otrosBis4: ''
}

var dataEntityCommunicationDataEmpty = {
  deuda: '',
  deudaDeudor: '',
  incumplimiento: '',
  incumplimientoDeudor: '',
  potencial: '',
  potencialDeudor: ''
}

var dataExternalFinancingEmpty = {
  fechamodificacion1: '',
  fechamodificacion2: '',
  codigocambio: '',
  comentarios: ''
}

var dataLegalProceduresITEmpty = {
  fechaactualizacion: ''
}

var dataCreditResponsabilityDataEmpty = {
  diaCentralizacion: '',
  entidades: '',
  incumplimiento: '',
  productosFinancieros: ''
}

var bankDataEmpty = {
  denominacion: '',
  codigoIdentificador: ''
}

var dataPaymentsLegalProcessEmpty = {
  empresa: '',
  history: '',
  financial: '',
  criminal: '',
  judgements: '',
  claims: '',
  secured: '',
  legal: '',
  disaster: '',
  operational: '',
  others: '',
  actual: '',
  months: '',
  norm: ''
}

var dataCommunicationsPOAEmpty = {
  telefonos1: '',
  telefonos2: '',
  telefonos3: '',
  emails1: '',
  emails2: '',
  emails3: '',
  webs1: '',
  webs2: '',
  webs3: ''
}

var datosSummaryExternalFinancingEmpty = {
  fechaactualizacion: '',
  periodo: '',
  tipofinanciacion: '',
  numerototal: '',
  importetotal1: '',
  financiacionreciente: '',
  numeroeventos: '',
  importetotal2: ''
}

var dataExternalFinancingPOAEmpty = [
  {
    fechamodificacion: '',
    fechacancelacion: '',
    tipofinanciacion: '',
    proveedor: '',
    importe: '',
    bienesgarantia: '',
    comentarios: ''
  }
]

var dataAJTSPOAEmpty = {
  fechamodificacion: '',
  codigocambio: '',
  nombre: '',
  direccion: '',
  codigofiscal: '',
  formajuridica: '',
  comentarios: ''
}

var dataIdentificacionEspanaInformaEmpty = {
  denominacion: '',
  domicilio: '',
  localidad: '',
  provincia: '',
  codigopostal: '',
  pais: '',
  tipoidenfiscal: '',
  codidenfiscal: '',
  fechultbalance: '',
  comentariosbalances: '',
  incidenciasdep: '',
  comentariogen: '',
  comentarios: ''
}

var dataAJTSEspanaInformaEmpty = {
  tipoderespuesta: '',
  escort: '',
  fechaconstitucion: '',
  balance: '',
  deposito: '',
  negativa: '',
  compromiso: '',
  incidentes: '',
  pagos: '',
  experiencia: '',
  documentos: ''
}

var dataDatosInformaEmpty = {
  numeropeticion: '',
  codigoproducto: '',
  codnomempresa: '',
  tipocorresponsal: '',
  numerodocumento: '',
  tipodocumento: '',
  numeroinforme: '',
  numeromovimiento: '',
  origen: '',
  gravedadajt: '',
  tipofichero: '',
  nombrefichero: ''
}

var dataCompanyAssetsEUDBFREmpty = {
  clase: '',
  tipoactivo: '',
  unidades: '',
  comentarios: '',
  ajt1: '',
  ajt2: '',
  fechamod: '',
  codigocambio: '',
  comentariosajts: ''
}

var dataScoreEmpty = {
  score: ''
}

var dataIdentityVerificationEmpty = {
  nombre: '',
  identificacion: '',
  numeroduns: '',
  calle: '',
  localidad: '',
  codigopostal: '',
  provincia: '',
  profesion: '',
  actividadeconomica: '',
  domicilioCompleto1: '',
  domicilioCompleto2: '',
  domicilioCompleto3: '',
  domicilioCompleto4: '',
  fechaconstitucion: '',
  fechanacimiento: '',
  edad: '',
  formajuridica: '',
  codigoactividadprincipal: '',
  actividadprincipal: '',
  codigoactividadsecundaria: '',
  actividadsecundaria: '',
  empleadosverificados: '',
  sinactividad: '',
  concursopresentado: '',
  iva: '',
  ganaciassociedades: '',
  ganaciaspersonasfisicas: ''
}

var dataConsultasEmpty = {
  temporales: '',
  permanentes: '',
  total: ''
}

var dataBouncedChecksEmpty = {
  sinfondo1: '',
  sinfondo2: '',
  sinfondo3: '',
  sinfondo4: '',
  sinfondo5: '',
  sinfondo6: '',
  sinfondo7: '',
  sinfondo8: '',
  defectosformales1: '',
  defectosformales2: '',
  defectosformales3: '',
  defectosformales4: '',
  defectosformales5: '',
  defectosformales6: '',
  defectosformales7: '',
  defectosformales8: '',
  totalrechazados1: '',
  totalrechazados2: '',
  totalrechazados3: '',
  totalrechazados4: '',
  totalrechazados5: '',
  totalrechazados6: '',
  totalrechazados7: '',
  totalrechazados8: '',
  totalAbonados1: '',
  totalAbonados2: '',
  totalAbonados3: '',
  totalAbonados4: '',
  totalAbonados5: '',
  totalAbonados6: '',
  totalAbonados7: '',
  totalAbonados8: '',
  porcentajeabonados1: '',
  porcentajeabonados2: '',
  porcentajeabonados3: '',
  porcentajeabonados4: '',
  porcentajeabonados5: '',
  porcentajeabonados6: '',
  porcentajeabonados7: '',
  porcentajeabonados8: ''
}

var dataRejectChecksLegalEmpty = {
  cheque1: '',
  cheque2: '',
  cheque3: '',
  cheque4: '',
  cheque5: '',
  fecharech1: '',
  fecharech2: '',
  fecharech3: '',
  fecharech4: '',
  fecharech5: '',
  monto1: '',
  monto2: '',
  monto3: '',
  monto4: '',
  monto5: '',
  causal1: '',
  causal2: '',
  causal3: '',
  causal4: '',
  causal5: '',
  fechapago1: '',
  fechapago2: '',
  fechapago3: '',
  fechapago4: '',
  fechapago5: '',
  revision1: '',
  revision2: '',
  revision3: '',
  revision4: '',
  revision5: '',
  pagomulta1: '',
  pagomulta2: '',
  pagomulta3: '',
  pagomulta4: '',
  pagomulta5: ''
}

var dataBureauCreditEmpty = {
  porcentajesituacion1: '',
  porcentajesituacion2: '',
  porcentajesituacion3: '',
  porcentajesituacion4: '',
  porcentajesituacion5: '',
  porcentajesituacion6: '',
  porcentajesituacion7: '',
  porcentajesituacion8: '',
  porcentajesituacion9: '',
  porcentajesituacion10: '',
  porcentajesituacion11: '',
  porcentajesituacion12: '',
  porcentajesituacion13: '',
  porcentajesituacion14: '',

  situacion1: '',
  situacion2: '',
  situacion3: '',
  situacion4: '',
  situacion5: '',
  situacion6: '',
  situacion7: '',
  situacion8: '',
  situacion9: '',
  situacion10: '',
  situacion11: '',
  situacion12: '',
  situacion13: '',
  situacion14: '',

  codigoentidad1: '',
  codigoentidad2: '',
  codigoentidad3: '',
  codigoentidad4: '',
  codigoentidad5: '',
  codigoentidad6: '',
  codigoentidad7: '',
  codigoentidad8: '',
  codigoentidad9: '',
  codigoentidad10: '',
  codigoentidad11: '',
  codigoentidad12: '',
  codigoentidad13: '',
  codigoentidad14: '',

  periodo1: '',
  periodo2: '',
  periodo3: '',
  periodo4: '',
  periodo5: '',
  periodo6: '',
  periodo7: '',
  periodo8: '',
  periodo9: '',
  periodo10: '',
  periodo11: '',
  periodo12: '',
  periodo13: '',
  periodo14: '',

  monto1: '',
  monto2: '',
  monto3: '',
  monto4: '',
  monto5: '',
  monto6: '',
  monto7: '',
  monto8: '',
  monto9: '',
  monto10: '',
  monto11: '',
  monto12: '',
  monto13: '',
  monto14: '',

  porcentajetotal1: '',
  porcentajetotal2: '',
  porcentajetotal3: '',
  porcentajetotal4: '',
  porcentajetotal5: '',
  porcentajetotal6: '',
  porcentajetotal7: '',
  porcentajetotal8: '',
  porcentajetotal9: '',
  porcentajetotal10: '',
  porcentajetotal11: '',
  porcentajetotal12: '',
  porcentajetotal13: '',
  porcentajetotal14: ''
}

var dataJudicialSourcesAlertsEmpty = {
  alerts: ''
}

var dataScorePeruEmpty = {
  score: '',
  puntaje: '',
  nivelRiesgo: '',
  conclusion: '',
  scoreEmpresasNoPrico: '',
  scoreAutonomos: '',
  tipoEmpresa: ''
}

var dataDirectoryNaturalPersonsEmpty = {
  codigoFiscal: '',
  tipoDocumento: '',
  denominacion: '',
  fechaDeNacimiento: '',
  estadoCivil: '',
  nacionalidad: '',
  gradoInstruccion: '',
  telefono: '',
  ocupacion: ''
}

var dataDirectorySunatEmpty = {
  codigoFiscal: '',
  denominacion: '',
  nombreComercial: '',
  direccion: '',
  fechaConstitución: '',
  tipoDeContribuyente: '',
  estado: '',
  condicionContribuyente: '',
  dependencia: '',
  actividad: '',
  actividadComercioExterior: '',
  padron: ''
}

var dataLastAddressesEmpty = {
  fecha: '',
  direccion: '',
  telefono: '',
  fuente: '',
  fecha2: '',
  direccion2: '',
  telefono2: '',
  fuente2: ''
}

var dataLegalAgentsEmpty = {
  name: '',
  name2: '',
  tipoDocumento: '',
  tipoDocumento2: '',
  nDocumento: '',
  nDocumento2: '',
  cargo: '',
  cargo2: '',
  fecha: '',
  fecha2: ''
}

var dataRegulatedNonFinancialSystemEmpty = {
  regulatedPeriodo1: '',
  regulatedPeriodo2: '',
  regulatedPeriodo3: '',
  regulatedPeriodo4: '',
  regulatedPeriodo5: '',
  regulatedPeriodo6: '',
  regulatedFlagImpagos1: '',
  regulatedFlagImpagos2: '',
  regulatedFlagImpagos3: '',
  regulatedFlagImpagos4: '',
  regulatedFlagImpagos5: '',
  regulatedFlagImpagos6: '',
  regulatedFlagDeudaAtrasada1: '',
  regulatedFlagDeudaAtrasada2: '',
  regulatedFlagDeudaAtrasada3: '',
  regulatedFlagDeudaAtrasada4: '',
  regulatedFlagDeudaAtrasada5: '',
  regulatedFlagDeudaAtrasada6: '',
  regulatedFlagDeudasImpagadasInfocorp1: '',
  regulatedFlagDeudasImpagadasInfocorp2: '',
  regulatedFlagDeudasImpagadasInfocorp3: '',
  regulatedFlagDeudasImpagadasInfocorp4: '',
  regulatedFlagDeudasImpagadasInfocorp5: '',
  regulatedFlagDeudasImpagadasInfocorp6: '',
  regulatedFlagInformacionNoDisponible1: '',
  regulatedFlagInformacionNoDisponible2: '',
  regulatedFlagInformacionNoDisponible3: '',
  regulatedFlagInformacionNoDisponible4: '',
  regulatedFlagInformacionNoDisponible5: '',
  regulatedFlagInformacionNoDisponible6: '',
  regulatedDiasAtraso1: '',
  regulatedDiasAtraso2: '',
  regulatedDiasAtraso3: '',
  regulatedDiasAtraso4: '',
  regulatedDiasAtraso5: '',
  regulatedDiasAtraso6: '',
  nonRegulatedPeriodo1: '',
  nonRegulatedPeriodo2: '',
  nonRegulatedPeriodo3: '',
  nonRegulatedPeriodo4: '',
  nonRegulatedPeriodo5: '',
  nonRegulatedPeriodo6: '',
  nonRegulatedFlagImpagos1: '',
  nonRegulatedFlagImpagos2: '',
  nonRegulatedFlagImpagos3: '',
  nonRegulatedFlagImpagos4: '',
  nonRegulatedFlagImpagos5: '',
  nonRegulatedFlagImpagos6: '',
  nonRegulatedFlagDeudaAtrasada1: '',
  nonRegulatedFlagDeudaAtrasada2: '',
  nonRegulatedFlagDeudaAtrasada3: '',
  nonRegulatedFlagDeudaAtrasada4: '',
  nonRegulatedFlagDeudaAtrasada5: '',
  nonRegulatedFlagDeudaAtrasada6: '',
  nonRegulatedFlagDeudasImpagadasInfocorp1: '',
  nonRegulatedFlagDeudasImpagadasInfocorp2: '',
  nonRegulatedFlagDeudasImpagadasInfocorp3: '',
  nonRegulatedFlagDeudasImpagadasInfocorp4: '',
  nonRegulatedFlagDeudasImpagadasInfocorp5: '',
  nonRegulatedFlagDeudasImpagadasInfocorp6: '',
  nonRegulatedFlagInformacionNoDisponible1: '',
  nonRegulatedFlagInformacionNoDisponible2: '',
  nonRegulatedFlagInformacionNoDisponible3: '',
  nonRegulatedFlagInformacionNoDisponible4: '',
  nonRegulatedFlagInformacionNoDisponible5: '',
  nonRegulatedFlagInformacionNoDisponible6: '',
  nonRegulatedDiasAtraso1: '',
  nonRegulatedDiasAtraso2: '',
  nonRegulatedDiasAtraso3: '',
  nonRegulatedDiasAtraso4: '',
  nonRegulatedDiasAtraso5: '',
  nonRegulatedDiasAtraso6: ''
}

var dataDebtsLastPeriodEmpty = {
  titlePeriod: '',
  entidadPeorCalificacion: '',
  entidadMayorDeudas: '',
  entidadMayorImporte: '',
  entidadMayorDiasRetraso: '',
  calificacionPeorCalificacion: '',
  calificacionMayorDeudas: '',
  calificacionMayorImporte: '',
  calificacionMayorDiasRetraso: '',
  sistemaFinancieroPeorCalificacion: '',
  sistemaFinancieroMayorDeudas: '',
  sistemaFinancieroMayorImporte: '',
  sistemaFinancieroMayorDiasRetraso: '',
  totalDeudaPeorCalificacion: '',
  totalDeudaMayorDeudas: '',
  totalDeudaMayorImporte: '',
  totalDeudaMayorDiasRetraso: ''
}

var dataDebtHistorySystemEmpty = {
  regulatedPeriodo1: '',
  regulatedPeriodo2: '',
  regulatedPeriodo3: '',
  regulatedPeriodo4: '',
  regulatedPeriodo5: '',
  regulatedPeriodo6: '',
  regulatedCalificacion1: '',
  regulatedCalificacion2: '',
  regulatedCalificacion3: '',
  regulatedCalificacion4: '',
  regulatedCalificacion5: '',
  regulatedCalificacion6: '',
  regulatedNroEntidades1: '',
  regulatedNroEntidades2: '',
  regulatedNroEntidades3: '',
  regulatedNroEntidades4: '',
  regulatedNroEntidades5: '',
  regulatedNroEntidades6: '',
  regulatedDuedaTotal1: '',
  regulatedDuedaTotal2: '',
  regulatedDuedaTotal3: '',
  regulatedDuedaTotal4: '',
  regulatedDuedaTotal5: '',
  regulatedDuedaTotal6: '',
  regulatedDeudaAtrasada1: '',
  regulatedDeudaAtrasada2: '',
  regulatedDeudaAtrasada3: '',
  regulatedDeudaAtrasada4: '',
  regulatedDeudaAtrasada5: '',
  regulatedDeudaAtrasada6: '',
  regulatedDuedaJudicial1: '',
  regulatedDuedaJudicial2: '',
  regulatedDuedaJudicial3: '',
  regulatedDuedaJudicial4: '',
  regulatedDuedaJudicial5: '',
  regulatedDuedaJudicial6: '',
  regulatedDiasAtraso1: '',
  regulatedDiasAtraso2: '',
  regulatedDiasAtraso3: '',
  regulatedDiasAtraso4: '',
  regulatedDiasAtraso5: '',
  regulatedDiasAtraso6: '',
  regulatedDuedaCastigada1: '',
  regulatedDuedaCastigada2: '',
  regulatedDuedaCastigada3: '',
  regulatedDuedaCastigada4: '',
  regulatedDuedaCastigada5: '',
  regulatedDuedaCastigada6: '',
  regulatedDuedaVigente1: '',
  regulatedDuedaVigente2: '',
  regulatedDuedaVigente3: '',
  regulatedDuedaVigente4: '',
  regulatedDuedaVigente5: '',
  regulatedDuedaVigente6: '',
  nonRegulatedPeriodo1: '',
  nonRegulatedPeriodo2: '',
  nonRegulatedPeriodo3: '',
  nonRegulatedPeriodo4: '',
  nonRegulatedPeriodo5: '',
  nonRegulatedPeriodo6: '',
  nonRegulatedCalificacion1: '',
  nonRegulatedCalificacion2: '',
  nonRegulatedCalificacion3: '',
  nonRegulatedCalificacion4: '',
  nonRegulatedCalificacion5: '',
  nonRegulatedCalificacion6: '',
  nonRegulatedNroEntidades1: '',
  nonRegulatedNroEntidades2: '',
  nonRegulatedNroEntidades3: '',
  nonRegulatedNroEntidades4: '',
  nonRegulatedNroEntidades5: '',
  nonRegulatedNroEntidades6: '',
  nonRegulatedDuedaVigente1: '',
  nonRegulatedDuedaVigente2: '',
  nonRegulatedDuedaVigente3: '',
  nonRegulatedDuedaVigente4: '',
  nonRegulatedDuedaVigente5: '',
  nonRegulatedDuedaVigente6: '',
  nonRegulatedDeudaAtrasada1: '',
  nonRegulatedDeudaAtrasada2: '',
  nonRegulatedDeudaAtrasada3: '',
  nonRegulatedDeudaAtrasada4: '',
  nonRegulatedDeudaAtrasada5: '',
  nonRegulatedDeudaAtrasada6: '',
  nonRegulatedDuedaJudicial1: '',
  nonRegulatedDuedaJudicial2: '',
  nonRegulatedDuedaJudicial3: '',
  nonRegulatedDuedaJudicial4: '',
  nonRegulatedDuedaJudicial5: '',
  nonRegulatedDuedaJudicial6: '',
  nonRegulatedDiasAtraso1: '',
  nonRegulatedDiasAtraso2: '',
  nonRegulatedDiasAtraso3: '',
  nonRegulatedDiasAtraso4: '',
  nonRegulatedDiasAtraso5: '',
  nonRegulatedDiasAtraso6: '',
  nonRegulatedDuedaCastigada1: '',
  nonRegulatedDuedaCastigada2: '',
  nonRegulatedDuedaCastigada3: '',
  nonRegulatedDuedaCastigada4: '',
  nonRegulatedDuedaCastigada5: '',
  nonRegulatedDuedaCastigada6: '',
  nonRegulatedDuedaTotal1: '',
  nonRegulatedDuedaTotal2: '',
  nonRegulatedDuedaTotal3: '',
  nonRegulatedDuedaTotal4: '',
  nonRegulatedDuedaTotal5: '',
  nonRegulatedDuedaTotal6: ''
}

var dataLastPeriodDetailEmpty = {
  ultimoPeriodo: '',
  nroEntidades: '',
  totalCreditosVigentes: '',
  totalCreditosVencidos: '',
  peorCalificacion: '',
  totalCreditosRefinanciados: '',
  totalCreditosJudiciales: ''
}

var dataHistoryPeruEmpty = {
  regulatedPeriodo1: '',
  regulatedPeriodo2: '',
  regulatedPeriodo3: '',
  regulatedPeriodo4: '',
  regulatedPeriodo5: '',
  regulatedPeriodo6: '',
  regulatednroEntidades6: '',
  regulatedNroEntidades1: '',
  regulatedNroEntidades2: '',
  regulatedNroEntidades3: '',
  regulatedNroEntidades4: '',
  regulatedNroEntidades5: '',
  regulatedNroEntidades6: '',
  regulatedNor1: '',
  regulatedNor2: '',
  regulatedNor3: '',
  regulatedNor4: '',
  regulatedNor5: '',
  regulatedNor6: '',
  regulatedCpp1: '',
  regulatedCpp2: '',
  regulatedCpp3: '',
  regulatedCpp4: '',
  regulatedCpp5: '',
  regulatedCpp6: '',
  regulatedDef1: '',
  regulatedDef2: '',
  regulatedDef3: '',
  regulatedDef4: '',
  regulatedDef5: '',
  regulatedDef6: '',
  regulatedDud1: '',
  regulatedDud2: '',
  regulatedDud3: '',
  regulatedDud4: '',
  regulatedDud5: '',
  regulatedDud6: '',
  regulatedPer1: '',
  regulatedPer2: '',
  regulatedPer3: '',
  regulatedPer4: '',
  regulatedPer5: '',
  regulatedPer6: '',
  regulatedTotalDeuda1: '',
  regulatedTotalDeuda2: '',
  regulatedTotalDeuda3: '',
  regulatedTotalDeuda4: '',
  regulatedTotalDeuda5: '',
  regulatedTotalDeuda6: '',
  nonRegulatedPeriodo1: '',
  nonRegulatedPeriodo2: '',
  nonRegulatedPeriodo3: '',
  nonRegulatedPeriodo4: '',
  nonRegulatedPeriodo5: '',
  nonRegulatedPeriodo6: '',
  nonRegulatedNroEntidades1: '',
  nonRegulatedNroEntidades2: '',
  nonRegulatedNroEntidades3: '',
  nonRegulatedNroEntidades4: '',
  nonRegulatedNroEntidades5: '',
  nonRegulatedNroEntidades6: '',
  nonRegulatedNor1: '',
  nonRegulatedNor2: '',
  nonRegulatedNor3: '',
  nonRegulatedNor4: '',
  nonRegulatedNor5: '',
  nonRegulatedNor6: '',
  nonRegulatedCpp1: '',
  nonRegulatedCpp2: '',
  nonRegulatedCpp3: '',
  nonRegulatedCpp4: '',
  nonRegulatedCpp5: '',
  nonRegulatedCpp6: '',
  nonRegulatedDef1: '',
  nonRegulatedDef2: '',
  nonRegulatedDef3: '',
  nonRegulatedDef4: '',
  nonRegulatedDef5: '',
  nonRegulatedDef6: '',
  nonRegulatedDud1: '',
  nonRegulatedDud2: '',
  nonRegulatedDud3: '',
  nonRegulatedDud4: '',
  nonRegulatedDud5: '',
  nonRegulatedDud6: '',
  nonRegulatedPer1: '',
  nonRegulatedPer2: '',
  nonRegulatedPer3: '',
  nonRegulatedPer4: '',
  nonRegulatedPer5: '',
  nonRegulatedPer6: '',
  nonRegulatedTotalDeuda1: '',
  nonRegulatedTotalDeuda2: '',
  nonRegulatedTotalDeuda3: '',
  nonRegulatedTotalDeuda4: '',
  nonRegulatedTotalDeuda5: '',
  nonRegulatedTotalDeuda6: ''
}

var dataMicrofinanceDebtEmpty = {
  ultimoPeriodo: '',
  nroEntidadesInput: '',
  peorCalificacion: '',
  regulatedPeriodo1: '',
  regulatedPeriodo2: '',
  regulatedPeriodo3: '',
  regulatedPeriodo4: '',
  regulatedPeriodo5: '',
  regulatedPeriodo6: '',
  regulatednroEntidades6: '',
  regulatedNroEntidades1: '',
  regulatedNroEntidades2: '',
  regulatedNroEntidades3: '',
  regulatedNroEntidades4: '',
  regulatedNroEntidades5: '',
  regulatedNroEntidades6: '',
  regulatedNor1: '',
  regulatedNor2: '',
  regulatedNor3: '',
  regulatedNor4: '',
  regulatedNor5: '',
  regulatedNor6: '',
  regulatedCpp1: '',
  regulatedCpp2: '',
  regulatedCpp3: '',
  regulatedCpp4: '',
  regulatedCpp5: '',
  regulatedCpp6: '',
  regulatedDef1: '',
  regulatedDef2: '',
  regulatedDef3: '',
  regulatedDef4: '',
  regulatedDef5: '',
  regulatedDef6: '',
  regulatedDud1: '',
  regulatedDud2: '',
  regulatedDud3: '',
  regulatedDud4: '',
  regulatedDud5: '',
  regulatedDud6: '',
  regulatedPer1: '',
  regulatedPer2: '',
  regulatedPer3: '',
  regulatedPer4: '',
  regulatedPer5: '',
  regulatedPer6: '',
  regulatedTotalDeuda1: '',
  regulatedTotalDeuda2: '',
  regulatedTotalDeuda3: '',
  regulatedTotalDeuda4: '',
  regulatedTotalDeuda5: '',
  regulatedTotalDeuda6: '',
  nonRegulatedPeriodo1: '',
  nonRegulatedPeriodo2: '',
  nonRegulatedPeriodo3: '',
  nonRegulatedPeriodo4: '',
  nonRegulatedPeriodo5: '',
  nonRegulatedPeriodo6: '',
  nonRegulatedNroEntidades1: '',
  nonRegulatedNroEntidades2: '',
  nonRegulatedNroEntidades3: '',
  nonRegulatedNroEntidades4: '',
  nonRegulatedNroEntidades5: '',
  nonRegulatedNroEntidades6: '',
  nonRegulatedNor1: '',
  nonRegulatedNor2: '',
  nonRegulatedNor3: '',
  nonRegulatedNor4: '',
  nonRegulatedNor5: '',
  nonRegulatedNor6: '',
  nonRegulatedCpp1: '',
  nonRegulatedCpp2: '',
  nonRegulatedCpp3: '',
  nonRegulatedCpp4: '',
  nonRegulatedCpp5: '',
  nonRegulatedCpp6: '',
  nonRegulatedDef1: '',
  nonRegulatedDef2: '',
  nonRegulatedDef3: '',
  nonRegulatedDef4: '',
  nonRegulatedDef5: '',
  nonRegulatedDef6: '',
  nonRegulatedDud1: '',
  nonRegulatedDud2: '',
  nonRegulatedDud3: '',
  nonRegulatedDud4: '',
  nonRegulatedDud5: '',
  nonRegulatedDud6: '',
  nonRegulatedPer1: '',
  nonRegulatedPer2: '',
  nonRegulatedPer3: '',
  nonRegulatedPer4: '',
  nonRegulatedPer5: '',
  nonRegulatedPer6: '',
  nonRegulatedTotalDeuda1: '',
  nonRegulatedTotalDeuda2: '',
  nonRegulatedTotalDeuda3: '',
  nonRegulatedTotalDeuda4: '',
  nonRegulatedTotalDeuda5: '',
  nonRegulatedTotalDeuda6: ''
}

var dataGeneralInformationMexicoEmpty = {
  fechaconsulta: '',
  rfc: '',
  nombre: '',
  tipo: ''
}

var dataScorePymeMexicoEmpty = {
  valorscore: '',
  error: '',
  motivos: ''
}

var dataGeneralDataFranciaEmpty = {
  codigo: '',
  razonsocial: '',
  codigofiscal: '',
  ajt1: '',
  ajt2: ''
}

var dataDocumentRegistrationEmpty = {
  tiporegistro: '',
  fecharegistro: '',
  referencia: ''
}

var dataOtherEventsOneFaker =
  {
    evento: '',
    fecha: '',
    efecto: '',
    importe: '',
    localizacion: ''
  }

var dataBussinessNameFranciaEmpty = {
  denominacion: '',
  fechainicio: ''
}

var dataPreviousCompanyFranciaEmpty = {
  denominacion: '',
  fechainicio: '',
  fechacambiodenominacion: '',
  endindicator: ''
}

var dataPreviousTradeNamesEmpty = {
  denominacion: '',
  fechainicio: '',
  fechacambiodenominacion: ''
}

var dataAddressFranciaEmpty = {
  localidad: '',
  codigopostal: '',
  provincia: '',
  fechainicio: '',
  fechacambiodomicilio: ''
}

var dataTaxCodesFranciaEmpty = {
  numerodun: '',
  fechaasignacion: '',
  fechacambio: ''
}

var dataOrganizationTypeEmpty = {
  statusActual: '',
  fechaStatusActual: '',
  tipoOrganizacion: '',
  fechaTomaControl: '',
  anoConstitucion: '',
  mes: '',
  tipoempresa: '',
  tipofirma: '',
  statusActual2: '',
  fechaStatusActual2: ''
}

var dataLegalFormFranciaEmpty = {
  situacionesConcursales: '',
  formajuridica1: '',
  formajuridica2: '',
  fecharegistroformajuridica: '',
  formajuridicainicial: '',
  fechainicialincorporacion1: '',
  fechainicialincorporacion2: '',
  tipoEmpresa1: '',
  tipoEmpresa2: '',
  statusActual1: '',
  statusActual2: '',
  fechacambioformajuridica1: '',
  fechacambioformajuridica2: ''
}

var dataExternalFinancingFranciaEmpty = {
  fechaobtencionfinancacion: '',
  fechacancelacion: '',
  tipofinanciacion1: '',
  tipofinanciacion2: '',
  proveedorFondos: '',
  importe1: '',
  importe2: '',
  bienesusados: '',
  comentarios1: '',
  comentarios2: ''
}

var dataSummarySourcesFranciaEmpty = {
  fechaactualizacion: '',
  periodoanalizado: '',
  tipofinanciacion: '',
  numerototal: '',
  importetotal1: '',
  financiacionreciente: '',
  situacionactual: '',
  numeroeventossituacion: '',
  importetotal2: ''
}

var dataShareholdersFranciaEmpty = {
  numDum: '',
  accionistadesde: '',
  tipoparticipacion: '',
  porcentajeparticipacion: '',
  importe1: '',
  importe2: ''
}

var dataEmployessFranciaEmpty = {
  nempleados1: '',
  nempleados2: '',
  nempleados3: '',
  nempleados4: '',
  nempleados5: '',
  nempleados6: ''
}

var dataFacilitiesDescriptionEmpty = {
  titularidad: ''
}

var dataBanksFranciaEmpty = {
  input1: '',
  input2: '',
  input3: '',
  input4: '',
  input5: '',
  input6: '',
  input7: ''
}

var dataAdministratorsFranciaEmpty = {
  input1: '',
  fechadenacimiento: '',
  porcentajedeparticipacion: '',
  fechatomacargo: '',
  input2: '',
  input3: '',
  input4: '',
  input5: '',
  input6: '',
  input7: '',
  input8: '',
  input9: '',
  input10: '',
  input11: '',
  input12: '',
  input13: '',
  input14: '',
  input15: '',
  input16: '',
  tipoasociacion: '',
  numeroDun: '',
  estatusactual: '',
  input17: '',
  administradordesde: '',
  fechafinalizacion: ''
}

var dataSummaryPaymentsFranciaEmpty = {
  fechacalculo: '',
  periodoconsiderado: '',
  numproveedores: '',
  numerotransaccionescomerciales: '',
  importetotaltransacciones: '',
  importeretrasado: '',
  moneda: '',
  comportamientoenpagos: '',
  numerotransaccionescomerciales2: '',
  promediominimo: '',
  promediomaximo: '',
  importe: '',
  moneda2: ''
}

var dataLegalProceduresFranciaEmpty = {
  entidad: '',
  fecha: '',
  tipoaccion: '',
  claseaccion: '',
  fechapublicacion: '',
  distrito: '',
  duracion: '',
  fechafinalizacion: '',
  fechaexpiracion: '',
  importe: '',
  costeslegales: '',
  moneda: '',
  situacion: '',
  resolucion: '',
  demandante1: '',
  demandante2: '',
  comentarios: '',
  tipoaccion2: '',
  claseaccion2: '',
  fuenteinformacion: '',
  input1: '',
  input2: ''
}

var dataSummaryLegalProceduresFranciaEmpty = {
  fechaactualizacion: '',
  periodoanalizado: '',
  tipodeacccion: '',
  clasedeaccion: '',
  numeroprocedimientos1: '',
  importetotal1: '',
  importetotal2: '',
  procedimientolegal: '',
  situacionactual: '',
  numeroprocedimentos2: '',
  importetotal3: '',
  importetotal4: ''
}

var dataCommentsEmpty = {
  comentarios: '',
  titularidad: '',
  tipodelocales: '',
  superficie1: '',
  superficie2: ''
}

var dataGuaratorsEmpty = {
  tipodocumento: '',
  ndocumento: '',
  nombreavalado: '',
  entidad: '',
  calificacion: '',
  saldo: ''
}

var GeneralInformationDataFaker = {
  generalData: dataGeneralDataEmpty,
  identification: dataIdentificationEmpty,
  denominacionesComerciales: dataDenominacionesComercialesEmpty,
  summary: dataSummaryEmpty,
  specificItems: dataSpecificItemsEmpty,
  informaData: dataInformaDataEmpty,
  protestsDemands: dataProtestsDemandsEmpty,
  communications: dataCommunicationsEmpty,
  taxCodes: dataTaxCodesEmpty,
  naceSic: dataNaceSicEmpty,
  legalForm: dataLegalFormEmpty,
  basicData: dataBasicDataEmpty,
  capital: dataCapitalEmpty,
  deal: {
    cnae: dataCnaeEmpty,
    dealForm: dataDealFormEmpty,
    importsExports: dataImportsExportsEmpty,
    otherEvents: dataOtherEventsEmpty
  },
  companyAssets: dataCompanyAssetsEmpty,
  relationsShip: {
    shareHolders: dataRelationShipEmpty,
    administrators: dataAdministratorEmpty,
    subsidiaryAffiliates: dataSubsidiaryAffiliatesEmpty,
    branchOffices: dataBranchOfficesEmpty,
    banks: dataBankEmpty
  },
  payments: {
    paymentForm: dataPaymentFormEmpty,
    paydexHistoric: dataPaydexHistoricEmpty,
    paydexSectorial: dataPaydexSectorialEmpty,
    summaryPayments: dataSummaryPaymentsEmpty
  },
  legalProcedures: {
    legalProcedures: dataLegalProceduresEmpty,
    legalConfirmed: dataLegalConfirmedFaker
  },
  ratingForm: dataRatingFormFaker,
  datosHost: datosHostDataEmpty,
  aggregateSummary: dataAggregateSummaryDataEmpty,
  entityCommunication: dataEntityCommunicationDataEmpty,
  externalFinancing: dataExternalFinancingEmpty,
  legalProceduresIT: dataLegalProceduresITEmpty,
  creditResponsability: dataCreditResponsabilityDataEmpty,
  bankData: bankDataEmpty,
  paymentsLegalProcess: dataPaymentsLegalProcessEmpty,
  communicationsPOA: dataCommunicationsPOAEmpty,
  companyAssetsPOA: {
    companyAssetsPOAForm: dataCompanyAssetsEmpty,
    summaryExternalFinancing: datosSummaryExternalFinancingEmpty,
    externalFinancingPOA: dataExternalFinancingPOAEmpty,
    ajtspoa: dataAJTSPOAEmpty
  },
  identificacionEspanaInforma: dataIdentificacionEspanaInformaEmpty,
  ajtsEspanaInforma: dataAJTSEspanaInformaEmpty,
  datosInforma: dataDatosInformaEmpty,
  generalDataEUDBP: dataGeneralDataEmpty,
  companyAssetsEUDBPFR: dataCompanyAssetsEUDBFREmpty,
  score: dataScoreEmpty,
  identityVerification: dataIdentityVerificationEmpty,
  consultas: dataConsultasEmpty,
  bouncedChecks: dataBouncedChecksEmpty,
  rejectChecksLegal: dataRejectChecksLegalEmpty,
  bureauCredit: dataBureauCreditEmpty,
  judicialSourcesAlerts: dataJudicialSourcesAlertsEmpty,
  scorePeru: dataScorePeruEmpty,
  directoryNaturalPersons: dataDirectoryNaturalPersonsEmpty,
  directorySunat: dataDirectorySunatEmpty,
  lastAddresses: dataLastAddressesEmpty,
  legalAgents: dataLegalAgentsEmpty,
  regulatedNonFinancialSystem: dataRegulatedNonFinancialSystemEmpty,
  debtsLastPeriod: dataDebtsLastPeriodEmpty,
  debtHistory: dataDebtHistorySystemEmpty,
  lastPeriodDetail: dataLastPeriodDetailEmpty,
  historyPeru: dataHistoryPeruEmpty,
  microfinanceDebt: dataMicrofinanceDebtEmpty,
  informationMexico: dataGeneralInformationMexicoEmpty,
  scorepymemexico: dataScorePymeMexicoEmpty,
  generalDataFrancia: dataGeneralDataFranciaEmpty,
  documentRegistration: dataDocumentRegistrationEmpty,
  otherEventsFrancia: dataOtherEventsOneFaker,
  ajtsPOA: dataAJTSPOAEmpty,
  paydexHistoric: dataPaydexHistoricEmpty,
  paydexSectorial: dataPaydexSectorialEmpty,
  businessNameFrancia: dataBussinessNameFranciaEmpty,
  previousCompanyFrancia: dataPreviousCompanyFranciaEmpty,
  comercialDesignation: dataBussinessNameFranciaEmpty,
  previousTradeNames: dataPreviousTradeNamesEmpty,
  addressFrancia: dataAddressFranciaEmpty,
  taxCodesFrancia: dataTaxCodesFranciaEmpty,
  organizacionType: dataOrganizationTypeEmpty,
  legalFormFrancia: dataLegalFormFranciaEmpty,
  externalFinancingFrancia: dataExternalFinancingFranciaEmpty,
  summarySourcesFrancia: dataSummarySourcesFranciaEmpty,
  shareholdersFrancia: dataShareholdersFranciaEmpty,
  subsidiaryAffiliates: dataSubsidiaryAffiliatesEmpty,
  branchOffices: dataBranchOfficesEmpty,
  employessFrancia: dataEmployessFranciaEmpty,
  facilitiesDescription: dataFacilitiesDescriptionEmpty,
  banksFrancia: dataBanksFranciaEmpty,
  administratorsFrancia: dataAdministratorsFranciaEmpty,
  paymentFrancia: dataPaymentFormEmpty,
  summaryPaymentsFrancia: dataSummaryPaymentsFranciaEmpty,
  legalProceduresFrancia: dataLegalProceduresFranciaEmpty,
  summaryLegalProceduresFrancia: dataSummaryLegalProceduresFranciaEmpty,
  comments: dataCommentsEmpty,
  guarators: dataGuaratorsEmpty
}
var dataBalancesEconomicosFaker = {
  planEstado1: '',
  planEstado2: '',
  planEstado3: '',
  fechaFinEstado1: '',
  fechaFinEstado2: '',
  fechaFinEstado3: '',
  numMeses1: '',
  numMeses2: '',
  numMeses3: '',
  indAudit1: '',
  indAudit2: '',
  indAudit3: '',
  indCalifAudit1: '',
  indCalifAudit2: '',
  indCalifAudit3: '',
  ambInfo1: '',
  ambInfo2: '',
  ambInfo3: '',
  codigoFiabilidad1: '',
  codigoFiabilidad2: '',
  codigoFiabilidad3: '',
  indFinal1: '',
  indFinal2: '',
  indFinal3: '',
  indFirma1: '',
  indFirma2: '',
  indFirma3: '',
  indDeseq1: '',
  indDeseq2: '',
  indDeseq3: '',
  numEmpleado1: '',
  numEmpleado2: '',
  numEmpleado3: '',
  codDivisaFinanciero1: '',
  codDivisaFinanciero2: '',
  codDivisaFinanciero3: '',
  unidadFinanciero1: '',
  unidadFinanciero2: '',
  unidadFinanciero3: '',
  razon1: '',
  razon2: '',
  razon3: '',
  inmobilizadoNeto1: '',
  inmobilizadoNeto2: '',
  inmobilizadoNeto3: '',
  activoCirculante1: '',
  activoCirculante2: '',
  activoCirculante3: '',
  fondosPropios1: '',
  fondosPropios2: '',
  fondosPropios3: '',
  capital1: '',
  capital2: '',
  capital3: '',
  acreeLargoPlazo1: '',
  acreeLargoPlazo2: '',
  acreeLargoPlazo3: '',
  acreeCortoPlazo1: '',
  acreeCortoPlazo2: '',
  acreeCortoPlazo3: '',
  totDeudas1: '',
  totDeudas2: '',
  totDeudas3: '',
  totActivoPasivo1: '',
  totActivoPasivo2: '',
  totActivoPasivo3: '',
  calProduccion1: '',
  calProduccion2: '',
  calProduccion3: '',
  ventasNetas1: '',
  ventasNetas2: '',
  ventasNetas3: '',
  netoExplotacion1: '',
  netoExplotacion2: '',
  netoExplotacion3: '',
  activOrdinarias1: '',
  activOrdinarias2: '',
  activOrdinarias3: '',
  perdidas1: '',
  perdidas2: '',
  perdidas3: '',
  beneficios1: '',
  beneficios2: '',
  beneficios3: ''
}

var dataRatiosActivoFaker = {
  accNoExi1: '',
  accNoExi2: '',
  accNoExi3: '',
  inmoNeto1: '',
  inmoNeto2: '',
  inmoNeto3: '',
  gastoEstabl1: '',
  gastoEstabl2: '',
  gastoEstabl3: '',
  invDesarrollo1: '',
  invDesarrollo2: '',
  invDesarrollo3: '',
  patentes1: '',
  patentes2: '',
  patentes3: '',
  fondoComertio1: '',
  fondoComertio2: '',
  fondoComertio3: '',
  otroInmoInma1: '',
  otroInmoInma2: '',
  otroInmoInma3: '',
  bienesArren1: '',
  bienesArren2: '',
  bienesArren3: '',
  amorInmoMat1: '',
  amorInmoMat2: '',
  amorInmoMat3: '',
  totInmoInmat1: '',
  totInmoInmat2: '',
  totInmoInmat3: '',
  terrenos1: '',
  terrenos2: '',
  terrenos3: '',
  construcciones1: '',
  construcciones2: '',
  construcciones3: '',
  terrConstrucciones1: '',
  terrConstrucciones2: '',
  terrConstrucciones3: '',
  maqHerra1: '',
  maqHerra2: '',
  maqHerra3: '',
  instTecnicas1: '',
  instTecnicas2: '',
  instTecnicas3: '',
  moviliario1: '',
  moviliario2: '',
  moviliario3: '',
  inmoEnCurso1: '',
  inmoEnCurso2: '',
  inmoEnCurso3: '',
  otroInmoMaterial1: '',
  otroInmoMaterial2: '',
  otroInmoMaterial3: '',
  inmoNoOpe1: '',
  inmoNoOpe2: '',
  inmoNoOpe3: '',
  totInmoMat1: '',
  totInmoMat2: '',
  totInmoMat3: '',
  empGrupo1: '',
  empGrupo2: '',
  empGrupo3: '',
  empAsociada1: '',
  empAsociada2: '',
  empAsociada3: '',
  acciones1: '',
  acciones2: '',
  acciones3: '',
  depositos1: '',
  depositos2: '',
  depositos3: '',
  otrosDepositos1: '',
  otrosDepositos2: '',
  otrosDepositos3: '',
  creditoLargoPlazo1: '',
  creditoLargoPlazo2: '',
  creditoLargoPlazo3: '',
  creditoAsociados1: '',
  creditoAsociados2: '',
  creditoAsociados3: '',
  creditosGrupo1: '',
  creditosGrupo2: '',
  creditosGrupo3: '',
  otroInmoFinanciero1: '',
  otroInmoFinanciero2: '',
  otroInmoFinanciero3: '',
  inmoOtros1: '',
  inmoOtros2: '',
  inmoOtros3: '',
  totInmoFinanciero1: '',
  totInmoFinanciero2: '',
  totInmoFinanciero3: '',
  amortizacion1: '',
  amortizacion2: '',
  amortizacion3: '',
  otroInmoLargoPlazo1: '',
  otroInmoLargoPlazo2: '',
  otroInmoLargoPlazo3: '',
  gastosDistribuir1: '',
  gastosDistribuir2: '',
  gastosDistribuir3: '',
  ratioActivoCirculante1: '',
  ratioActivoCirculante2: '',
  ratioActivoCirculante3: '',
  existenciasNetas1: '',
  existenciasNetas2: '',
  existenciasNetas3: '',
  materiasPrimas1: '',
  materiasPrimas2: '',
  materiasPrimas3: '',
  productoCurso1: '',
  productoCurso2: '',
  productoCurso3: '',
  productoTerminado1: '',
  productoTerminado2: '',
  productoTerminado3: '',
  mercaderias1: '',
  mercaderias2: '',
  mercaderias3: '',
  existencias1: '',
  existencias2: '',
  existencias3: '',
  contratos1: '',
  contratos2: '',
  contratos3: '',
  inmiuebles1: '',
  inmiuebles2: '',
  inmiuebles3: '',
  anticipos1: '',
  anticipos2: '',
  anticipos3: '',
  provExistencias1: '',
  provExistencias2: '',
  provExistencias3: '',
  realizable1: '',
  realizable2: '',
  realizable3: '',
  clientes1: '',
  clientes2: '',
  clientes3: '',
  otrosDeudores1: '',
  otrosDeudores2: '',
  otrosDeudores3: '',
  deudoresEspeciales1: '',
  deudoresEspeciales2: '',
  deudoresEspeciales3: '',
  provTrafico1: '',
  provTrafico2: '',
  provTrafico3: '',
  deudasGrupo1: '',
  deudasGrupo2: '',
  deudasGrupo3: '',
  deudasAsociados1: '',
  deudasAsociados2: '',
  deudasAsociados3: '',
  otrosActCirculantes1: '',
  otrosActCirculantes2: '',
  otrosActCirculantes3: '',
  admiPubnlicas1: '',
  admiPubnlicas2: '',
  admiPubnlicas3: '',
  acumulaciones1: '',
  acumulaciones2: '',
  acumulaciones3: '',
  capitalDesem1: '',
  capitalDesem2: '',
  capitalDesem3: '',
  gastosAnticipados1: '',
  gastosAnticipados2: '',
  gastosAnticipados3: '',
  invFinancierasTemp1: '',
  invFinancierasTemp2: '',
  invFinancierasTemp3: '',
  otrasInvFinancierasCPlazo1: '',
  otrasInvFinancierasCPlazo2: '',
  otrasInvFinancierasCPlazo3: '',
  otrosCreditos1: '',
  otrosCreditos2: '',
  otrosCreditos3: '',
  carteraCortoPlazo1: '',
  carteraCortoPlazo2: '',
  carteraCortoPlazo3: '',
  participaciones1: '',
  participaciones2: '',
  participaciones3: '',
  accionesPropias1: '',
  accionesPropias2: '',
  accionesPropias3: '',
  tesoreria1: '',
  tesoreria2: '',
  tesoreria3: '',
  caja1: '',
  caja2: '',
  caja3: '',
  bancos1: '',
  bancos2: '',
  bancos3: '',
  totActiv1: '',
  totActiv2: '',
  totActiv3: ''
}

var dataRatiosPasivoRequestForm = {
  ratiosFondosPropios1: '',
  ratiosFondosPropios2: '',
  ratiosFondosPropios3: '',
  totCapital1: '',
  totCapital2: '',
  totCapital3: '',
  ratiosCapital1: '',
  ratiosCapital2: '',
  ratiosCapital3: '',
  accionesPref1: '',
  accionesPref2: '',
  accionesPref3: '',
  capitalEmitido1: '',
  capitalEmitido2: '',
  capitalEmitido3: '',
  capitalDesembolsado1: '',
  capitalDesembolsado2: '',
  capitalDesembolsado3: '',
  primaEmision1: '',
  primaEmision2: '',
  primaEmision3: '',
  totReservas1: '',
  totReservas2: '',
  totReservas3: '',
  reservas1: '',
  reservas2: '',
  reservas3: '',
  exceCapital1: '',
  exceCapital2: '',
  exceCapital3: '',
  reservaLegal1: '',
  reservaLegal2: '',
  reservaLegal3: '',
  reservaNoDisp1: '',
  reservaNoDisp2: '',
  reservaNoDisp3: '',
  reservaVolunt1: '',
  reservaVolunt2: '',
  reservaVolunt3: '',
  reservaAccionesPropias1: '',
  reservaAccionesPropias2: '',
  reservaAccionesPropias3: '',
  reservasEstatutarias1: '',
  reservasEstatutarias2: '',
  reservasEstatutarias3: '',
  reservasDisponibles1: '',
  reservasDisponibles2: '',
  reservasDisponibles3: '',
  otrasReservas1: '',
  otrasReservas2: '',
  otrasReservas3: '',
  reservasRevalorizacion1: '',
  reservasRevalorizacion2: '',
  reservasRevalorizacion3: '',
  acumulada1: '',
  acumulada2: '',
  acumulada3: '',
  beneficioEjerAnt1: '',
  beneficioEjerAnt2: '',
  beneficioEjerAnt3: '',
  perdidasEjerAnt1: '',
  perdidasEjerAnt2: '',
  perdidasEjerAnt3: '',
  noDistribuido1: '',
  noDistribuido2: '',
  noDistribuido3: '',
  beneficiosNoDistribuido1: '',
  beneficiosNoDistribuido2: '',
  beneficiosNoDistribuido3: '',
  perdidasGanancias1: '',
  perdidasGanancias2: '',
  perdidasGanancias3: '',
  perdidasEjer1: '',
  perdidasEjer2: '',
  perdidasEjer3: '',
  beneficiosEjer1: '',
  beneficiosEjer2: '',
  beneficiosEjer3: '',
  dividendoEjer1: '',
  dividendoEjer2: '',
  dividendoEjer3: '',
  provReservas1: '',
  provReservas2: '',
  provReservas3: '',
  interesMinoritario1: '',
  interesMinoritario2: '',
  interesMinoritario3: '',
  ingresosVariosEjer1: '',
  ingresosVariosEjer2: '',
  ingresosVariosEjer3: '',
  subvencionesCapital1: '',
  subvencionesCapital2: '',
  subvencionesCapital3: '',
  riesgosGastos1: '',
  riesgosGastos2: '',
  riesgosGastos3: '',
  provRiesgosGastos1: '',
  provRiesgosGastos2: '',
  provRiesgosGastos3: '',
  provPensiones1: '',
  provPensiones2: '',
  provPensiones3: '',
  provImpuesto1: '',
  provImpuesto2: '',
  provImpuesto3: '',
  otrasProv1: '',
  otrasProv2: '',
  otrasProv3: '',
  provCompras1: '',
  provCompras2: '',
  provCompras3: '',
  deprecInmo1: '',
  deprecInmo2: '',
  deprecInmo3: '',
  deprecIntangible1: '',
  deprecIntangible2: '',
  deprecIntangible3: '',
  provDeprecExistencias1: '',
  provDeprecExistencias2: '',
  provDeprecExistencias3: '',
  creditosIncobrables1: '',
  creditosIncobrables2: '',
  creditosIncobrables3: '',
  deprecInmovilizado1: '',
  deprecInmovilizado2: '',
  deprecInmovilizado3: '',
  cuentaRegularizacion1: '',
  cuentaRegularizacion2: '',
  cuentaRegularizacion3: '',
  cuentaCompensacion1: '',
  cuentaCompensacion2: '',
  cuentaCompensacion3: '',
  acreedLargoPlazo1: '',
  acreedLargoPlazo2: '',
  acreedLargoPlazo3: '',
  deudasComerciales1: '',
  deudasComerciales2: '',
  deudasComerciales3: '',
  acreedoresComerciales1: '',
  acreedoresComerciales2: '',
  acreedoresComerciales3: '',
  otrosAcreedores1: '',
  otrosAcreedores2: '',
  otrosAcreedores3: '',
  deudasRepresentadas1: '',
  deudasRepresentadas2: '',
  deudasRepresentadas3: '',
  ventasPlazo1: '',
  ventasPlazo2: '',
  ventasPlazo3: '',
  deudasEmpGrupo1: '',
  deudasEmpGrupo2: '',
  deudasEmpGrupo3: '',
  acreedoresGrupo1: '',
  acreedoresGrupo2: '',
  acreedoresGrupo3: '',
  acreedoresAsociados1: '',
  acreedoresAsociados2: '',
  acreedoresAsociados3: '',
  deudasFinancieras1: '',
  deudasFinancieras2: '',
  deudasFinancieras3: '',
  obligacionesConvertibles1: '',
  obligacionesConvertibles2: '',
  obligacionesConvertibles3: '',
  obligacionesSimilares1: '',
  obligacionesSimilares2: '',
  obligacionesSimilares3: '',
  hipotecasPrestamos1: '',
  hipotecasPrestamos2: '',
  hipotecasPrestamos3: '',
  otrasDeudasNoComer1: '',
  otrasDeudasNoComer2: '',
  otrasDeudasNoComer3: '',
  impuestosSeguridadSocial1: '',
  impuestosSeguridadSocial2: '',
  impuestosSeguridadSocial3: '',
  deudasPensiones1: '',
  deudasPensiones2: '',
  deudasPensiones3: '',
  cobrosAnticipados1: '',
  cobrosAnticipados2: '',
  cobrosAnticipados3: '',
  acreedoresCortoPlazo1: '',
  acreedoresCortoPlazo2: '',
  acreedoresCortoPlazo3: '',
  deudasComercialesBis1: '',
  deudasComercialesBis2: '',
  deudasComercialesBis3: '',
  cuentasPagar1: '',
  cuentasPagar2: '',
  cuentasPagar3: '',
  proveedorCP1: '',
  proveedorCP2: '',
  proveedorCP3: '',
  otrosAcreedoresCom1: '',
  otrosAcreedoresCom2: '',
  otrosAcreedoresCom3: '',
  deudasRepreAPagar1: '',
  deudasRepreAPagar2: '',
  deudasRepreAPagar3: '',
  ventaPlazos1: '',
  ventaPlazos2: '',
  ventaPlazos3: '',
  deudasEmpGrupoAsoc1: '',
  deudasEmpGrupoAsoc2: '',
  deudasEmpGrupoAsoc3: '',
  acreedoresEGrupo1: '',
  acreedoresEGrupo2: '',
  acreedoresEGrupo3: '',
  prestamosAdmin1: '',
  prestamosAdmin2: '',
  prestamosAdmin3: '',
  acreedoresEAsoc1: '',
  acreedoresEAsoc2: '',
  acreedoresEAsoc3: '',
  deudasFinancierasBis1: '',
  deudasFinancierasBis2: '',
  deudasFinancierasBis3: '',
  deudasFinancierasLower1: '',
  deudasFinancierasLower2: '',
  deudasFinancierasLower3: '',
  pertamosBancarios1: '',
  pertamosBancarios2: '',
  pertamosBancarios3: '',
  parteCorrienteDeuda1: '',
  parteCorrienteDeuda2: '',
  parteCorrienteDeuda3: '',
  otrosPrestamos1: '',
  otrosPrestamos2: '',
  otrosPrestamos3: '',
  deudasValoresNegociables1: '',
  deudasValoresNegociables2: '',
  deudasValoresNegociables3: '',
  otrosPrestamosCP1: '',
  otrosPrestamosCP2: '',
  otrosPrestamosCP3: '',
  otrasDeudasNoComerciales1: '',
  otrasDeudasNoComerciales2: '',
  otrasDeudasNoComerciales3: '',
  cuentasGenerales1: '',
  cuentasGenerales2: '',
  cuentasGenerales3: '',
  otrasDeudas1: '',
  otrasDeudas2: '',
  otrasDeudas3: '',
  deudasInmovilizado1: '',
  deudasInmovilizado2: '',
  deudasInmovilizado3: '',
  impuestosSegSocial1: '',
  impuestosSegSocial2: '',
  impuestosSegSocial3: '',
  impuestos1: '',
  impuestos2: '',
  impuestos3: '',
  salariosSegSocial1: '',
  salariosSegSocial2: '',
  salariosSegSocial3: '',
  dividendo1: '',
  dividendo2: '',
  dividendo3: '',
  declaradoAnticipado1: '',
  declaradoAnticipado2: '',
  declaradoAnticipado3: '',
  cobroAnticipado1: '',
  cobroAnticipado2: '',
  cobroAnticipado3: '',
  acreedoresEspeciales1: '',
  acreedoresEspeciales2: '',
  acreedoresEspeciales3: '',
  ingresosDiferidos1: '',
  ingresosDiferidos2: '',
  ingresosDiferidos3: '',
  totAcreedores1: '',
  totAcreedores2: '',
  totAcreedores3: '',
  totPasivo1: '',
  totPasivo2: '',
  totPasivo3: ''
}

var dataRatiosInformationFaker = {
  activo: dataRatiosActivoFaker,
  pasivo: dataRatiosPasivoRequestForm
}

var dataCuentasResultadoFaker = {
  ventasNetas1: '',
  ventasNetas2: '',
  ventasNetas3: '',
  variacionExistencias1: '',
  variacionExistencias2: '',
  variacionExistencias3: '',
  trabajosInmovilizado1: '',
  trabajosInmovilizado2: '',
  trabajosInmovilizado3: '',
  otrosIngresos1: '',
  otrosIngresos2: '',
  otrosIngresos3: '',
  valorProducción1: '',
  valorProducción2: '',
  valorProducción3: '',
  aprovisionamientos1: '',
  aprovisionamientos2: '',
  aprovisionamientos3: '',
  materiasPrimas1: '',
  materiasPrimas2: '',
  materiasPrimas3: '',
  subcontragos1: '',
  subcontragos2: '',
  subcontragos3: '',
  brutoExplotación1: '',
  brutoExplotación2: '',
  brutoExplotación3: '',
  gastosOperativos1: '',
  gastosOperativos2: '',
  gastosOperativos3: '',
  dotaciónInmovilizado1: '',
  dotaciónInmovilizado2: '',
  dotaciónInmovilizado3: '',
  provTrafico1: '',
  provTrafico2: '',
  provTrafico3: '',
  otrosGastos1: '',
  otrosGastos2: '',
  otrosGastos3: '',
  costesReorganiczacion1: '',
  costesReorganiczacion2: '',
  costesReorganiczacion3: '',
  netoExplotación1: '',
  netoExplotación2: '',
  netoExplotación3: '',
  gastosFinancieros1: '',
  gastosFinancieros2: '',
  gastosFinancieros3: '',
  interesesSimilares1: '',
  interesesSimilares2: '',
  interesesSimilares3: '',
  perdidasInversiones1: '',
  perdidasInversiones2: '',
  perdidasInversiones3: '',
  otrosGastosFinancieros1: '',
  otrosGastosFinancieros2: '',
  otrosGastosFinancieros3: '',
  ingresosFinancieros1: '',
  ingresosFinancieros2: '',
  ingresosFinancieros3: '',
  ingresosInmoFinanciero1: '',
  ingresosInmoFinanciero2: '',
  ingresosInmoFinanciero3: '',
  ingresosGrupo1: '',
  ingresosGrupo2: '',
  ingresosGrupo3: '',
  ingresosInversores1: '',
  ingresosInversores2: '',
  ingresosInversores3: '',
  ordinario1: '',
  ordinario2: '',
  ordinario3: '',
  impuestos1: '',
  impuestos2: '',
  impuestos3: '',
  impuestosAntex1: '',
  impuestosAntex2: '',
  impuestosAntex3: '',
  ingresosExtraordinarios1: '',
  ingresosExtraordinarios2: '',
  ingresosExtraordinarios3: '',
  gastosExtraordinarios1: '',
  gastosExtraordinarios2: '',
  gastosExtraordinarios3: '',
  extraordinarios1: '',
  extraordinarios2: '',
  extraordinarios3: '',
  impuestoExtraordinarios1: '',
  impuestoExtraordinarios2: '',
  impuestoExtraordinarios3: '',
  beneficios1: '',
  beneficios2: '',
  beneficios3: '',
  participacionAccionistas1: '',
  participacionAccionistas2: '',
  participacionAccionistas3: '',
  participacionEmpleados1: '',
  participacionEmpleados2: '',
  participacionEmpleados3: '',
  ajusteIngresos1: '',
  ajusteIngresos2: '',
  ajusteIngresos3: '',
  tercerasPartes1: '',
  tercerasPartes2: '',
  tercerasPartes3: '',
  beneficioNeto1: '',
  beneficioNeto2: '',
  beneficioNeto3: '',
  perdidasNetas1: '',
  perdidasNetas2: '',
  perdidasNetas3: '',
  exportaciones1: '',
  exportaciones2: '',
  exportaciones3: '',
  distribIniciales1: '',
  distribIniciales2: '',
  distribIniciales3: '',
  ingresosNetos1: '',
  ingresosNetos2: '',
  ingresosNetos3: '',
  otrasAcciones1: '',
  otrasAcciones2: '',
  otrasAcciones3: '',
  perdidasNetasBis1: '',
  perdidasNetasBis2: '',
  perdidasNetasBis3: '',
  dividendos1: '',
  dividendos2: '',
  dividendos3: '',
  retenciones1: '',
  retenciones2: '',
  retenciones3: '',
  otrasDeducciones1: '',
  otrasDeducciones2: '',
  otrasDeducciones3: '',
  beneficiosDistribuidos1: '',
  beneficiosDistribuidos2: '',
  beneficiosDistribuidos3: '',
  salariosDirectores1: '',
  salariosDirectores2: '',
  salariosDirectores3: ''
}

var dataBalancesEconomicosFakerBis = {
  planEstado1: '',
  planEstado2: '',
  planEstado3: '',
  fechaFinEstado1: '',
  fechaFinEstado2: '',
  fechaFinEstado3: '',
  numMeses1: '',
  numMeses2: '',
  numMeses3: '',
  indAudit1: '',
  indAudit2: '',
  indAudit3: '',
  indCalifAudit1: '',
  indCalifAudit2: '',
  indCalifAudit3: '',
  ambInfo1: '',
  ambInfo2: '',
  ambInfo3: '',
  codigoFiabilidad1: '',
  codigoFiabilidad2: '',
  codigoFiabilidad3: '',
  indFinal1: '',
  indFinal2: '',
  indFinal3: '',
  indFirma1: '',
  indFirma2: '',
  indFirma3: '',
  indDeseq1: '',
  indDeseq2: '',
  indDeseq3: '',
  numEmpleado1: '',
  numEmpleado2: '',
  numEmpleado3: '',
  codDivisaFinanciero1: '',
  codDivisaFinanciero2: '',
  codDivisaFinanciero3: '',
  unidadFinanciero1: '',
  unidadFinanciero2: '',
  unidadFinanciero3: '',
  razon1: '',
  razon2: '',
  razon3: '',
  inmobilizadoNeto1: '',
  inmobilizadoNeto2: '',
  inmobilizadoNeto3: '',
  activoCirculante1: '',
  activoCirculante2: '',
  activoCirculante3: '',
  fondosPropios1: '',
  fondosPropios2: '',
  fondosPropios3: '',
  capital1: '',
  capital2: '',
  capital3: '',
  acreeLargoPlazo1: '',
  acreeLargoPlazo2: '',
  acreeLargoPlazo3: '',
  acreeCortoPlazo1: '',
  acreeCortoPlazo2: '',
  acreeCortoPlazo3: '',
  totDeudas1: '',
  totDeudas2: '',
  totDeudas3: '',
  totActivoPasivo1: '',
  totActivoPasivo2: '',
  totActivoPasivo3: '',
  calProduccion1: '',
  calProduccion2: '',
  calProduccion3: '',
  ventasNetas1: '',
  ventasNetas2: '',
  ventasNetas3: '',
  netoExplotacion1: '',
  netoExplotacion2: '',
  netoExplotacion3: '',
  activOrdinarias1: '',
  activOrdinarias2: '',
  activOrdinarias3: '',
  perdidas1: '',
  perdidas2: '',
  perdidas3: '',
  beneficios1: '',
  beneficios2: '',
  beneficios3: ''
}

var dataRatiosActivoBisRequestFormFaker = {
  capital1: '',
  capital2: '',
  capital3: '',
  activoFijo1: '',
  activoFijo2: '',
  activoFijo3: '',
  inmovilizadoIntangible1: '',
  inmovilizadoIntangible2: '',
  inmovilizadoIntangible3: '',
  inmovilizadoIntangible_11: '',
  inmovilizadoIntangible_12: '',
  inmovilizadoIntangible_13: '',
  inmovilizadoIntangible_21: '',
  inmovilizadoIntangible_22: '',
  inmovilizadoIntangible_23: '',
  inmovilizadoIntangible_31: '',
  inmovilizadoIntangible_32: '',
  inmovilizadoIntangible_33: '',
  inmovilizadoIntangible_41: '',
  inmovilizadoIntangible_42: '',
  inmovilizadoIntangible_43: '',
  inmovilizadoIntangible_51: '',
  inmovilizadoIntangible_52: '',
  inmovilizadoIntangible_53: '',
  inmovilizadoIntangible_61: '',
  inmovilizadoIntangible_62: '',
  inmovilizadoIntangible_63: '',
  inmovilizadoMaterial1: '',
  inmovilizadoMaterial2: '',
  inmovilizadoMaterial3: '',
  inmovilizadoMaterial_11: '',
  inmovilizadoMaterial_12: '',
  inmovilizadoMaterial_13: '',
  inmovilizadoMaterial_21: '',
  inmovilizadoMaterial_22: '',
  inmovilizadoMaterial_23: '',
  inmovilizadoMaterial_31: '',
  inmovilizadoMaterial_32: '',
  inmovilizadoMaterial_33: '',
  inmovilizadoMaterial_41: '',
  inmovilizadoMaterial_42: '',
  inmovilizadoMaterial_43: '',
  inmovilizadoMaterial_51: '',
  inmovilizadoMaterial_52: '',
  inmovilizadoMaterial_53: '',
  inmovilizadoMaterial_61: '',
  inmovilizadoMaterial_62: '',
  inmovilizadoMaterial_63: '',
  inmovilizadoFinanciero1: '',
  inmovilizadoFinanciero2: '',
  inmovilizadoFinanciero3: '',
  inmovilizadoFinanciero_11: '',
  inmovilizadoFinanciero_12: '',
  inmovilizadoFinanciero_13: '',
  inmovilizadoFinanciero_21: '',
  inmovilizadoFinanciero_22: '',
  inmovilizadoFinanciero_23: '',
  inmovilizadoFinanciero_31: '',
  inmovilizadoFinanciero_32: '',
  inmovilizadoFinanciero_33: '',
  inmovilizadoFinanciero_41: '',
  inmovilizadoFinanciero_42: '',
  inmovilizadoFinanciero_43: '',
  inmovilizadoFinanciero_51: '',
  inmovilizadoFinanciero_52: '',
  inmovilizadoFinanciero_53: '',
  inmovilizadoFinanciero_61: '',
  inmovilizadoFinanciero_62: '',
  inmovilizadoFinanciero_63: '',
  activoCirculante1: '',
  activoCirculante2: '',
  activoCirculante3: '',
  existencias1: '',
  existencias2: '',
  existencias3: '',
  existencias_11: '',
  existencias_12: '',
  existencias_13: '',
  existencias_21: '',
  existencias_22: '',
  existencias_23: '',
  existencias_31: '',
  existencias_32: '',
  existencias_33: '',
  existencias_41: '',
  existencias_42: '',
  existencias_43: '',
  existencias_51: '',
  existencias_52: '',
  existencias_53: '',
  anticipos1: '',
  anticipos2: '',
  anticipos3: '',
  deudores1: '',
  deudores2: '',
  deudores3: '',
  deudores_11: '',
  deudores_12: '',
  deudores_13: '',
  deudores_21: '',
  deudores_22: '',
  deudores_23: '',
  deudores_31: '',
  deudores_32: '',
  deudores_33: '',
  varios1: '',
  varios2: '',
  varios3: '',
  varios_11: '',
  varios_12: '',
  varios_13: '',
  varios_21: '',
  varios_22: '',
  varios_23: '',
  otros1: '',
  otros2: '',
  otros3: '',
  otros_11: '',
  otros_12: '',
  otros_13: '',
  otros_21: '',
  otros_22: '',
  otros_23: '',
  otros_31: '',
  otros_32: '',
  otros_33: '',
  otros_41: '',
  otros_42: '',
  otros_43: '',
  totalActivo1: '',
  totalActivo2: '',
  totalActivo3: '',
  otrasCuentas1: '',
  otrasCuentas2: '',
  otrasCuentas3: '',
  totalCuentas1: '',
  totalCuentas2: '',
  totalCuentas3: '',
  prestamosFamiliares1: '',
  prestamosFamiliares2: '',
  prestamosFamiliares3: ''
}

var dataRatiosPasivoBisRequestFormFaker = {
  patrimonio1: '',
  patrimonio2: '',
  patrimonio3: '',
  fondosPropios1: '',
  fondosPropios2: '',
  fondosPropios3: '',
  fondosPropios_11: '',
  fondosPropios_12: '',
  fondosPropios_13: '',
  fondosPropios_21: '',
  fondosPropios_22: '',
  fondosPropios_23: '',
  fondosPropios_31: '',
  fondosPropios_32: '',
  fondosPropios_33: '',
  fondosPropios_41: '',
  fondosPropios_42: '',
  fondosPropios_43: '',
  fondosPropios_51: '',
  fondosPropios_52: '',
  fondosPropios_53: '',
  fondosPropios_61: '',
  fondosPropios_62: '',
  fondosPropios_63: '',
  fondosPropios_71: '',
  fondosPropios_72: '',
  fondosPropios_73: '',
  fondosPropios_81: '',
  fondosPropios_82: '',
  fondosPropios_83: '',
  fondosPropios_91: '',
  fondosPropios_92: '',
  fondosPropios_93: '',
  fondosPropios_101: '',
  fondosPropios_102: '',
  fondosPropios_103: '',
  fondosPropios_111: '',
  fondosPropios_112: '',
  fondosPropios_113: '',
  otrosFondos1: '',
  otrosFondos2: '',
  otrosFondos3: '',
  otrosFondos_11: '',
  otrosFondos_12: '',
  otrosFondos_13: '',
  otrosFondos_21: '',
  otrosFondos_22: '',
  otrosFondos_23: '',
  proviciones1: '',
  proviciones2: '',
  proviciones3: '',
  proviciones_11: '',
  proviciones_12: '',
  proviciones_13: '',
  proviciones_21: '',
  proviciones_22: '',
  proviciones_23: '',
  totalDeudas1: '',
  totalDeudas2: '',
  totalDeudas3: '',
  totalDeudas_11: '',
  totalDeudas_12: '',
  totalDeudas_13: '',
  totalDeudas_21: '',
  totalDeudas_22: '',
  totalDeudas_23: '',
  totalDeudas_31: '',
  totalDeudas_32: '',
  totalDeudas_33: '',
  totalDeudas_41: '',
  totalDeudas_42: '',
  totalDeudas_43: '',
  totalDeudas_51: '',
  totalDeudas_52: '',
  totalDeudas_53: '',
  totalDeudas_61: '',
  totalDeudas_62: '',
  totalDeudas_63: '',
  totalDeudas_71: '',
  totalDeudas_72: '',
  totalDeudas_73: '',
  totalDeudas_81: '',
  totalDeudas_82: '',
  totalDeudas_83: '',
  totalDeudas_91: '',
  totalDeudas_92: '',
  totalDeudas_93: '',
  cuentasRegulacion1: '',
  cuentasRegulacion2: '',
  cuentasRegulacion3: '',
  cuentasRegulacion_101: '',
  cuentasRegulacion_102: '',
  cuentasRegulacion_103: '',
  cuentasPasivo1: '',
  cuentasPasivo2: '',
  cuentasPasivo3: '',
  totalPasivo1: '',
  totalPasivo2: '',
  totalPasivo3: '',
  referencias1: '',
  referencias2: '',
  referencias3: '',
  referencias_11: '',
  referencias_12: '',
  referencias_13: '',
  referencias_21: '',
  referencias_22: '',
  referencias_23: '',
  referencias_31: '',
  referencias_32: '',
  referencias_33: '',
  referencias_41: '',
  referencias_42: '',
  referencias_43: '',
  referencias_51: '',
  referencias_52: '',
  referencias_53: '',
  referencias_61: '',
  referencias_62: '',
  referencias_63: '',
  referencias_71: '',
  referencias_72: '',
  referencias_73: '',
  otrasCuentas1: '',
  otrasCuentas2: '',
  otrasCuentas3: '',
  otrasCuentas_11: '',
  otrasCuentas_12: '',
  otrasCuentas_13: '',
  otrasCuentas_21: '',
  otrasCuentas_22: '',
  otrasCuentas_23: '',
  otrasCuentas_31: '',
  otrasCuentas_32: '',
  otrasCuentas_33: '',
  pasivoCirculante1: '',
  pasivoCirculante2: '',
  pasivoCirculante3: '',
  totalDeudasCortoPlazo1: '',
  totalDeudasCortoPlazo2: '',
  totalDeudasCortoPlazo3: ''
}

var dataratiosInformacionBis = {
  activo: dataRatiosActivoBisRequestFormFaker,
  pasivo: dataRatiosPasivoBisRequestFormFaker
}

var dataCuentasResultadosBisRequestFormFaker = {
  ventasMercancias1: '',
  ventasMercancias2: '',
  ventasMercancias3: '',
  ventasBienes1: '',
  ventasBienes2: '',
  ventasBienes3: '',
  prestacionServicio1: '',
  prestacionServicio2: '',
  prestacionServicio3: '',
  prestacionServicio_11: '',
  prestacionServicio_12: '',
  prestacionServicio_13: '',
  prestacionServicio_21: '',
  prestacionServicio_22: '',
  prestacionServicio_23: '',
  prestacionServicio_31: '',
  prestacionServicio_32: '',
  prestacionServicio_33: '',
  prestacionServicio_41: '',
  prestacionServicio_42: '',
  prestacionServicio_43: '',
  prestacionServicio_51: '',
  prestacionServicio_52: '',
  prestacionServicio_53: '',
  prestacionServicio_61: '',
  prestacionServicio_62: '',
  prestacionServicio_63: '',
  totalIngresos1: '',
  totalIngresos2: '',
  totalIngresos3: '',
  totalIngresos_11: '',
  totalIngresos_12: '',
  totalIngresos_13: '',
  totalIngresos_21: '',
  totalIngresos_22: '',
  totalIngresos_23: '',
  totalIngresos_31: '',
  totalIngresos_32: '',
  totalIngresos_33: '',
  totalIngresos_41: '',
  totalIngresos_42: '',
  totalIngresos_43: '',
  totalIngresos_51: '',
  totalIngresos_52: '',
  totalIngresos_53: '',
  totalIngresos_61: '',
  totalIngresos_62: '',
  totalIngresos_63: '',
  totalIngresos_71: '',
  totalIngresos_72: '',
  totalIngresos_73: '',
  totalIngresos_81: '',
  totalIngresos_82: '',
  totalIngresos_83: '',
  dotaciones1: '',
  dotaciones2: '',
  dotaciones3: '',
  totalIngresos_91: '',
  totalIngresos_92: '',
  totalIngresos_93: '',
  totalIngresos_101: '',
  totalIngresos_102: '',
  totalIngresos_103: '',
  totalIngresos_111: '',
  totalIngresos_131: '',
  totalIngresos_132: '',
  totalIngresos_133: '',
  totalExplotacion1: '',
  totalExplotacion2: '',
  totalExplotacion3: '',
  totalExplotacion_11: '',
  totalExplotacion_12: '',
  totalExplotacion_13: '',
  beneficio1: '',
  beneficio2: '',
  beneficio3: '',
  resultado1: '',
  resultado2: '',
  resultado3: '',
  resultado_11: '',
  resultado_12: '',
  resultado_13: '',
  resultado_21: '',
  resultado_22: '',
  resultado_23: '',
  resultado_31: '',
  resultado_32: '',
  resultado_33: '',
  resultado_41: '',
  resultado_42: '',
  resultado_43: '',
  resultado_51: '',
  resultado_52: '',
  resultado_53: '',
  resultado_61: '',
  resultado_62: '',
  resultado_63: '',
  totalIngresoFinanciero1: '',
  totalIngresoFinanciero2: '',
  totalIngresoFinanciero3: '',
  totalIngreso_11: '',
  totalIngreso_12: '',
  totalIngreso_13: '',
  totalIngreso_21: '',
  totalIngreso_22: '',
  totalIngreso_23: '',
  totalIngreso_31: '',
  totalIngreso_32: '',
  totalIngreso_33: '',
  totalIngreso_41: '',
  totalIngreso_42: '',
  totalIngreso_43: '',
  totalGastoFinanciero1: '',
  totalGastoFinanciero2: '',
  totalGastoFinanciero3: '',
  resultadoFinanciero1: '',
  resultadoFinanciero2: '',
  resultadoFinanciero3: '',
  resultadoOrdinario1: '',
  resultadoOrdinario2: '',
  resultadoOrdinario3: '',
  ingresoExcep_11: '',
  ingresoExcep_12: '',
  ingresoExcep_13: '',
  ingresoExcep_21: '',
  ingresoExcep_22: '',
  ingresoExcep_23: '',
  ingresoExcep_31: '',
  ingresoExcep_32: '',
  ingresoExcep_33: '',
  totalIngresoExtra1: '',
  totalIngresoExtra2: '',
  totalIngresoExtra3: '',
  totalIngresoExtra_11: '',
  totalIngresoExtra_12: '',
  totalIngresoExtra_13: '',
  totalIngresoExtra_21: '',
  totalIngresoExtra_22: '',
  totalIngresoExtra_23: '',
  t7otalIngresoExtra_31: '',
  totalIngresoExtra_32: '',
  totalIngresoExtra_33: '',
  totalGastoExtra_h1: '',
  totalGastoExtra_h2: '',
  totalGastoExtra_h3: '',
  totalGastoExtra_41: '',
  totalGastoExtra_42: '',
  totalGastoExtra_43: '',
  totalGastoExtra_411: '',
  totalGastoExtra_412: '',
  totalGastoExtra_413: '',
  totalGastoExtra_421: '',
  totalGastoExtra_422: '',
  totalGastoExtra_423: '',
  totalIngreso1: '',
  totalIngreso2: '',
  totalIngreso3: '',
  totalGasto1: '',
  totalGasto2: '',
  totalGasto3: '',
  resultadoEjercicio1: '',
  resultadoEjercicio2: '',
  resultadoEjercicio3: '',
  otrasCuentas1: '',
  otrasCuentas2: '',
  otrasCuentas3: '',
  ebitda1: '',
  ebitda2: '',
  ebitda3: '',
  gastoPersonal1: '',
  gastoPersonal2: '',
  gastoPersonal3: '',
  compras1: '',
  compras2: '',
  compras3: '',
  cashFlow1: '',
  cashFlow2: '',
  cashFlow3: ''
}

var dataBalanceFaker = {
  balancesEconomicos: dataBalancesEconomicosFaker,
  ratiosInformacion: dataRatiosInformationFaker,
  cuentasResultado: dataCuentasResultadoFaker,
  balancesEconomicosBis: dataBalancesEconomicosFakerBis,
  ratiosInformacionBis: dataratiosInformacionBis,
  cuentasResultadoBis: dataCuentasResultadosBisRequestFormFaker
}
var dataBaseReport = {
  empresa: '',
  codigoFiscal: '',
  general: GeneralInformationDataFaker,
  balance: dataBalanceFaker
}

export {
  ThemeCatalogueProvider,
  BoeForm,
  ConsultReports,
  CopyFileProcess,
  SimulationReport,
  FilesTableFTP,
  ReportDetail,
  ReportReferences,
  ReportSpain,
  ReportPortugal,
  ReportLatin,
  ReportFrance,
  RequestList,
  ShowReport,
  CreatedReports,
  MasiveGestion,
  UserMenu,
  BaseReport,
  ModalError,
  ModalSuccess
}

export type {
  IBoeForm,
  IConsultsReports,
  ICopyFileProcess,
  ISimulationReport,
  IFilesTableFTP,
  IReportDetail,
  IReportReferences,
  IReportsSpain,
  IReportPortugal,
  IReportLatin,
  IReportFrance,
  IRequestList,
  IShowReport,
  ICreatedReports,
  IMasiveGestion,
  IUserMenu,
  IModalError,
  IModalSuccess
}

export {
  ReportTypes,
  dataBaseReport,
  userDataFaker,
  applicationsFaker
}
