
interface I18n {
  'form:portugal:titulo': string
  'form:portugal:concepto:titulo': string
  'form:portugal:concepto:nregistro': string
  'form:portugal:concepto:nombre': string
  'form:portugal:concepto:direccion': string
  'form:portugal:concepto:localidad': string
  'form:portugal:concepto:provincia': string
  'form:portugal:concepto:codigopostal': string
  'form:portugal:concepto:telefono': string
  'form:portugal:concepto:fax': string
  'form:portugal:concepto:confidencialidad': string
  'form:portugal:concepto:alerta': string
  'form:portugal:concepto:consolidado': string
  'form:portugal:concepto:si': string
  'form:portugal:concepto:no': string
  'form:portugal:balance:titulo': string
  'form:portugal:balance:cifra': string
  'form:portugal:balance:origen': string
  'form:portugal:balance:fechascierre': string
  'form:portugal:balance:fechacierre1': string
  'form:portugal:balance:fechacierre2': string
  'form:portugal:balance:fechacierre3': string
  'form:portugal:balance:fechacierreheader1': string
  'form:portugal:balance:fechacierreheader2': string
  'form:portugal:balance:fechacierreheader3': string
  'form:portugal:table:disclaimer': string
  'form:portugal:table:actualizar': string
  'form:portugal:activonocorriente:header1': string
  'form:portugal:activonocorriente:header2': string
  'form:portugal:activonocorriente:header3': string
  'form:portugal:activonocorriente:1': string
  'form:portugal:activonocorriente:1.1': string
  'form:portugal:activonocorriente:1.2': string
  'form:portugal:activonocorriente:1.3': string
  'form:portugal:activonocorriente:1.4': string
  'form:portugal:activonocorriente:1.5': string
  'form:portugal:activonocorriente:1.6': string
  'form:portugal:activonocorriente:1.6.1': string
  'form:portugal:activonocorriente:1.6.2': string
  'form:portugal:activonocorriente:1.7': string
  'form:portugal:activonocorriente:1.8': string
  'form:portugal:activonocorriente:1.9': string
  'form:portugal:totalactivo': string
  'form:portugal:patrimonioneto:4': string
  'form:portugal:patrimonioneto:4.1': string
  'form:portugal:patrimonioneto:4.2': string
  'form:portugal:patrimonioneto:4.3': string
  'form:portugal:patrimonioneto:4.4': string
  'form:portugal:patrimonioneto:4.5': string
  'form:portugal:patrimonioneto:4.6': string
  'form:portugal:patrimonioneto:4.7': string
  'form:portugal:patrimonioneto:4.8': string
  'form:portugal:patrimonioneto:4.9': string
  'form:portugal:patrimonioneto:4.10': string
  'form:portugal:patrimonioneto:4.11': string
  'form:portugal:patrimonioneto:4.12': string
  'form:portugal:pasivonocorriente:header1': string
  'form:portugal:pasivonocorriente:header2': string
  'form:portugal:pasivonocorriente:header3': string
  'form:portugal:pasivonocorriente:5': string
  'form:portugal:pasivonocorriente:5.1': string
  'form:portugal:pasivonocorriente:5.2': string
  'form:portugal:pasivonocorriente:5.3': string
  'form:portugal:pasivonocorriente:5.4': string
  'form:portugal:pasivonocorriente:5.5': string
  'form:portugal:pasivocorriente:header1': string
  'form:portugal:pasivocorriente:header2': string
  'form:portugal:pasivocorriente:header3': string
  'form:portugal:pasivocorriente:6': string
  'form:portugal:pasivocorriente:6.1': string
  'form:portugal:pasivocorriente:6.2': string
  'form:portugal:pasivocorriente:6.3': string
  'form:portugal:pasivocorriente:6.3.1': string
  'form:portugal:pasivocorriente:6.3.2': string
  'form:portugal:pasivocorriente:6.4': string
  'form:portugal:pasivocorriente:6.4.1': string
  'form:portugal:pasivocorriente:6.4.2': string
  'form:portugal:pasivocorriente:6.4.3': string
  'form:portugal:pasivocorriente:6.4.4': string
  'form:portugal:pasivocorriente:6.4.5': string
  'form:portugal:pasivocorriente:6.4.6': string
  'form:portugal:pasivocorriente:6.4.7': string
  'form:portugal:pasivocorriente:6.4.8': string
  'form:portugal:totalpasivo:header1': string
  'form:portugal:totalpasivo:header2': string
  'form:portugal:totalpasivo:header3': string
  'form:portugal:totalpasivo': string
  'form:portugal:patrimonio': string
  'form:portugal:ventas:header1': string
  'form:portugal:ventas:header2': string
  'form:portugal:ventas:header3': string
  'form:portugal:ventas:01': string
  'form:portugal:ventas:02': string
  'form:portugal:ventas:03': string
  'form:portugal:ventas:04': string
  'form:portugal:ventas:05': string
  'form:portugal:ventas:06': string
  'form:portugal:ventas:07': string
  'form:portugal:ventas:08': string
  'form:portugal:ventas:14': string
  'form:portugal:ventas:15': string
  'form:portugal:ebitda:header1': string
  'form:portugal:ebitda:header2': string
  'form:portugal:ebitda:header3': string
  'form:portugal:ebitda:27': string
  'form:portugal:ebitda:17': string
  'form:portugal:ebitda:09': string
  'form:portugal:ebitda:10': string
  'form:portugal:ebitda:11': string
  'form:portugal:ebitda:16': string
  'form:portugal:ebitda:12': string
  'form:portugal:explotacion:header1': string
  'form:portugal:explotacion:header2': string
  'form:portugal:explotacion:header3': string
  'form:portugal:explotacion:25': string
  'form:portugal:explotacion:18': string
  'form:portugal:explotacion:13': string
  'form:portugal:explotacion:19': string
  'form:portugal:explotacion:20': string
  'form:portugal:explotacion:26': string
  'form:portugal:explotacion:21': string
  'form:portugal:explotacion:22': string
  'form:portugal:explotacion:23': string
  'form:portugal:explotacion:24': string
  'form:portugal:guardar': string
  'form:portugal:aceptar': string
  'form:portugal:cancelar': string
}

export interface IReportPortugal {
  readonly i18n: I18n
  balanceOrigenOpt: Array<{
    value: string
    label: string
  }>
  readonly formValues: {
    conceptoRegistro: string
    conceptoNombre: string
    conceptoDireccion: string
    conceptoLocalidad: string
    conceptoProvincia: string
    conceptoCodigoPostal: string
    conceptoTelefono: string
    conceptoFax: string
    conceptoConfidencialidad: string
    conceptoAlerta: string
    conceptoConsolidado: string
    balanceCifra: string
    balanceOrigen: string
    balanceFechacierre1Dia: string
    balanceFechacierre1Mes: string
    balanceFechacierre1Ano: string
    balanceFechacierre2Dia: string
    balanceFechacierre2Mes: string
    balanceFechacierre2Ano: string
    balanceFechacierre3Dia: string
    balanceFechacierre3Mes: string
    activonocorriente1_balance1: string
    activonocorriente1_balance2: string
    activonocorriente1_balance3: string
    activonocorriente1_1_balance1: string
    activonocorriente1_1_balance2: string
    activonocorriente1_1_balance3: string
    activonocorriente1_2_balance1: string
    activonocorriente1_2_balance2: string
    activonocorriente1_2_balance3: string
    activonocorriente1_3_balance1: string
    activonocorriente1_3_balance2: string
    activonocorriente1_3_balance3: string
    activonocorriente1_4_balance1: string
    activonocorriente1_4_balance2: string
    activonocorriente1_4_balance3: string
    activonocorriente1_5_balance1: string
    activonocorriente1_5_balance2: string
    activonocorriente1_5_balance3: string
    activonocorriente1_6_balance1: string
    activonocorriente1_6_balance2: string
    activonocorriente1_6_balance3: string
    activonocorriente1_6_1_balance1: string
    activonocorriente1_6_1_balance2: string
    activonocorriente1_6_1_balance3: string
    activonocorriente1_6_2_balance1: string
    activonocorriente1_6_2_balance2: string
    activonocorriente1_6_2_balance3: string
    activonocorriente1_7_balance1: string
    activonocorriente1_7_balance2: string
    activonocorriente1_7_balance3: string
    activonocorriente1_8_balance1: string
    activonocorriente1_8_balance2: string
    activonocorriente1_8_balance3: string
    activonocorriente1_9_balance1: string
    activonocorriente1_9_balance2: string
    activonocorriente1_9_balance3: string
    totalActivo_balance1: string
    totalActivo_balance2: string
    totalActivo_balance3: string
    patrimonioneto_4_balance1: string
    patrimonioneto_4_balance2: string
    patrimonioneto_4_balance3: string
    patrimonioneto_4_1_balance1: string
    patrimonioneto_4_1_balance2: string
    patrimonioneto_4_1_balance3: string
    patrimonioneto_4_2_balance1: string
    patrimonioneto_4_2_balance2: string
    patrimonioneto_4_2_balance3: string
    patrimonioneto_4_3_balance1: string
    patrimonioneto_4_3_balance2: string
    patrimonioneto_4_3_balance3: string
    patrimonioneto_4_4_balance1: string
    patrimonioneto_4_4_balance2: string
    patrimonioneto_4_4_balance3: string
    patrimonioneto_4_5_balance1: string
    patrimonioneto_4_5_balance2: string
    patrimonioneto_4_5_balance3: string
    patrimonioneto_4_6_balance1: string
    patrimonioneto_4_6_balance2: string
    patrimonioneto_4_6_balance3: string
    patrimonioneto_4_7_balance1: string
    patrimonioneto_4_7_balance2: string
    patrimonioneto_4_7_balance3: string
    patrimonioneto_4_8_balance1: string
    patrimonioneto_4_8_balance2: string
    patrimonioneto_4_8_balance3: string
    patrimonioneto_4_9_balance1: string
    patrimonioneto_4_9_balance2: string
    patrimonioneto_4_9_balance3: string
    patrimonioneto_4_10_balance1: string
    patrimonioneto_4_10_balance2: string
    patrimonioneto_4_10_balance3: string
    patrimonioneto_4_11_balance1: string
    patrimonioneto_4_11_balance2: string
    patrimonioneto_4_11_balance3: string
    patrimonioneto_4_12_balance1: string
    patrimonioneto_4_12_balance2: string
    patrimonioneto_4_12_balance3: string
    pasivonocorriente_5_balance1: string
    pasivonocorriente_5_balance2: string
    pasivonocorriente_5_balance3: string
    pasivonocorriente_5_1_balance1: string
    pasivonocorriente_5_1_balance2: string
    pasivonocorriente_5_1_balance3: string
    pasivonocorriente_5_2_balance1: string
    pasivonocorriente_5_2_balance2: string
    pasivonocorriente_5_2_balance3: string
    pasivonocorriente_5_3_balance1: string
    pasivonocorriente_5_3_balance2: string
    pasivonocorriente_5_3_balance3: string
    pasivonocorriente_5_4_balance1: string
    pasivonocorriente_5_4_balance2: string
    pasivonocorriente_5_4_balance3: string
    pasivonocorriente_5_5_balance1: string
    pasivonocorriente_5_5_balance2: string
    pasivonocorriente_5_5_balance3: string
    pasivocorriente_6_balance1: string
    pasivocorriente_6_balance2: string
    pasivocorriente_6_balance3: string
    pasivocorriente_6_1_balance1: string
    pasivocorriente_6_1_balance2: string
    pasivocorriente_6_1_balance3: string
    pasivocorriente_6_2_balance1: string
    pasivocorriente_6_2_balance2: string
    pasivocorriente_6_2_balance3: string
    pasivocorriente_6_3_balance1: string
    pasivocorriente_6_3_balance2: string
    pasivocorriente_6_3_balance3: string
    pasivocorriente_6_3_1_balance1: string
    pasivocorriente_6_3_1_balance2: string
    pasivocorriente_6_3_1_balance3: string
    pasivocorriente_6_3_2_balance1: string
    pasivocorriente_6_3_2_balance2: string
    pasivocorriente_6_3_2_balance3: string
    pasivocorriente_6_4_balance1: string
    pasivocorriente_6_4_balance2: string
    pasivocorriente_6_4_balance3: string
    pasivocorriente_6_4_1_balance1: string
    pasivocorriente_6_4_1_balance2: string
    pasivocorriente_6_4_1_balance3: string
    pasivocorriente_6_4_2_balance1: string
    pasivocorriente_6_4_2_balance2: string
    pasivocorriente_6_4_2_balance3: string
    pasivocorriente_6_4_3_balance1: string
    pasivocorriente_6_4_3_balance2: string
    pasivocorriente_6_4_3_balance3: string
    pasivocorriente_6_4_4_balance1: string
    pasivocorriente_6_4_4_balance2: string
    pasivocorriente_6_4_4_balance3: string
    pasivocorriente_6_4_5_balance1: string
    pasivocorriente_6_4_5_balance2: string
    pasivocorriente_6_4_5_balance3: string
    pasivocorriente_6_4_6_balance1: string
    pasivocorriente_6_4_6_balance2: string
    pasivocorriente_6_4_6_balance3: string
    pasivocorriente_6_4_7_balance1: string
    pasivocorriente_6_4_7_balance2: string
    pasivocorriente_6_4_7_balance3: string
    pasivocorriente_6_4_8_balance1: string
    pasivocorriente_6_4_8_balance2: string
    pasivocorriente_6_4_8_balance3: string
    totalpasivo_balance1: string
    totalpasivo_balance2: string
    totalpasivo_balance3: string
    totalpatrimonio_balance1: string
    totalpatrimonio_balance2: string
    totalpatrimonio_balance3: string
    ventas_01_balance1: string
    ventas_01_balance2: string
    ventas_01_balance3: string
    ventas_02_balance1: string
    ventas_02_balance2: string
    ventas_02_balance3: string
    ventas_03_balance1: string
    ventas_03_balance2: string
    ventas_03_balance3: string
    ventas_04_balance1: string
    ventas_04_balance2: string
    ventas_04_balance3: string
    ventas_05_balance1: string
    ventas_05_balance2: string
    ventas_05_balance3: string
    ventas_06_balance1: string
    ventas_06_balance2: string
    ventas_06_balance3: string
    ventas_07_balance1: string
    ventas_07_balance2: string
    ventas_07_balance3: string
    ventas_08_balance1: string
    ventas_08_balance2: string
    ventas_08_balance3: string
    ventas_14_balance1: string
    ventas_14_balance2: string
    ventas_14_balance3: string
    ventas_15_balance1: string
    ventas_15_balance2: string
    ventas_15_balance3: string
    ebitda_27_balance1: string
    ebitda_27_balance2: string
    ebitda_27_balance3: string
    ebitda_17_balance1: string
    ebitda_17_balance2: string
    ebitda_17_balance3: string
    ebitda_09_balance1: string
    ebitda_09_balance2: string
    ebitda_09_balance3: string
    ebitda_10_balance1: string
    ebitda_10_balance2: string
    ebitda_10_balance3: string
    ebitda_11_balance1: string
    ebitda_11_balance2: string
    ebitda_11_balance3: string
    ebitda_16_balance1: string
    ebitda_16_balance2: string
    ebitda_16_balance3: string
    ebitda_12_balance1: string
    ebitda_12_balance2: string
    ebitda_12_balance3: string
    explotacion_13_balance1: string
    explotacion_13_balance2: string
    explotacion_13_balance3: string
    explotacion_18_balance1: string
    explotacion_18_balance2: string
    explotacion_18_balance3: string
    explotacion_19_balance1: string
    explotacion_19_balance2: string
    explotacion_19_balance3: string
    explotacion_20_balance1: string
    explotacion_20_balance2: string
    explotacion_20_balance3: string
    explotacion_21_balance1: string
    explotacion_21_balance2: string
    explotacion_21_balance3: string
    explotacion_22_balance1: string
    explotacion_22_balance2: string
    explotacion_22_balance3: string
    explotacion_23_balance1: string
    explotacion_23_balance2: string
    explotacion_23_balance3: string
    explotacion_24_balance1: string
    explotacion_24_balance2: string
    explotacion_24_balance3: string
    explotacion_25_balance1: string
    explotacion_25_balance2: string
    explotacion_25_balance3: string
    explotacion_26_balance1: string
    explotacion_26_balance2: string
    explotacion_26_balance3: string
    auditoria: string
  }
  readonly formLoading: boolean
  readonly formRecoverDataError: boolean
  readonly saveSuccess: boolean
  readonly saveLoading: boolean
  readonly acceptSuccess: boolean
  readonly acceptLoading: boolean
  readonly handleCancel: () => void
  readonly handleSave: (params) => void
  readonly handleAccept: (params) => void
  readonly handleSubmit: (params) => void
  readonly validateActivoNoCorriente: (params) => void
  readonly validatePatrimonioNeto: (params) => void
  readonly validatePasivoNoCorriente: (params) => void
  readonly validatePasivoCorriente: (params) => void
  readonly validateTotalPasivo: (params) => void
  readonly validateVentas: (params) => void
  readonly validateEbitda: (params) => void
  readonly validateExplotacion: (params) => void
}
