interface Ii18nRatiosInformationBis {
  'RatiosInformationBis:activo:title': string
  'RatiosInformationBis:labelTbEjercicio1': string
  'RatiosInformationBis:labelTbEjercicio2': string
  'RatiosInformationBis:labelTbEjercicio3': string
  'RatiosInformationBis:activo:detailTbCapital': string
  'RatiosInformationBis:activo:detailTbActivoFijo': string
  'RatiosInformationBis:activo:detailTbInmovilizadoIntangible': string
  'RatiosInformationBis:activo:detailTbInmovilizadoIntangible_1': string
  'RatiosInformationBis:activo:detailTbInmovilizadoIntangible_2': string
  'RatiosInformationBis:activo:detailTbInmovilizadoIntangible_3': string
  'RatiosInformationBis:activo:detailTbInmovilizadoIntangible_4': string
  'RatiosInformationBis:activo:detailTbInmovilizadoIntangible_5': string
  'RatiosInformationBis:activo:detailTbInmovilizadoIntangible_6': string
  'RatiosInformationBis:activo:detailTbInmovilizadoMaterial': string
  'RatiosInformationBis:activo:detailTbInmovilizadoMaterial_1': string
  'RatiosInformationBis:activo:detailTbInmovilizadoMaterial_2': string
  'RatiosInformationBis:activo:detailTbInmovilizadoMaterial_3': string
  'RatiosInformationBis:activo:detailTbInmovilizadoMaterial_4': string
  'RatiosInformationBis:activo:detailTbInmovilizadoMaterial_5': string
  'RatiosInformationBis:activo:detailTbInmovilizadoMaterial_6': string
  'RatiosInformationBis:activo:detailTbInmovilizadoFinanciero': string
  'RatiosInformationBis:activo:detailTbInmovilizadoFinanciero_1': string
  'RatiosInformationBis:activo:detailTbInmovilizadoFinanciero_2': string
  'RatiosInformationBis:activo:detailTbInmovilizadoFinanciero_3': string
  'RatiosInformationBis:activo:detailTbInmovilizadoFinanciero_4': string
  'RatiosInformationBis:activo:detailTbInmovilizadoFinanciero_5': string
  'RatiosInformationBis:activo:detailTbInmovilizadoFinanciero_6': string
  'RatiosInformationBis:activo:detailTbActivoCirculante': string
  'RatiosInformationBis:activo:detailTbExistencias': string
  'RatiosInformationBis:activo:detailTbExistencias_1': string
  'RatiosInformationBis:activo:detailTbExistencias_2': string
  'RatiosInformationBis:activo:detailTbExistencias_3': string
  'RatiosInformationBis:activo:detailTbExistencias_4': string
  'RatiosInformationBis:activo:detailTbExistencias_5': string
  'RatiosInformationBis:activo:detailTbAnticipos': string
  'RatiosInformationBis:activo:detailTbDeudores': string
  'RatiosInformationBis:activo:detailTbDeudores_1': string
  'RatiosInformationBis:activo:detailTbDeudores_2': string
  'RatiosInformationBis:activo:detailTbDeudores_3': string
  'RatiosInformationBis:activo:detailTbVarios': string
  'RatiosInformationBis:activo:detailTbVarios_1': string
  'RatiosInformationBis:activo:detailTbVarios_2': string
  'RatiosInformationBis:activo:detailTbOtros': string
  'RatiosInformationBis:activo:detailTbOtros_1': string
  'RatiosInformationBis:activo:detailTbOtros_2': string
  'RatiosInformationBis:activo:detailTbOtros_3': string
  'RatiosInformationBis:activo:detailTbOtros_4': string
  'RatiosInformationBis:activo:detailTbTotalActivo': string
  'RatiosInformationBis:activo:detailTbOtrasCuentas': string
  'RatiosInformationBis:activo:detailTbTotalCuentas': string
  'RatiosInformationBis:activo:detailTbPrestamosFamiliares': string
  'RatiosInformationBis:pasivo:title': string
  'RatiosInformationBis:pasivo:detailTbPatrimonio': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_1': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_2': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_3': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_4': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_5': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_6': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_7': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_8': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_9': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_10': string
  'RatiosInformationBis:pasivo:detailTbFondosPropios_11': string
  'RatiosInformationBis:pasivo:detailTbOtrosFondos': string
  'RatiosInformationBis:pasivo:detailTbOtrosFondos_1': string
  'RatiosInformationBis:pasivo:detailTbOtrosFondos_2': string
  'RatiosInformationBis:pasivo:detailTbProviciones': string
  'RatiosInformationBis:pasivo:detailTbProviciones_1': string
  'RatiosInformationBis:pasivo:detailTbProviciones_2': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_1': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_2': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_3': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_4': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_5': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_6': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_7': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_8': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudas_9': string
  'RatiosInformationBis:pasivo:detailTbCuentasRegulacion': string
  'RatiosInformationBis:pasivo:detailTbCuentasRegulacion_10': string
  'RatiosInformationBis:pasivo:detailTbCuentasPasivo': string
  'RatiosInformationBis:pasivo:detailTbTotalPasivo': string
  'RatiosInformationBis:pasivo:detailTbReferencias': string
  'RatiosInformationBis:pasivo:detailTbReferencias_1': string
  'RatiosInformationBis:pasivo:detailTbReferencias_2': string
  'RatiosInformationBis:pasivo:detailTbReferencias_3': string
  'RatiosInformationBis:pasivo:detailTbReferencias_4': string
  'RatiosInformationBis:pasivo:detailTbReferencias_5': string
  'RatiosInformationBis:pasivo:detailTbReferencias_6': string
  'RatiosInformationBis:pasivo:detailTbReferencias_7': string
  'RatiosInformationBis:pasivo:detailTbOtrasCuentas': string
  'RatiosInformationBis:pasivo:detailTbOtrasCuentas_1': string
  'RatiosInformationBis:pasivo:detailTbOtrasCuentas_2': string
  'RatiosInformationBis:pasivo:detailTbOtrasCuentas_3': string
  'RatiosInformationBis:pasivo:detailTbPasivoCirculante': string
  'RatiosInformationBis:pasivo:detailTbTotalDeudasCortoPlazo': string
}

export interface IRatiosActivoBisRequestForm {
  capital1: string
  capital2: string
  capital3: string
  activoFijo1: string
  activoFijo2: string
  activoFijo3: string
  inmovilizadoIntangible1: string
  inmovilizadoIntangible2: string
  inmovilizadoIntangible3: string
  inmovilizadoIntangible_11: string
  inmovilizadoIntangible_12: string
  inmovilizadoIntangible_13: string
  inmovilizadoIntangible_21: string
  inmovilizadoIntangible_22: string
  inmovilizadoIntangible_23: string
  inmovilizadoIntangible_31: string
  inmovilizadoIntangible_32: string
  inmovilizadoIntangible_33: string
  inmovilizadoIntangible_41: string
  inmovilizadoIntangible_42: string
  inmovilizadoIntangible_43: string
  inmovilizadoIntangible_51: string
  inmovilizadoIntangible_52: string
  inmovilizadoIntangible_53: string
  inmovilizadoIntangible_61: string
  inmovilizadoIntangible_62: string
  inmovilizadoIntangible_63: string
  inmovilizadoMaterial1: string
  inmovilizadoMaterial2: string
  inmovilizadoMaterial3: string
  inmovilizadoMaterial_11: string
  inmovilizadoMaterial_12: string
  inmovilizadoMaterial_13: string
  inmovilizadoMaterial_21: string
  inmovilizadoMaterial_22: string
  inmovilizadoMaterial_23: string
  inmovilizadoMaterial_31: string
  inmovilizadoMaterial_32: string
  inmovilizadoMaterial_33: string
  inmovilizadoMaterial_41: string
  inmovilizadoMaterial_42: string
  inmovilizadoMaterial_43: string
  inmovilizadoMaterial_51: string
  inmovilizadoMaterial_52: string
  inmovilizadoMaterial_53: string
  inmovilizadoMaterial_61: string
  inmovilizadoMaterial_62: string
  inmovilizadoMaterial_63: string
  inmovilizadoFinanciero1: string
  inmovilizadoFinanciero2: string
  inmovilizadoFinanciero3: string
  inmovilizadoFinanciero_11: string
  inmovilizadoFinanciero_12: string
  inmovilizadoFinanciero_13: string
  inmovilizadoFinanciero_21: string
  inmovilizadoFinanciero_22: string
  inmovilizadoFinanciero_23: string
  inmovilizadoFinanciero_31: string
  inmovilizadoFinanciero_32: string
  inmovilizadoFinanciero_33: string
  inmovilizadoFinanciero_41: string
  inmovilizadoFinanciero_42: string
  inmovilizadoFinanciero_43: string
  inmovilizadoFinanciero_51: string
  inmovilizadoFinanciero_52: string
  inmovilizadoFinanciero_53: string
  inmovilizadoFinanciero_61: string
  inmovilizadoFinanciero_62: string
  inmovilizadoFinanciero_63: string
  activoCirculante1: string
  activoCirculante2: string
  activoCirculante3: string
  existencias1: string
  existencias2: string
  existencias3: string
  existencias_11: string
  existencias_12: string
  existencias_13: string
  existencias_21: string
  existencias_22: string
  existencias_23: string
  existencias_31: string
  existencias_32: string
  existencias_33: string
  existencias_41: string
  existencias_42: string
  existencias_43: string
  existencias_51: string
  existencias_52: string
  existencias_53: string
  anticipos1: string
  anticipos2: string
  anticipos3: string
  deudores1: string
  deudores2: string
  deudores3: string
  deudores_11: string
  deudores_12: string
  deudores_13: string
  deudores_21: string
  deudores_22: string
  deudores_23: string
  deudores_31: string
  deudores_32: string
  deudores_33: string
  varios1: string
  varios2: string
  varios3: string
  varios_11: string
  varios_12: string
  varios_13: string
  varios_21: string
  varios_22: string
  varios_23: string
  otros1: string
  otros2: string
  otros3: string
  otros_11: string
  otros_12: string
  otros_13: string
  otros_21: string
  otros_22: string
  otros_23: string
  otros_31: string
  otros_32: string
  otros_33: string
  otros_41: string
  otros_42: string
  otros_43: string
  totalActivo1: string
  totalActivo2: string
  totalActivo3: string
  otrasCuentas1: string
  otrasCuentas2: string
  otrasCuentas3: string
  totalCuentas1: string
  totalCuentas2: string
  totalCuentas3: string
  prestamosFamiliares1: string
  prestamosFamiliares2: string
  prestamosFamiliares3: string
}

export interface IRatiosPasivoBisRequestForm {
  patrimonio1: string
  patrimonio2: string
  patrimonio3: string
  fondosPropios1: string
  fondosPropios2: string
  fondosPropios3: string
  fondosPropios_11: string
  fondosPropios_12: string
  fondosPropios_13: string
  fondosPropios_21: string
  fondosPropios_22: string
  fondosPropios_23: string
  fondosPropios_31: string
  fondosPropios_32: string
  fondosPropios_33: string
  fondosPropios_41: string
  fondosPropios_42: string
  fondosPropios_43: string
  fondosPropios_51: string
  fondosPropios_52: string
  fondosPropios_53: string
  fondosPropios_61: string
  fondosPropios_62: string
  fondosPropios_63: string
  fondosPropios_71: string
  fondosPropios_72: string
  fondosPropios_73: string
  fondosPropios_81: string
  fondosPropios_82: string
  fondosPropios_83: string
  fondosPropios_91: string
  fondosPropios_92: string
  fondosPropios_93: string
  fondosPropios_101: string
  fondosPropios_102: string
  fondosPropios_103: string
  fondosPropios_111: string
  fondosPropios_112: string
  fondosPropios_113: string
  otrosFondos1: string
  otrosFondos2: string
  otrosFondos3: string
  otrosFondos_11: string
  otrosFondos_12: string
  otrosFondos_13: string
  otrosFondos_21: string
  otrosFondos_22: string
  otrosFondos_23: string
  proviciones1: string
  proviciones2: string
  proviciones3: string
  proviciones_11: string
  proviciones_12: string
  proviciones_13: string
  proviciones_21: string
  proviciones_22: string
  proviciones_23: string
  totalDeudas1: string
  totalDeudas2: string
  totalDeudas3: string
  totalDeudas_11: string
  totalDeudas_12: string
  totalDeudas_13: string
  totalDeudas_21: string
  totalDeudas_22: string
  totalDeudas_23: string
  totalDeudas_31: string
  totalDeudas_32: string
  totalDeudas_33: string
  totalDeudas_41: string
  totalDeudas_42: string
  totalDeudas_43: string
  totalDeudas_51: string
  totalDeudas_52: string
  totalDeudas_53: string
  totalDeudas_61: string
  totalDeudas_62: string
  totalDeudas_63: string
  totalDeudas_71: string
  totalDeudas_72: string
  totalDeudas_73: string
  totalDeudas_81: string
  totalDeudas_82: string
  totalDeudas_83: string
  totalDeudas_91: string
  totalDeudas_92: string
  totalDeudas_93: string
  cuentasRegulacion1: string
  cuentasRegulacion2: string
  cuentasRegulacion3: string
  cuentasRegulacion_101: string
  cuentasRegulacion_102: string
  cuentasRegulacion_103: string
  cuentasPasivo1: string
  cuentasPasivo2: string
  cuentasPasivo3: string
  totalPasivo1: string
  totalPasivo2: string
  totalPasivo3: string
  referencias1: string
  referencias2: string
  referencias3: string
  referencias_11: string
  referencias_12: string
  referencias_13: string
  referencias_21: string
  referencias_22: string
  referencias_23: string
  referencias_31: string
  referencias_32: string
  referencias_33: string
  referencias_41: string
  referencias_42: string
  referencias_43: string
  referencias_51: string
  referencias_52: string
  referencias_53: string
  referencias_61: string
  referencias_62: string
  referencias_63: string
  referencias_71: string
  referencias_72: string
  referencias_73: string
  otrasCuentas1: string
  otrasCuentas2: string
  otrasCuentas3: string
  otrasCuentas_11: string
  otrasCuentas_12: string
  otrasCuentas_13: string
  otrasCuentas_21: string
  otrasCuentas_22: string
  otrasCuentas_23: string
  otrasCuentas_31: string
  otrasCuentas_32: string
  otrasCuentas_33: string
  pasivoCirculante1: string
  pasivoCirculante2: string
  pasivoCirculante3: string
  totalDeudasCortoPlazo1: string
  totalDeudasCortoPlazo2: string
  totalDeudasCortoPlazo3: string
}

export interface IRatiosInformationBisRequestForm {
  activo: IRatiosActivoBisRequestForm
  pasivo: IRatiosPasivoBisRequestForm
}

export interface IRatiosInformationBis {
  i18n: Ii18nRatiosInformationBis
  data: IRatiosInformationBisRequestForm
}
